### ISSUE TITLE
implement native app banners

### ISSUE THREAD

**Issue by SadisticSun** [part-up/part-up#1007]
When the user navigates to and through the application on their mobile device a banner should popup referring them to download the native Part-Up app.

**Comment by ralphboeije** [comment]
I think we can implement this using the intercom interface that we have running. No code needed here. Thanks for the pointer and good idea anyway.

**Comment by wouterd** [comment]
I personally hate those popups, if I decide to go to a website in my mobile browser, I want to use the mobile site, not download some app.

**Comment by ralphboeije** [comment]
Until the app supports the full Part-up experience, this is not an issue we should take on.
