### ISSUE TITLE
Add "mark as complete" to dropdown of activities on activity card

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1022]
Based on user experience in agile workflow, a user wants to mark an activity as completed after the demo of the activities in the "Done (or other name)" lane. Now this takes 5 clicks for a roundtrip (go to activity detail, click edit, click mark as completed, click save, click back to activities). This proposal would reduce that to 1 click.

Complexity: 13

**Comment by jplattel** [comment]
You do need to know which Lane is the _done_ lane, this might not always be the last one...

**Comment by ralphboeije** [comment]
So you need to add this feature to every lane instead

**Comment by noelheesen** [comment]
@ralphboeije This is pushing to staging now on the branch 'feat-activity-dropdown-archive'. I guess we want the activity removed from the current lane when it's archived? (which is not happening atm)

**Comment by ralphboeije** [comment]
@noelheesen no, don't hide it. It gets greyed out when it is archived. That is enough. When you remove them from the lane, the history is gone. There is a delete action for that.

**Comment by ralphboeije** [comment]
@noelheesen Two findings (first one due to bad DoD, my fault):
- After "mark as complete" (archiving), the dropdown menu item should switch to the existing "make as active" option that you also have on the activity detail. (now you can archive an archived activity again, but nothing happens of course)
- there is no need for the confirmation pop-up, as it also doesn't exist on the activity detail and when the first point is realized, it can easily be undone
