### ISSUE TITLE
Kadira subs undefined for network

### ISSUE THREAD

**Issue by noelheesen** [part-up/part-up#1023]
In the leaveNetwork() function in partup-client-pages/app/network/network.js 'Subs.reset()' is called but undefined. 'Subs' is from the Kadira subs-manager package.

![subs undefined](https://cloud.githubusercontent.com/assets/18031130/25126049/28259dd6-2431-11e7-9b5e-848f85c880ef.png)

**Comment by jplattel** [comment]
Had some time to look into this, according to: https://github.com/kadirahq/subs-manager the reset function is being used to renew subscriptions, but that isn't needed as far as I tested...

**Comment by jplattel** [comment]
Removing the call doesn't alter any functionality, thus I'm closing this issue..
