### ISSUE TITLE
Test findings build 2.13.0-2-ge830a70

### ISSUE THREAD

**Issue by noelheesen** [part-up/part-up#1038]
# Testing Acceptance build 2.13.0-2-ge830a70

- [x] Marketo
- [x] Tribe Landingpage
- [x] Activity invite
- [x] Tribe navigation cog
- [ ] Media upload: complexity 55

## Marketo
- It seems marketo only loads after a page refresh when the user accepted the cookies instead of right away;
- When clearing your privacy data in the browser while being in a session the script won't get removed before a browser refresh is done;
![merketo](https://cloud.githubusercontent.com/assets/18031130/25783934/dbc00718-3364-11e7-953f-5a31ab2a749e.PNG)

## Tribe landingpage
- The new homepage for a tribe uses '?show=true', there is no option to navigate to '?show=false' where you can see all part-ups (only if you manually type ?show=false)
  - this way you can only see the most popular part-ups from that tribe even if the tribe is open
The page in the picture below is not accessible anymore if you are not logged in.
![showisfalse](https://cloud.githubusercontent.com/assets/18031130/25783955/24c1af52-3365-11e7-85ba-a66ba7cdee76.PNG)

## Activity invite
- When inviting someone by e-mail a new usertile is created at 'pending invites' which will never load data
  - This does not happen when inviting someone by email to a part-up (no usertile created)
- Also able to invite people already assigned to the activity
![activities-email](https://cloud.githubusercontent.com/assets/18031130/25783960/3ff47aca-3365-11e7-9ea9-9de0522ce232.PNG)

## Tribe navigation cog
- When making the window smaller the cog disappears behind the dropdown
  - This is caused by the activity cog (I have put css in the wrong place)
![tribecog](https://cloud.githubusercontent.com/assets/18031130/25783963/60722e78-3365-11e7-957c-6874bf023508.PNG)

## Media upload
- File types can be removed in dropdown
- Can't upload in IE/Edge (stays spinning)
![uploadie](https://cloud.githubusercontent.com/assets/18031130/25783970/7d2d3a12-3365-11e7-982e-f07c97c745f4.PNG)

**Comment by ralphboeije** [comment]
Issue nr 2 is related to the fact that the part-ups are not showing on the tribe landing page for not logged in users.

**Comment by noelheesen** [comment]
Some more info about the request with IE:

![ierequesttimeout](https://cloud.githubusercontent.com/assets/18031130/25793929/0616bec0-33cf-11e7-9385-6c96dce7246f.PNG)
![ierequestbody](https://cloud.githubusercontent.com/assets/18031130/25793935/0d00a804-33cf-11e7-80f5-62f8da690008.PNG)

![requestchrome](https://cloud.githubusercontent.com/assets/18031130/25793940/140c7466-33cf-11e7-9c68-7dbd999590aa.PNG)
