### ISSUE TITLE
In safari the Members tab on a tribe won't load

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1040]
And Part-up keeps trying to connect. Also found on chrome on iOS

<img width="1440" alt="screen shot 2017-05-07 at 22 16 40" src="https://cloud.githubusercontent.com/assets/14044235/25784762/ed4959a4-3372-11e7-86cf-ae56120d1528.png">

**Comment by andreleon** [comment]
update: this seems to be a known issue: https://forums.meteor.com/t/failed-to-send-websocket-frame/35672/2

**Comment by andreleon** [comment]
![screen shot 2017-08-11 at 15 38 42](https://user-images.githubusercontent.com/1391492/29215385-201d0b72-7eab-11e7-97da-3c143f0a4097.png)

**Comment by andreleon** [comment]
![screen shot 2017-08-11 at 15 38 50](https://user-images.githubusercontent.com/1391492/29215390-24632b1c-7eab-11e7-9e87-36d549f2ebf8.png)

**Comment by andreleon** [comment]
We discovered that a meteor method was sending too much data, we hope this was causing the flickering on this page on safari. According to the meteor forums Safari doesn't like more than 5000 bytes per websocket frame, this method was sending over 90000 bytes. I reduces this to 2000, well within the limit.

I'm afraid we won't know if this is fixed until we test is with a tribe that has as many data/uppers as some in production.
