### ISSUE TITLE
Show tribe in My tribes even when not member of the tribe yet (but partner/supporter in a part-up in that tribe)

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1050]
Complexity: 21

**Comment by noelheesen** [comment]
It is because the filter is set to check if the part-up itself belongs to a tribe or not. It does not pass the part-ups you are a member of when not in the tribe itself.
(tribes.js 228) <- _so I can find it again_

**Comment by ralphboeije** [comment]
Ah check, maybe we should just add the tribe, even if you are not member. With the new landingpage this is not an issue anymore.

**Comment by noelheesen** [comment]
@ralphboeije This one should be fixed now. 

I couldn't test 2 scenario's:
- user is (s)upp of loads of part-ups and loading takes long;
- user is not (s)upp of any part-up, in this case.

Both of these have to do with the loading indicator. Setting up the fixtures to be able to test this would take half the time it took to implement it, which is about 5~ hours.

**Comment by ralphboeije** [comment]
Let's test those scenario's in acceptance then
