### ISSUE TITLE
Activity Card Board improvements

### ISSUE THREAD

**Issue by noelheesen** [part-up/part-up#1072]
There are some minor improvements to be made on the activity boardview card, see #1022 

- [x] When an activity is archived the card's hover state should remain grey;
- [ ] Dropdown is placed a bit too much to the left;
- [ ] Reduce the padding and dividers to make the dropdown a bit more compact;
- [ ] There is no visual feedback when the user (un)archives an activity until an event is triggered, such as moving the mouse;
- [ ] Markdown not limited to 2 lines on card

**Comment by ralphboeije** [comment]
To add: 
- [ ] move action buttons on activity detail on mobile to new row. Remove right column of activity detail on mobile.
