### ISSUE TITLE
Import lodash as lodash in mytribes

### ISSUE THREAD

**Issue by noelheesen** [part-up/part-up#1076]
Lodash and underscore both use '_', by assigning one to _ it will overwrite the other. The variable lodash is defined in global scope but not usable within a meteor template.

There has to be a way to use lodash outside and within a meteor template.

**Comment by noelheesen** [comment]
@jplattel I've CLogged both 'lodash' and '_' and they are actually the same thing. However, if I use 'import _ from lodash' _ is something different because it then get's imported from the lib. Still not figured out how they manage these dependencies so will continue to investigate further.

An option would be renaming _ in the import statement but it would be confusing I think. Another interesting thing is that 'lodash' does not have '.unionBy' but when I use import _ from lodash it has '.unionBy'...

I suggest I leave the import statement for now and we should decide how to manage lodash and underscore (<- doesn't get used) in the app in general.

**Comment by jplattel** [comment]
Agreed, let's discuss this tomorrow :)

**Comment by noelheesen** [comment]
Closed after discussing this with jplattel. _ gives extra functionality so an import is needed.
