### ISSUE TITLE
Archived date shows current date instead of archivedAt date

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1085]
See this part-up: https://part-up.com/partups/backfeed-protocol-integration-with-part-up-sHtwyFWvTrmBZhzuQ/updates

![schermafbeelding 2017-05-26 om 16 48 49](https://cloud.githubusercontent.com/assets/14044235/26499527/53784f86-4233-11e7-8182-b4552ee7f838.png)

**Comment by jplattel** [comment]
If you look at the page now it looks like it displays the current date as the archive date, while it has a different date (2016-7-7) in the database. Maybe the formatter is broken in `app/packages/partup-client-base/helpers/dateFormatters.js` ? (partupDateOnly)

**Comment by andreleon** [comment]
I'm not really sure what causes this issue since we use moment for date formatting, and we use the correct date 🤔  Maybe using a different moment formatter like `moment(date).calendar()` would help. But I'm not sure
