### ISSUE TITLE
Downgrade these packages always (because of bootstrap ugglyness) when doing Meteor upgrade

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1092]
check this commit: https://github.com/part-up/part-up/commit/18bcad3ccd90347f07acfca7da7ad43bda10b90f
- yogiben:autoform-tags@0.1.3
- sergeyt:typeahead@0.11.1_8
- yogiben:autoform-tags@0.1.3

**Comment by wouterd** [comment]
This is really dangerous, we're "fixing" a cosmetic issue by introducing an old version of a package with possibly all kinds of security issues and compatiblity problems with new meteor versions. We must not want this.

**Comment by ralphboeije** [comment]
see #1086
