### ISSUE TITLE
iPad/iPhone issue with recognizing tap on form field

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1097]
To reproduce:
- Go to part-up.com/register on ipad or iphone
- Try to enter your name / email / etc and see that you need to tap 3-5 times before it activates the form field and loads the keyboard

Maybe related: tags input not working correctly. needs retesting.

**Comment by andreleon** [comment]
@ralphboeije Can you verify that this is still an issue? I tested it on several devices and I didn't have to tap multiple times before the keyboard activated.

**Comment by ralphboeije** [comment]
Hi @andreleon I just retested this use case and it seems to work perfect now on the log in flow. I also tested other form fields and only found that it still occurs consistently on the new message modal on a part-up.

**Comment by ralphboeije** [comment]
@andreleon I just reproduced it consistently. It has to do with the force with which you touch on your ios device. A simple tap won't do, you really need to touch with some force.

**Comment by andreleon** [comment]
@ralphboeije Isn't that an issue with the way you user your device? I cannot reproduce this at all..

**Comment by ralphboeije** [comment]
yes indeed, so I'll close this for now
