### ISSUE TITLE
Login not working or lost after refresh in IE

### ISSUE THREAD

**Issue by noelheesen** [part-up/part-up#1128]
After upgrading to Meteor 1.5 we've removed the custom .babelrc scripts so the platform worked again on IE. The result of this is that IE users simply can't login at all or get logged out after a page refresh.

**Comment by noelheesen** [comment]
When running 'meteur run' and opening the site on IE the following message appears:

`You are running a browser with no localStorage or userData support. Logging in from one tab will not cause another tab to be logged in.`

There's a difference in the localStorage object from IE and from Chrome:

**Chrome**:
![localstorage-chrome](https://user-images.githubusercontent.com/18031130/27397125-9ef29a8e-56b5-11e7-8559-b04f8032d98e.PNG)

**IE**:
![localstorage-ie](https://user-images.githubusercontent.com/18031130/27397126-9ef8d3a4-56b5-11e7-8d04-0fa10228a010.PNG)

It seems the get and set value functions are just strings in the localStorage object of IE and thus meteor can't use those to store login tokens.

**Comment by noelheesen** [comment]
Haven't found the solution yet, @peterpeerdeman @andreleon could you guys take a look as well?

**Comment by noelheesen** [comment]
This is the file that holds the message: https://github.com/meteor/meteor/blob/master/packages/localstorage/localstorage.js

**Comment by ralphboeije** [comment]
ref to #1127

**Comment by andreleon** [comment]
It has to do with this issue: https://github.com/meteor/meteor/pull/1291

calling window.localStorage can cause IE to throw an error, we don't see this error because in the file @noelheesen references they `try {} catch(e) {}` it. So somehow the upgrade to meteor 1.5 causes this error.

**Comment by andreleon** [comment]
Localstorage error: 
https://social.technet.microsoft.com/Forums/ie/en-US/066767a5-f9d5-45f4-95cf-dcd0ff030090/script5-access-is-denied-error-when-accessing-web-sites-using-localstorage?forum=ieitprocurrentver

**Comment by andreleon** [comment]
It has to do with the `SCRIPT5: Access is denied.` message in the console of IE.

**Comment by ralphboeije** [comment]
And is there a solution in sight @andreleon ?

**Comment by andreleon** [comment]
Still working on it

**Comment by andreleon** [comment]
@ralphboeije I determined that the login issue was already in partup before the upgrade to meteor 1.5. I reverted my branch to commit fbbec861e2e35ef95be6e664033a01146f9caf60 and the problem still persists

**Comment by ralphboeije** [comment]
@andreleon that is quite odd, as I have never had one single user report this issue. @noelheesen how do you look at this?

**Comment by ralphboeije** [comment]
Just discussed this with Noel, @andreleon. After the upgrade to 1.5 Part-up didn't load at all on IE. The cause of that appeared to be the babel runtime. So we assumed this refresh issue was related, as we never heard about it before/found it in acceptance testing on IE.

**Comment by ralphboeije** [comment]
@tlimpanont advised to use Polyfill: https://github.com/mortzdk/localStorage

**Comment by ralphboeije** [comment]
Maybe Polyfill also fixes the issue that when you have www.part-up.com in the url, that you are not logged in, even though you are logged in to part-up.com in another tab?

**Comment by andreleon** [comment]
I have tried a localStorage polyfill in my attempt to fix this issue, but don't let that stop you from trying.

**Comment by ralphboeije** [comment]
Thanks for sharing @andreleon ! no easy fix then after all. BTW, @noelheesen thinks it has to do with this PR on the Meteor project instead of the Script 5 issue that you referenced above. What do you think? https://github.com/meteor/meteor/pull/8852

**Comment by andreleon** [comment]
Yes I agree, I tried to fix these proxy methods myself without any luck. Have you tried using this pull-request in a test environment?
