### ISSUE TITLE
Chat optimization

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1130]
@noelheesen and @andreleon please add your findings here

**Comment by andreleon** [comment]
Chatmessage: (ChatMessage.js)
- Iedere chatmessage subscribed op de creator
    - volgens mij gebeurt dit al in de chat subscription
    - anders moet dit worden gerefactored naar de overkoepelende subscription

One on one chats: (OneOnOneChat.js)
- te veel chats worden daar opgehaald
    - Infinite scroll/showmore button in /chats list
    - http gets ervan maken met infinite scroll

Chats dropdown: (chat-notifications.js)
- one on one chats worden hier nog volledig getoond
    - Inifnite scroll/showmore button in chats dropdown
    - gelimiteerde weergave zal het switchen van tab sneller maken
        - http gets ervan maken met infinite scroll
    - chatData helper kan geoptimaliseerd en gesplitst worden in 2 template helpers

**Comment by noelheesen** [comment]
Subscriptions & HTTP calls
- Data throttlen en alleen ophalen wat nodig is

Chat menu's
- Infinite scroll

Chat publications: (publications/chats.js)
- Omzetten naar HTTP.get calls en publications alleen nog gebruiken voor individuele updates;

Plaatjes
- exposen als resource via rest;

**Comment by andreleon** [comment]
@ralphboeije I have done a significant refactor of the way we manage our chat data.

Some of the things i did to achieve this:
1. Splitted the reactive and static data from each other
2. Created a few new (very light) subscriptions that manage:
- private chat online status
- private and network chat unread count
- private and network latest message
3. Created a routepublication for all the static(unchanging) data that only sends the necessary data
4. Created a client-side chatdata manager that is used by both the chat-notifications dropdown and the one-on-one chats list.
5. added load-more buttons to reduce initial load

To paint a little picture of the improvements this brings:

This was tested with Erik Soonieus's very heavy user profile
before:
![1](https://user-images.githubusercontent.com/1391492/27687754-647d51d6-5cd8-11e7-9c10-5eb986fb1171.gif)

after:
![2](https://user-images.githubusercontent.com/1391492/27687763-6b9a55c2-5cd8-11e7-80ac-c6417e189080.gif)

ps:
Even without the 'load-more' button it still perfoms very well, but for future-proofing sake lets keep it?
