### ISSUE TITLE
Optimize MyTribes menu

### ISSUE THREAD

**Issue by noelheesen** [part-up/part-up#1131]
- MyTribes menu omzetten naar een REST call;
- Op de back-end geen publicaties meer aanspreken;

**Comment by andreleon** [comment]
@ralphboeije op verzoek van jou deel ik hier mijn feedback voor @noelheesen 

Hey noel, wat is de reden dat je je /users/me/menu/networks en /users/me/menu/partups niet hebt samengevoegd in 1 call?

De routepublications zien er al een stuk beter uit, wat ik nog wel zou veranderen zijn de volgende puntjes:
- iets specifieker zijn in de fields die je nodig hebt per find. Je bent namelijk erg specifiek bij partups en networks, maar dan weer niet bij de images die je ophaalt.

Je hebt bijvoorbeeld alleen de copies.80x80 nodig voor in het my-tribes menu

En de structuur van de publicatie zou ik iets anders doen. Namelijk de manier waarop de images worden opgehaald. Er wordt nu per partup een mongo call gedaan, dat is best wel zwaar voor de server. Als iemand dus lid is van 100 partups, wordt er 1 mongo dearch gedaan om die partups op te halen, maar per partup wordt er nog een aparte search gedaan om een image object te vinden.

het gaat dus specifiek om dit soort stukjes: 

`app/packages/partup-server/publications/users.js:45`
```.js
children: [
    { find: Images.findForPartup }
]
```
hiermee zeg je namelijk; Per partup, wil ik 1 voor 1 een image hebben, dus je doet bij 100 partups, 100 calls naar mongodb

Kijk even naar mijn refactor van `/users/me/menu/partups`:
```.js
Meteor.routeComposite('/users/me/menu/partups', function(request, params) {
    const options = parseDefaultOptions(params.query);
    options.fields = {
        name: 1,
        network_id: 1,
        slug: 1,
        image: 1,
        // upper_data: [user._id] // For notifications
    }
    const user = Meteor.users.findOne({_id: request.user._id});
    const partupsToGet = options.ids ?
        JSON.parse(options.ids) :
        user.upperOf ?
        user.upperOf.concat(user.supporterOf || []) :
        user.supporterOf || [];

    const partupsCursor = Partups.guardedFind(this.userId, { $and: [{ _id: { $in: partupsToGet } }, { archived_at: { $exists: false } }] }, options);

    return {
        find: function() {
            return Meteor.users.find({_id: this.userId});
        },
        children: [{
            find: function(user) {
                return partupsCursor;
            }
        }, {
            find: function(user) {
                const imageIds = partupsCursor.map(function(partup) {
                    return partup.image;
                });
                return Images.find({_id: {$in: imageIds}}, {fields: {'copies.80x80': 1}});
            }
        }]
    };
});
```

Zoals je kan zien haal ik de partup cursors ietsje eerder op, zodat ik het resultaat daarvan kan gebruiken om alle images in 1 keer op te vragen

Kijk er even naar met wouter zou ik zeggen, ik denk dat hij je wel kan uitleggen waarom dit een iets betere practice is.
