### ISSUE TITLE
Stop being a partner shouldn't show after you stopped

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1135]
After you clicked: "Stop being a partner" in the dropdown behind the cog on a part-up you are partner in, the dropdown item should be gone.

<img width="1440" alt="screen shot 2017-06-26 at 21 59 14" src="https://user-images.githubusercontent.com/14044235/27557681-b629e280-5aba-11e7-919d-d741ebf2db19.png">

**Comment by nathan-lamb** [comment]
Hey people, I'd be keen to take this issue. This will be my first open source contribution if that's all good :)

**Comment by wouterd** [comment]
Go for it! :) Please let us know if you have any questions.
