### ISSUE TITLE
Websocket connection interuption

### ISSUE THREAD

**Issue by andreleon** [part-up/part-up#1140]
On partup production my connection keeps being interupted. I have seen this in chome on my macbook and on @jessedvrs 's macbook.

![large gif 382x552](https://user-images.githubusercontent.com/1391492/27784843-ec101060-5fdb-11e7-94a1-0e5e2302b503.gif)

**Comment by ralphboeije** [comment]
Yes, saw this yesterday evening as well. Strange thing is that on beta.part-up.com (which is on exactly the same stack) this issue doesn't occur. Let's deploy a new version asap @wouterd to see if that fixes things.

**Comment by wouterd** [comment]
This has to do with clients falling back to using XHRs over websockets. For that we need sticky sessions. 

Found something here: https://stackoverflow.com/questions/23808528/sockjs-xhr-requests-404ing-with-meteor-app-running-behind-passenger-nginx

Will reenable sticky sessions and check if that helps.

**Comment by ralphboeije** [comment]
idle connections were closed after 5 secs instead of 60, Wouter changed this
