### ISSUE TITLE
Tribe page: clicking the users avatar results in an error

### ISSUE THREAD

**Issue by bartwr** [part-up/part-up#1150]
On tribe page: clicking the avatar of a user results in an error.

This is what I expected:

1. I go to https://part-up.com/tribes/customer-co-creation (in a private tab)
2. I click on an avatar 
3. The profile page of this user appears

This is what actually happens:

1. I go to https://part-up.com/tribes/customer-co-creation (in a private tab)
2. I click on an avatar 
3. A few things happen:

- The URL changes to https://part-up.com/profile/:profileId
- The page scrolls to top
- In the JavaScript console there is an error:

```Exception from Tracker recompute function:
d021abb….js?meteor_js_resource=true:3 TypeError: Cannot read property 'map' of undefined
    at Object.chatIdWithCurrentUser (d021abb….js?meteor_js_resource=true:291)
    at d021abb….js?meteor_js_resource=true:95
    at Object.p.call (d021abb….js?meteor_js_resource=true:95)
    at d021abb….js?meteor_js_resource=true:291
    at f.View.<anonymous> (d021abb….js?meteor_js_resource=true:79)
    at d021abb….js?meteor_js_resource=true:79
    at Function.e._withTemplateInstanceFunc (d021abb….js?meteor_js_resource=true:79)
    at d021abb….js?meteor_js_resource=true:79
    at Object.f._withCurrentView (d021abb….js?meteor_js_resource=true:79)
    at n (d021abb….js?meteor_js_resource=true:79)
d021abb….js?meteor_js_resource=true:3 Exception from Tracker recompute function:
d021abb….js?meteor_js_resource=true:3 TypeError: Cannot read property 'map' of undefined
    at Object.chatIdWithCurrentUser (d021abb….js?meteor_js_resource=true:291)
    at d021abb….js?meteor_js_resource=true:95
    at Object.p.call (d021abb….js?meteor_js_resource=true:95)
    at d021abb….js?meteor_js_resource=true:291
    at f.View.<anonymous> (d021abb….js?meteor_js_resource=true:79)
    at d021abb….js?meteor_js_resource=true:79
    at Function.e._withTemplateInstanceFunc (d021abb….js?meteor_js_resource=true:79)
    at d021abb….js?meteor_js_resource=true:79
    at Object.f._withCurrentView (d021abb….js?meteor_js_resource=true:79)
    at n (d021abb….js?meteor_js_resource=true:79)
```

4. That's it. I don't see a profile page.

**Comment by ralphboeije** [comment]
NB: avatar of core team member is meant. NB2:this only holds true for tribe homepage. Test it in inprivate browser when you are already a member of this tribe or click the tribe header to get to the tribe homepage.

**Comment by AnnotatedJS** [comment]
Is still an issue? I tried to recreate the error but the results I got were according normal expectations.

**Comment by ralphboeije** [comment]
@AnnotatedJS yes, just tested the exact flow as described by @bartwr and it still happens, see screenshots. NB: Click on a user profile picture under the "Chat with one of our coreteammembers" section.

<img width="1680" alt="screen shot 2017-09-27 at 20 29 48" src="https://user-images.githubusercontent.com/14044235/30930685-b595b03c-a3c2-11e7-8d05-a426aadb6004.png">

<img width="1680" alt="screen shot 2017-09-27 at 20 29 09" src="https://user-images.githubusercontent.com/14044235/30930692-bc997a44-a3c2-11e7-9a9a-7de453ffc5b1.png">

**Comment by AnnotatedJS** [comment]
I have checked again using Forefox inPrivate and this is what I found:
If I am logged-in then I will see the profile (= normal expected behavior)
When I am NOT logged-in, I do get the error described by OP

**Comment by ralphboeije** [comment]
Log in was not part of the steps to reproduce, so your finding is consistent with those steps.

**Comment by AnnotatedJS** [comment]
You wrote, "Test it in inprivate browser when you are already a member of this tribe ... " and that suggested a login.
Btw, I've checked it with regular Firefox and Chrome (not inPrivate) and got the same error.
And once a user is in this error situation Part-up is not responding anymore in a meaningful way.

**Comment by ralphboeije** [comment]
check, updated the comment, was too vaguely written.
