### ISSUE TITLE
Change button in warning pop-up (no partner) to become partner

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1169]
As we now have the become partner feature in the part-ups, we need to change the call to action button on the warning pop-up when you try to create an activity to become partner. And the close to cancel. See current state below.

As a logged in user
And on a part-up in which I am not a partner
When I click the "new activity" button
Then I want to see a pop-up explaining me that I need to be a partner to add contributions to an activity
And on this pop-up I see a button to become partner

When I click the button to become a partner on this pop-up (existing feature)
Then I see the "become partner" pop-up (existing feature)
And I can apply to become partner with or without contribution (existing feature)

<img width="1440" alt="screen shot 2017-07-17 at 14 15 23" src="https://user-images.githubusercontent.com/14044235/28267469-79eb4908-6afa-11e7-9a07-4ce7dd6b76e1.png">

**Comment by AnnotatedJS** [comment]
The current state (commit  [4683b24](https://github.com/part-up/part-up/commit/4683b2409b4b437ac226949186bca51694e0ff34) )of branch [fix-new-activity-join-partner-v2](https://github.com/part-up/part-up/tree/fix-new-activity-join-partner-v2) just tackles the logic/flow.

To finish this issue the wording of the messages need to be decided.
