### ISSUE TITLE
Chats and chatmessages have no indexes

### ISSUE THREAD

**Issue by wouterd** [part-up/part-up#1175]
Chat messages, chat and related documents with chat_ids in them have no indexes on those fields. This makes for slow queries that have to do table scans.

I created an index on production on Chatmessage: "chat_id" : 1 and "created_at" : -1 and that dropped queries to grab chat messages from a chat from 34ms to 0ms per query. That's a lot of CPU saved.

There's more indexes missing that should be added using ensureIndex in the Collection code.

**Comment by ralphboeije** [comment]
closed in #1188
