### ISSUE TITLE
Login error FB login: "email already exists"

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1177]
To reproduce:
- Create new FB account (or use one not used before to create a Part-up account)
- Create a new Part-up account with this fb account
- Log out of Part-up
- Open inPrivate browser and log in to Part-up with this FB account
- See that the following error message is shown

<img width="1440" alt="screen shot 2017-07-24 at 14 11 12" src="https://user-images.githubusercontent.com/14044235/28522855-ff301290-7079-11e7-8fb5-505c36b84c06.png">

**Comment by andreleon** [comment]
@ralphboeije I cannot reproduce this issue on a development environment or a production environment.
We have created several new facebook accounts and tried the steps you provided without any errors. We even registered with the email-adresses with wich the facebook accounts were registered and could not reproduce the `login-error_email-already-exists`.

**Comment by ralphboeije** [comment]
That's weird, I'll send you two test accounts in the part-up chat that produce this behavior consistently and that I created specifically for testing this issue that was also reported by a couple of users.
