### ISSUE TITLE
Disable the profile url of inactive users

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1180]
Admins can deactivate users in the admin panel. However, their profile remains visible. This should not be the case. How can we make this happen?

Issues:
- Google still indexes the profile
- Profile URL still returns profile page

**Comment by ralphboeije** [comment]
@andreleon when you think of a solution here, also take into account that there will be a demand from privacy law perspective in the near future that users should be able to set the visibility of their profile:
- public: search engines and visitors/not logged in users
- private: other part-up users only

**Comment by andreleon** [comment]
@ralphboeije at the same spot where I check for the `deactivatedAt` flag, we can implement the private profile logic.
