### ISSUE TITLE
Network invite: slug of undefined

### ISSUE THREAD

**Issue by noelheesen** [part-up/part-up#1194]
When you open the notification to grant a user access to the tribe the tribe settings modal pops up, this modal gives an error.

**Comment by andreleon** [comment]
I have tested it several times without any error.

with user 1
1. go to tribe you don't have access to
2. request access

with user 2(admin of tribe)
1. receive notification
2. click on notification
3. see no error

**Comment by noelheesen** [comment]
@andreleon I cannot reproduce this anymore, I guess it got fixed with another commit. I take this as a lesson to be more clear and upload screens for reference.
