### ISSUE TITLE
Validating input fields

### ISSUE THREAD

**Issue by noelheesen** [part-up/part-up#1227]
In some input fields it's possible to pass html, like the profile phone number and description.
The description get's `sanitized` and displayed as html.

![htmldescription](https://user-images.githubusercontent.com/18031130/29559443-6c7a5d8a-872f-11e7-9654-91cc1ad2ae75.png)

In the schema for registration no validation is performed, the sanitation is done when rendering?
![registerschemadescription](https://user-images.githubusercontent.com/18031130/29564490-4e59abf4-8742-11e7-9774-69defa79394c.png)

It's also possible to enter html in the phone input field, this also has no validation in the schema. The phone number doesn't get displayed at all so there are no risks. Do we have to sanitize this before displaying in order to prevent an XSS attack?

![profilephonenumber](https://user-images.githubusercontent.com/18031130/29559448-70266668-872f-11e7-9c21-652c8dcbcfca.png)

I found 2 places where checking for html is done in the Schema. These are the messages at the `inviteupper.js` and `networkbulkinvite.js`.

Why have you chosen for schema validation instead of sanitizing in these cases? Which systems are in place to prevent faulty input when we decide to show the phone number for example?

This could happen in other input fields as well, not tested any further yet.

**Comment by andreleon** [comment]
For clarification:

if you se a html string anywhere it means it is not rendered as html but as plain text. like so:
![profilephonenumber](https://user-images.githubusercontent.com/18031130/29559448-70266668-872f-11e7-9c21-652c8dcbcfca.png)

Only when this html tag is invisible, renders something out of the ordinary, or when it triggers some javascript, then it means there is "html rendering"
