### ISSUE TITLE
FB and LI login don't work on www.part-up.com

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1229]
I have set these URL's correctly in the developer sites of FB and LI I believe, but it won't work. What I also notice that the local storage of the www.part-up.com site is different from the part-up.com site, so you are not logged in automatically.

**Comment by wouterd** [comment]
AFAIK www.part-up.com always redirects to part-up.com, right? So we don't need support for stuff on www.part-up.com. Or am I understanding you wrong?

**Comment by ralphboeije** [comment]
It doesn't seem to redirect correctly then, as the www is kept in the url @wouterd
 
<img width="1440" alt="screen shot 2017-08-28 at 09 44 57" src="https://user-images.githubusercontent.com/14044235/29763942-8ae97a1c-8bd5-11e7-81c7-65d08db0ccfc.png">

**Comment by wouterd** [comment]
Made a DNS change that should fix this eventually. It'll take a while to propagate. All www.part-up.com requests should be redirected to part-up.com.

**Comment by ralphboeije** [comment]
check, tested and works now
