### ISSUE TITLE
Autofocus to activity modal input form

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1249]
Realy anoying that you need to click on this input field, as it is the only form field, so has to be clicked always.

**Comment by plant99** [comment]
Hi, can I work on it?

**Comment by ralphboeije** [comment]
Hi @plant99, yes I would be more than happy to accept your contribution on this issue. Please read https://github.com/part-up/part-up/blob/master/CONTRIBUTING.md to understand our working proces and conventions. If you have any questions, you will find the way to contact the team in this description as well. Issue related questions you can post on here of course.
