### ISSUE TITLE
Tribe stats are not updated anymore

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1256]
The stats object of the tribes are not all correctly updated. Issue: there is a difference between the number of tribe members listed on discover vs on the tribe homepage. See screenshots.

<img width="1440" alt="screen shot 2017-09-15 at 11 57 44" src="https://user-images.githubusercontent.com/14044235/30477436-70ef567c-9a0d-11e7-8da5-fc6de02bf93f.png">
<img width="1440" alt="screen shot 2017-09-15 at 11 57 53" src="https://user-images.githubusercontent.com/14044235/30477437-70f151c0-9a0d-11e7-82e5-e3fb720aa53c.png">

**Comment by jplattel** [comment]
For some tribes this seems to be updated, for others it is not... Came to our attention trough the dashboard that I've build. Multiple tribes flatline, others are still calculated daily...
