### ISSUE TITLE
Add restriction levels to html sanitizing

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1290]
Check PR #1257 and add restriction levels:

- Standard: sanitize everything
- Markup: sanitizing scripting
 - post (markdown)
 - comment (markdown)
 - content block tribe homepage and tribe about page (wysiwyg)
- URL only
 - chat messages (1-on-1 and tribe chat)

**Comment by noelheesen** [comment]
@ralphboeije It it still necessary to exclude html from the character limit?

**Comment by ralphboeije** [comment]
@noelheesen The exclude was created by Leon in #1282 and is necessary yes
