### ISSUE TITLE
Enable profile pop-up on part-up tiles for not logged-in users

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1293]
In #1286 we re-enabled the profile pop-up. In acceptance testing we found that it does not work for logged in users.

**Comment by jplattel** [comment]
On what page does this happen? Discover-page seems & the partups in tribe-page seems to be working on: https://master.staging.part-up.com/

**Comment by ralphboeije** [comment]
Not if you are a not logged in user
