### ISSUE TITLE
Activities still appear on the board after deleting (striked through)

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1305]
To reproduce: 
- Go to master.staging.part-up.com and log in with admin@example.com // user
- Start a part-up in a tribe (tested with board view) and copy activities from an existing part-up
- Go to the activities tab and click on an activity
- Click "edit" (on hoover) and then "remove"
- See that the activity is striked through (intended result)
- Go back to all activities
- See that the deleted activity is striked through (unintended result, see screenshot)

Expected result: deleted activities are not visible anymore on the activities tab (list and board view), only visible on the activity update itself (see all updates).

<img width="1680" alt="screen shot 2017-10-05 at 16 25 31" src="https://user-images.githubusercontent.com/14044235/31232466-3b12c222-a9ea-11e7-85bc-6c2a7928dd20.png">

**Comment by AnnotatedJS** [comment]
Does this mean this issue can be closed?

**Comment by ralphboeije** [comment]
yes, @jplattel forgot to add closes: #1305 to his PR message
