### ISSUE TITLE
On FF on Mac creating a new lane in board view doesn't work

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1312]
Tested on Mac + FF:
- Go to a part-up in which you are partner
- Go to activities tab with board view
- Try to add a lane (click + on right column/lane with dotted line)
- Add the lane title
- See that the input field is gone and no lane is added

Maybe related to #1160 ??

**Comment by AnnotatedJS** [comment]
Tested on Windows and FF

It works. 

I can't help you with specific Mac issues

![3 part up fast lane](https://user-images.githubusercontent.com/11474975/31407827-a1fe5fb2-ae06-11e7-87a3-9a0784e46847.png)

**Comment by ralphboeije** [comment]
@AnnotatedJS very annoying those differences between OS's, indeed.
