### ISSUE TITLE
Collapse/expand not working on profile page coming from a direct link

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1313]
in #814 this issue was fixed, but probably not in this edge case?

e.g. https://part-up.com/profile/Mv92iiTMNZ7jtgbQE

**Comment by AnnotatedJS** [comment]
Maybe not related to direct link but to the position of the last characters of user profile text (in your example 'Zagreb'). When it is more or less completely to the right side of its text block, than the 'show less' text overlaps with the user profile text.
If one makes the window, starting from maximum size, smaller, you will see several occasions where this phenomenon happens.

**Comment by andreleon** [comment]
@ralphboeije When I go to your url (https://part-up.com/profile/Mv92iiTMNZ7jtgbQE) it works for me, can you still reproduce it? 🤔
