### ISSUE TITLE
When hover over part-up partner pictures all pop-ups show the same profile

### ISSUE THREAD

**Issue by AnnotatedJS** [part-up/part-up#1314]
While exploring issue #1293 I noticed that (not being logged in) on a tribe page all pop-ups of part-up partners showed the same profile when I hovered above them. 
See screenshot below.
I could not find a logical explanation for the first round profile shown. (Meaning, why Ilan Siebert in this example?)
However, when I clicked on Lea Reisner's picture I was redirected to the top of the tribe page. When I scrolled down and hovered again over the partner pictures all pop-ups showed Lea's profile.

![part up koln spricht](https://user-images.githubusercontent.com/11474975/31352472-34ef2c26-ad2f-11e7-83f5-7b8864e86473.png)

**Comment by AnnotatedJS** [comment]
When logged in I saw my own profile while hovering over partner pictures.

**Comment by ralphboeije** [comment]
This is very strange indeed. In #829 it was fixed, but somehow the issue is back
