### ISSUE TITLE
Give tribe partners more information to accept/decline pending membership request

### ISSUE THREAD

**Issue by AnnotatedJS** [part-up/part-up#1317]
Currently a tribe partner has not that much information when he has to decide about a request of a person to become a partner. There is more information available in part-up but not presented to the deciding partner at the moment of decision.
See screenshot for some suggestions.
![part up snappy part up](https://user-images.githubusercontent.com/11474975/31411107-e1a3c2b0-ae10-11e7-9172-b7f8dcf62866.png)

**Comment by ralphboeije** [comment]
@AnnotatedJS the inviter motivation is shared as a comment when it is provided. Invites are also shown as updates, so you can already know who invited someone. Moreover, the flow not always starts with an invite, so the inviter motivation is not relevant. The only real relevant information is the motivation of the user that proposes to become member.  PS: the link to the profile is already there in the hover on the image of the user on the timeline.

**Comment by AnnotatedJS** [comment]
My wrong, based my conclusions on an incomplete test set.
