### ISSUE TITLE
Remove  "involved in" email notification for own comments

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#132]
In 1.16.0 new "involved in" comment notifications are introduced. Very neat. But there is one email notification to many. To reproduce:
1. check in profile settings if email notifications for "involved in" are enabled (green)
2. post comment to conversation you are already involved in
3. check your mail for a notification email.

**Comment by prik** [comment]
After checking it on production, I can't reproduce it. I can remember it being fixed in the past so I guess you can close this one.
