### ISSUE TITLE
English language settings of some users with NL IP adres are not saved

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#134]
To reproduce:
1. Log in as admin@part-up.com
2. Go to part-up.com/admin
3. search e.g. for user Rob Schilperoort (YjpZNoZukqgiYDfEw)
4. Log in as this user
5. Click user menu and next "Instellingen"
6. Set language under "Algemeen" to English
7. See that language changed to English
8. Close browser window
9. Retake step 1 through 4
10. See that language is set to dutch

**Comment by andreleon** [comment]
I tried the steps, this is not an issue anymore
