### ISSUE TITLE
Render part-up update types

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1342]
As a logged in user
And I am on the personal homepage
When I am on the conversations tab
Then I see all possible update types in the existing conversations filter:

- Add Message updates (should this include changed, NO, only if there are new comments on these updates, but not on the change, archive or delete events)
- Add activity updates (should this included changed, archived, deleted? NO, only if there are new comments on these updates, but not on the change, archive or delete events)
- Contribution updates
- Invite updates
- Membership updates (became supporter, stopped supporting, became partner, proposed to become partner, stopped as partner)
- Part-up settings updates (title, description, tags, date, location, image)
- Add update for commented on (update xyz)

edit, found the following updates:

- partups_created
- partups_message_added
- partups_messages_inserted?
- partups_supporters_added
- partups_uppers_added
- partups_ratings_changed
- partups_activities_comments_added
- partups_contributions_proposed
- update_partups_unarchived
- update_tags_removed
- update_tags_changed
- update_tags_added
- update_partups_partner_request
- update_partups_name_changed
- update_partups_message_added
- update_partups_location_changed
- update_partups_invited
- update_partups_image_changed
- update_partups_end_date_changed
- update_partups_description_changed
- update_partups_budget_changed
- update_partups_archived

**Comment by jplattel** [comment]
These are the ones I found (33):

- partups_location_changed
- system_supporters_removed
- partups_supporters_added
- partups_activities_comments_added
- partups_archived
- partups_contributions_accepted
- partups_message_added
- partups_uppers_added
- partups_created
- partups_tags_added
- partups_activities_archived
- partups_tags_removed
- partups_end_date_changed
- partups_description_changed
- partups_activities_added
- partups_invited
- partups_activities_unarchived
- partups_ratings_inserted
- partups_activities_removed
- partups_contributions_removed
- partups_contributions_proposed
- partups_name_changed
- partups_budget_changed
- partups_contributions_added
- partups_tags_changed
- partups_activities_changed
- partups_unarchived
- partups_image_changed
- partups_partner_rejected
- partups_ratings_changed
- partups_contributions_comments_added
- partups_partner_request
- partups_contributions_changed

**Comment by ralphboeije** [comment]
@noelheesen check if you have a complete view from the phraseapp keys
