### ISSUE TITLE
Change mouse pointer to selector type when able to drag a lane on the board view

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1352]
If you hoover over a card your mouse pointer is showing a drag/drop type of selector instead of the hand or arrow. This should also be the case when you are on a position to drag a lane.

**Comment by jamesbarrett95** [comment]
Hi Ralph,

Could you clarify what exactly you mean and where the problem resides?

Cheers.

**Comment by ralphboeije** [comment]
HI @jamesbarrett95 it resides on the activities tab of any part-up, e.g. https://master.staging.part-up.com/partups/part-up-developement-board-vGaxNojSerdizDPjd/activities (log in with admin@example.com and pw: user)

There you see the lanes that partners in the part-up can edit and move when the click and drag the header of a lane. The mouse pointer shows a hand when you do that, and it should be a 4-sided arrow, like it is when you click and drag a card to another position in the lane or to another lane.

**Comment by etisdew** [comment]
I think I have fixed this with [PR #1397](https://github.com/part-up/part-up/pull/1397)

**Comment by etisdew** [comment]
I have tested this in FFdev but am confident in the caniuse status of the change, and the effect is that you gain the positive effect that was suggested without losing the context of knowing you are able to single click the header for renaming. I feel this is an elegant and simple solution without any risk to merge, however I am not familiar with your framework and would request that you confirm the location of the change for yourself. Nice, to meet you guys and the project looks great. :) I'm Jeff.

**Comment by ralphboeije** [comment]
@jplattel, as discussed last friday, could you have a look at this PR?

**Comment by jplattel** [comment]
Welcome @etisdew! Thank you for you contribution, we're almost there, somehow the dragging a lane functionality didn't work for me on Firefox and Chrome, so I couldn't test is. @ralphboeije do you want the drag icon on just the header or the entire body of the lane?

**Comment by jplattel** [comment]
As discussed on the phone with @ralphboeije I can confirm we want the entire lane to be draggable, so this is fixed with your pull request @etisdew , it will be merged shortly! 👍
