### ISSUE TITLE
Change email address in user id doc when external service email address is updated

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#136]
As a linkedin login user, I want to be allowed to change my emailaddress on linkedin and still use linkedin to login to my existing partup profile.

**Comment by peterpeerdeman** [comment]
Can we split up this bug in two separate issues? I'd suggest:

- As a linkedin login user, I want to be allowed to change my emailaddress on linkedin and still use linkedin to login to my existing partup profile.

- As an upper I want to be able to change my email address manually on my profile settings.

(the second issue has larger impact on security / emailverification / password resets etc)

**Comment by ralphboeije** [comment]
@peterpeerdeman could we do the second only in admin panel? that would be great.

**Comment by ralphboeije** [comment]
@peterpeerdeman is it possible to have two external services (FB and LI) connected to one user ID if the email addresses are the same?

**Comment by peterpeerdeman** [comment]
this is currently not possible. When we detect an account login attempt with the same emailaddress, we show a message "please use linkedin/facebook/emailandpassword to signin"

**Comment by AnnotatedJS** [comment]
Maybe this package is relevant? [splendido/meteor-accounts-meld](https://github.com/splendido/meteor-accounts-meld/)

**Comment by ralphboeije** [comment]
Not needed anymore, because we implement user editable email address to profile settings
