### ISSUE TITLE
Change copy Invited to activity update

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1393]
Currently, the invited to activity update holds the copy: "<user x> invited <user y> to this part-up" after a user has invited another user to contribute to an activity. This should be "<user x> invited <user y> to contribute to this activity" and show the activity in this update.

<img width="1680" alt="screen shot 2017-11-13 at 12 17 07" src="https://user-images.githubusercontent.com/14044235/32723133-a6d9a5ca-c86c-11e7-9e7b-17adc93ee612.png">

**Comment by noelheesen** [comment]
Complexity: 3
