### ISSUE TITLE
Update VWO script for new CRO platform

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1395]
Take the script from: https://vwo.com/knowledge/how-to-use-vwo-for-single-page-applications/

**Comment by ralphboeije** [comment]
@noelheesen can you make a PR for it to have it included in the activity redesign release?

**Comment by noelheesen** [comment]
@ralphboeije What's our account id? it's required for the script;

**Comment by ralphboeije** [comment]
only testable in production

**Comment by noelheesen** [comment]
The VWO script leaves an error in the console.

**Comment by noelheesen** [comment]
The console error has dissappeared. If I encouter it again I'll add a more detailed description in case it takes a while before I can get back to it.
