### ISSUE TITLE
Hidden part-ups not showing after search on discover

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#142]
To reproduce:
- create hidden part-up
- search for this part-up on discover
- see that it returns "1 part-up found" header, but doesn't display the part-up tile as expected (see screenshot below)

![schermafbeelding 2015-12-21 om 09 11 05](https://cloud.githubusercontent.com/assets/14044235/11926324/1c7d6148-a7c4-11e5-9deb-996a32a2f134.png)

**Comment by andreleon** [comment]
@ralphboeije Could you please re-test this issue on **acceptance**? I cannot reproduce this locally or on acceptance, thanks.

**Comment by ralphboeije** [comment]
This was fixed earlier by @bryantebeek I thought, but somehow the issue wasn't closed. Just retested, but in production this bug is not there anymore.
