### ISSUE TITLE
Account verification link has no result page

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#143]
To reproduce:
1. Sign up to Part-up at part-up.com/register
2. Check your email for a "Confirm email address" email from Part-up
3. Click the link in that email
4. See your browser open, but showing a blank page (see screenshot)

![schermafbeelding 2015-12-21 om 10 33 17](https://cloud.githubusercontent.com/assets/14044235/11927864/c26d2970-a7cf-11e5-8068-ee5f1e797e9e.png)

**Comment by jessedvrs** [comment]
Fixed :+1:

**Comment by ralphboeije** [comment]
Like!

**Comment by tlimpanont** [comment]
@peterpeerdeman can you pick this up, don't how to test this locally??
