### ISSUE TITLE
Add partners to upper profile

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#146]
As an upper I want to view/show the partners I worked with in part-ups on my upper profile, because it is part of my online reputation.

@LifelyPim can you add the design to this issue? I don't see it on redpen anymore.

**Comment by ralphboeije** [comment]
added this one to the invite modal milestone, since we already need the partner-list for the people relation information on the search results/upper card. This then requires the frontend of this list to be added to the upper profile.

**Comment by peterpeerdeman** [comment]
from the olden days: the last trace of the partners tab I could find https://redpen.io/fybd8d18cee43503c7
