### ISSUE TITLE
Allow to self-assign an activity on the add activity modal

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1461]
As a logged in user
When adding a new activity
Then I want to be able to self-assign the activity

Reason: it now takes two extra clicks (dropdown and dropdown item "I want to do this")

**Comment by noelheesen** [comment]
Complexity: 9

**Comment by ralphboeije** [comment]
@noelheesen last minor improvement: can you make the text: "I want to do this" clickable as well (to tick the box)
