### ISSUE TITLE
Acceptance test findings startpage

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1462]
- [x] media query missing on motivation block, lay-out messed up on mobile
- [x] Not logged in: missing onboarding tile
- [x] On click on Comment or x comments on starred update on startpage, you should be routed to update detail and not be able to comment inline as it is now.
- [x] Comments on starred updates should not be shown on the startpage
- [x] Media gallery does not autorun the carroussel of images/videos
- [x] Media gallery items are displayed below each other on first render and then "collapsed" into the carroussel (overflow: hidden needed)
- [x] You should be routed to startpage when: not logged in, or when: logged in but not partner/supporter of this part-up. Only partners should not be routed there. 

FEATURE
- [x] Files not rendered on starred updates
- [x] Move star icon to dropdown on all updates (same as on activity update)

BUG
- [x] Settings can't be saved after adding or removing files (tested on Chrome/Safari)
- [x] Can't create a new partup: 'create  your part-up' button doesn't seem to work.
- [x] You can select a non-image file format in the settings to upload to the carroussel. That will not upload however, leaving you with an endless spinner on the image upload button. We should limit the files available to pick to image files only (PNG, JPEG)
- [x] Add copy to toaster error message when trying to add the star to an update when there are already 5 updates starred (toaster is showing, but with empty content)

STYLING
- [x] Decrease size of loading spinner of react app to be the same as spinner in blaze part (or better, use custom part-up logo spinner)

Mobile:
- [x]  Become partner/supporter buttons overlap
- [x] Star icon overruns title on starred updates

![schermafbeelding 2017-12-29 om 14 46 29](https://user-images.githubusercontent.com/14044235/34438425-161e7bdc-eca7-11e7-865b-8da3d53a312b.png)

**Comment by jplattel** [comment]
Screenshot for the media query on mobile: 

![img_3538](https://user-images.githubusercontent.com/517775/34438554-f1e46848-eca7-11e7-8977-0945389b604a.PNG)

**Comment by jplattel** [comment]
Star icon overlaps on smaller screensizes:

![img_3539](https://user-images.githubusercontent.com/517775/34438564-05f653c8-eca8-11e7-9793-31236243440b.PNG)

**Comment by eriksoon** [comment]
When writing a motivation it says 0 characters left. I can still add more text however. Would be nice if I couldn't or if the text box turns red.

![image](https://user-images.githubusercontent.com/18055074/34439773-a1fac2ce-ecb0-11e7-8c82-92f17c7c6769.png)

**Comment by eriksoon** [comment]
Cant comment on a starred post from the part-up startpage (win10 / chrome)
![image](https://user-images.githubusercontent.com/18055074/34440016-957de8d0-ecb2-11e7-9af5-25ae5fd09119.png)

**Comment by eriksoon** [comment]
I think the ticker of the images is quite distracting (arrows are orange iso transparant and images are loading continuously)

![image](https://user-images.githubusercontent.com/18055074/34485933-6a569972-efcd-11e7-95e2-970a08db621a.png)

**Comment by noelheesen** [comment]
* The new partup profile image gallery moves away from an entry even when a video is being played;
* Flexboxes with text do not take the appropiate width on IE11
![ms-flex](https://user-images.githubusercontent.com/18031130/34605941-c462e384-f20d-11e7-9903-558445f5cb63.PNG)
* CSS is not applied properly for smaller screen sizes:
![ie11-small-screen-css](https://user-images.githubusercontent.com/18031130/34606880-54e7ff68-f211-11e7-9ea7-a54ae43fa3ee.PNG)

* Once, after a page refresh, localization got stuck in a loop switching from EN to NL constantly;
* When you click on 'x reacties' in the comments a button 'terug naar overzicht' appears, this will however not go back to the star tab but conversations instead.

**Comment by noelheesen** [comment]
* When I go to a [partup](http://ft-react-app-start-page.staging.part-up.com/partups/incubator-list-vGaxNojSerdizDPjc) the start text next to the star dissappears in the render process;

All the CSS issues are fixed now on IE11. The going back buttons we use for navigation when in a detail page are still thinking the user comes from one of the other tabs.

**Comment by ralphboeije** [comment]
@noelheesen removing the text next to the star is intentional for partners and supporters :-). The buttons I will first fix in copy. Later we can improve this by having different button.
