### ISSUE TITLE
Add search to part-up

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#147]
As an upper I want to be able to search my part-up's content, such that I can also find stuff that's been added some time ago.

@LifelyPim can you add the design to this issue, because I don't see it on Redpen anymore.

**Comment by erik-visser** [comment]
Think this is a big thing

**Comment by ralphboeije** [comment]
Agree, but we'll take this into account for the full redesign of the part-up page we are working on right now. We're in concepting phase right now.

**Comment by ralphboeije** [comment]
duplicate to #640
