### ISSUE TITLE
Staging test findings

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1480]
- [x] hoover state activity title white
- [x] After login still redirected to discover instead of home
- [x] "ToDo Empty state" showing when logged in as default user
- [x] Counter missing in part-ups dropdown
- [x] 4 console errors on loading home, one is triggered by the part-ups dropdown (which froze after a couple of tries, maybe related to this error)
- [x] After changing the partner/supporter filter in the dropdown, the part-ups dropdown is frozen (specific case: log in as admin, he has no supporter part-ups)
- [x] Placeholder text (write a comment) does not have the right font+size
- [x] New message/New activity buttons not hidden (or can they use the blaze modals now Rick has also used that method in the startpage react app)
- [x] Title of update does not link to update detail on the part-up page, which it should
- [x] Toaster message with login succes is not needed every time you go to the personal homepage
- [x] My activities not loading for Admin user
- [x] After logout, you are on an empty /home, should be routed to part-up.com/

**Comment by ralphboeije** [comment]
@andreleon I just found three minor issues when testing:
- [ ] You have to click "My activities" twice in the right column navigation before the tab is loaded
- [ ] In the My activities overview only activities of active (non-archived) part-ups should show
- [ ] On the My invitations, it lists all invitations I received in the past. We discussed that we should empty this list before the release and change the way the invite is stored, such that it will be more accurate (can't remember specifics of our conversations, though)

**Comment by andreleon** [comment]
@ralphboeije I don't recall having discussed we will empty the list. Also we would not be able to know which ones we should remove (based on what condition do we invalidate invites? it could cause problems with active users).

What I do recall is discussing the way we handle invites in the partup startpage sprint. e.g. user clicks an invite and is able to accept on the partup page. (wich I don't think is implemented yet 🤔)
