### ISSUE TITLE
Replace all hardcoded 'Starred update' related text

### ISSUE THREAD

**Issue by noelheesen** [part-up/part-up#1496]

**Comment by noelheesen** [comment]
Complexity: 2

**Comment by noelheesen** [comment]
@ralphboeije I can't find any hard-coded copies of `Star`, `Unstar` or `Starred Updates` anymore.

**Comment by ralphboeije** [comment]
@noelheesen See screenshot. Header of the Starred updates on the startpage should be translated as: " "Belangrijkste updates".

<img width="1680" alt="screen shot 2018-01-14 at 21 57 59" src="https://user-images.githubusercontent.com/14044235/34920646-19da4cca-f976-11e7-86e3-a62d32a42172.png">

**Comment by noelheesen** [comment]
I have already replaced that with a copy. For some reason it's not being translated properly.

**Comment by ralphboeije** [comment]
Strange, is the key correct. I see this in Phraseapp: pur-partup-start-starred-updates_title
