### ISSUE TITLE
Notification route to startpage and shouldn't

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1513]
- [x] Multiple updates: The notifications for "User x and x other(s) added updates" and "User x added several updates" now route to the startpage instead of the All updates tab
- [x] Activity invite updates now route to the startpage instead of the activity detail 
- [x] My Tribes menu: when supporter, you are routed to startpage instead of conversations timeline

**Comment by noelheesen** [comment]
Complexity: 4
EST: 30min - 2hrs

**Comment by noelheesen** [comment]
@ralphboeije We have discussed this so I feel stupid asking. Is it still desired that supporters no longer get redirected to `/start`? I can remember you saying a customer liked the start page (as supporter).

**Comment by ralphboeije** [comment]
@noelheesen never hesitate to ask twice!! Should have done that in the last release with the feature flag, remember!? Yes, that is the desired behavior. /start is not for parnters/supporters, unless they tick the box as in #1512

**Comment by ralphboeije** [comment]
@noelheesen found another one and don't know if fixed this one in this branch as well: notification of new part-up in production routes to conversations tab instead of start page
