### ISSUE TITLE
Markdown does not render numbered lists properly anymore

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1518]
To reproduce:
1. Add a numbered list to a new message on a part-up
2. post the message
3. see that the numbered list is rendered as bullet point list

**Comment by philippeehlert** [comment]
hey @ralphboeije I'm interested on trying to solve this, could you give me some guidance on which files I should look to?

**Comment by ralphboeije** [comment]
Hi @philippeehlert thanks for your kind interest. @noelheesen can you help Philippe out?

**Comment by noelheesen** [comment]
Yes, glad you want to help out @philippeehlert !

We use `marked` to handle markdown. You can find the implementation in `app/packages/partup-client-base/client/strings.js`

**Comment by noelheesen** [comment]
@philippeehlert It might just be a css issue, definitely worth checking before diving into js.

**Comment by philippeehlert** [comment]
@noelheesen @ralphboeije It was actually only a css issue, I've created the pull request here: https://github.com/part-up/part-up/pull/1519

not sure about how to link this issue with my pull request.

can you guys give me any feedback about the fix?

thanks!

**Comment by ralphboeije** [comment]
Thanks man! Small thing, but there will be some happy users: https://part-up.com/partups/co-creating-the-part-up-development-roadmap-WqfR2oqsDucsFfojH/updates/PsiKb45WxxSE8CJay

We mostly use the reference "closes: #<issueNumber)" in the PR message, but I don't know if "fixes" (that you used) also works well to reference the issue and close it automatically on merge to master, @noelheesen ?
