### ISSUE TITLE
Date is missing from Homepage conversations date-posted

### ISSUE THREAD

**Issue by brittanyryan** [part-up/part-up#1527]
For each entry of a conversation on the homepage, the date is missing the # of the day. 

Should be: Time, Day of week, Month, **Date of Month**, Year

<img width="385" alt="screen shot 2018-01-22 at 10 11 42" src="https://user-images.githubusercontent.com/29369630/35213101-c775445c-ff5c-11e7-81aa-2ba3125ec5a0.png">

**Comment by noelheesen** [comment]
Complexity: 2
EST: 30-45mins
