### ISSUE TITLE
"00" inserted at end of messages including @Mentions

### ISSUE THREAD

**Issue by brittanyryan** [part-up/part-up#1528]
On Homepage > Conversations - a message which includes an @Mention includes a "00" at the end. 

<img width="945" alt="screen shot 2018-01-22 at 10 16 40" src="https://user-images.githubusercontent.com/29369630/35213306-76e7d652-ff5d-11e7-9c80-26cf5e9d6af3.png">

**Comment by noelheesen** [comment]
Complexity: 6
EST: 1hr
