### ISSUE TITLE
Fix OneDrive error, see #1521

### ISSUE THREAD

**Issue by noelheesen** [part-up/part-up#1530]

**Comment by noelheesen** [comment]
I'm not yet able to reproduce this consistently. @ralphboeije Does this happen on a specific device? I sometimes get the error, which can lead to other errors. One time I had a Meteor error about an image which was also totally random. For now I have modified the source code to include extra checks to prevent errors. Until I can reproduce consistently it's hard to test what's going wrong in these cases. I have pushed a [branch](https://github.com/part-up/part-up/tree/fix-onedrive-picker) that catches the errors. I'll test more on staging, could you add the branch to the microsoft account?

**Comment by ralphboeije** [comment]
Really annoying these kind of bugs. the branch is on the ms account now

**Comment by noelheesen** [comment]
I have figured out how the dropbox implementation is done. I now serve a static file that won't load the whole SPA. I'm sorry that I didn't figure it our earlier but if this work's the implementation is rock solid. While the current implementation works, fixing things `later` is often never until there's a immediate demand to do so. @ralphboeije Could you add `http://localhost:3000/onedrive/oauth_receiver.html` to the redirect_uri's so I can test this? if it doesn't work I'll accept the current implementation.

**Comment by ralphboeije** [comment]
@noelheesen cool! and done
