### ISSUE TITLE
Improve tile on personal homepage conversations tab

### ISSUE THREAD

**Issue by jplattel** [part-up/part-up#1536]
To remove the tile background & border would result in a cleaner look. Without all the nesting. Another suggestion is to add: "Tribe: " to the tribe name or "Partup: " for the part-up, as it may not be clear about what we are talking about.

<img width="1125" alt="screen shot 2018-01-23 at 10 41 37" src="https://user-images.githubusercontent.com/517775/35271167-830b72a2-0031-11e8-964a-17eb641c9f7b.png">

AND

- [ ] Move the part-up title to the subtitle ("datestamp" + "in" + "partupName") and make the partupName orange, underlined and clickable

**Comment by noelheesen** [comment]
@ralphboeije Should I move the title to be a part of the subtitle as we discussed?

**Comment by ralphboeije** [comment]
@noelheesen Yes, see AND in the description above

**Comment by noelheesen** [comment]
Ah my bad
