### ISSUE TITLE
Topbar on home page for selecting Role

### ISSUE THREAD

**Issue by jplattel** [part-up/part-up#1537]
"updates of" should have a non-breaking space, or enough space to break properly.

<img width="1154" alt="screen shot 2018-01-23 at 11 48 18" src="https://user-images.githubusercontent.com/517775/35271733-55e5eb02-0033-11e8-92ff-a250adc8eb6b.png">

**Comment by ralphboeije** [comment]
Thanks for mentioning. The first will be fixed in the code, the second point is a copy thing, I will fix that by changing the logic of the sentence.

**Comment by noelheesen** [comment]
Closing this because I have already commented #1538

**Comment by ralphboeije** [comment]
Reopened, because we need to have a look at the logical sentence structure of these two filters
