### ISSUE TITLE
List Part-up as author of the onboarding message of a part-up

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1548]
Now the partupName is listed as the author in stead of "Part-up"

<img width="1091" alt="screen shot 2018-01-23 at 12 14 19" src="https://user-images.githubusercontent.com/14044235/35272911-0b0b53e8-0037-11e8-93a8-ff5da253c254.png">

**Comment by noelheesen** [comment]
Is this ok?

![pur-messagetitle](https://user-images.githubusercontent.com/18031130/35300498-dc4e57ec-0088-11e8-9578-a3fdff3e09b9.png)

**Comment by ralphboeije** [comment]
yup
