### ISSUE TITLE
Add trackingcode for Part-up GA account

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#160]
as discussed with Peter we need an extra tracking code on Part-up to be able to create historic data on our own GA account instead of only on the Lifely account. This is important to have full control over GA in the future.

Trackingcode of Part-up platform should be added. Note that the GA advisor told us to use a specific format for adding it to the code. Check the att (in Dutch).

[Meerdere sites meten in één dataweergave.pdf](https://github.com/part-up/part-up/files/77093/Meerdere.sites.meten.in.een.dataweergave.pdf)

**Comment by ralphboeije** [comment]
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55573564-4', 'auto');
  ga('send', 'pageview');

</script>

**Comment by jessedvrs** [comment]
In pull request #212 I added the trackingId "UA-55573564-4" as second tracker to the METEOR_SETTINGS production environment variables. The client will use that key to set up a second tracker.
