### ISSUE TITLE
Reduce home page image size

### ISSUE THREAD

**Issue by noelheesen** [part-up/part-up#1603]
The used image is larger than seen on screen. Cut off the image to the exact pixels seen on screen and compress it slightly for even more reduced size. This reduces the page load.

**Comment by Avasse** [comment]
Hello, i'd really appreciate to work on this issue as my first contribution, is anybody working on it ?

**Comment by christiandavidturner** [comment]
Hey! is this still open?

**Comment by ralphboeije** [comment]
Hi @christiandavidturner yes, it is still open. Had some more urgent issues to look into. But happy for any contributions on this one.
