### ISSUE TITLE
Profile menu / Chat support list item has no on-click event

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1605]
Expected result: open intercom
Steps to reproduce
1. Go to part-up.com and log in
2. Click profile image to open dropdown
3. Click on Chat support / Chat met ons in the dropdown
4. See that nothing happens

**Comment by lilliekhogg** [comment]
The <a> tag to the chat support does not have a valid link. It is simply a "#". Are you requiring an On-Click event to bring up a page using Javascript? Or simply a link to the chat page? 

Thanks

**Comment by jplattel** [comment]
Hi @lilliekhogg it's supposed to activate the Intercom window as far as I know, that's why it's `href` attribute is set to #
