### ISSUE TITLE
Upgrade FB API use for login

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1622]
https://developers.facebook.com/tools/api_versioning/361616407358764/

Upgrade to v2.12 needed

Upgradeherinnering voor v2.5 | Upgradeherinnering voor v2.5 |  
-- | -- | --
Upgradeherinnering voor v2.5
 
 
Your App, Part-up, is currently accessing Graph API v2.5 which will reach the end of its 2-year lifetime on 12 April, 2018. We estimate 1 endpoint that Part-up calls will be impacted by this change and may stop working after the automatic upgrade push. To ensure a smooth transition, please migrate all calls to Graph API v2.6 or higher. Use the API Upgrade Tool to understand exactly how this change will impact your app.Opmerking: If you do not see any impacted calls in the API Upgrade Tool, your app/code may not be affected by this upgrade.Visit our changelog to see the full list of changes in all Graph API versions. You can view this and other Developer Notifications related to your app, in the App Dashboard. | Your App, Part-up, is currently accessing Graph API v2.5 which will reach the end of its 2-year lifetime on 12 April, 2018. We estimate 1 endpoint that Part-up calls will be impacted by this change and may stop working after the automatic upgrade push. To ensure a smooth transition, please migrate all calls to Graph API v2.6 or higher. Use the API Upgrade Tool to understand exactly how this change will impact your app.Opmerking: If you do not see any impacted calls in the API Upgrade Tool, your app/code may not be affected by this upgrade.Visit our changelog to see the full list of changes in all Graph API versions. |   | You can view this and other Developer Notifications related to your app, in the App Dashboard.
Your App, Part-up, is currently accessing Graph API v2.5 which will reach the end of its 2-year lifetime on 12 April, 2018. We estimate 1 endpoint that Part-up calls will be impacted by this change and may stop working after the automatic upgrade push. To ensure a smooth transition, please migrate all calls to Graph API v2.6 or higher. Use the API Upgrade Tool to understand exactly how this change will impact your app.Opmerking: If you do not see any impacted calls in the API Upgrade Tool, your app/code may not be affected by this upgrade.Visit our changelog to see the full list of changes in all Graph API versions.

 
You can view this and other Developer Notifications related to your app, in the App Dashboard.

**Comment by jplattel** [comment]
What does: https://developers.facebook.com/tools/api_versioning/ say? Can you upgrade you endpoints from there?
