### ISSUE TITLE
Partner request update detail not loading when routed from a notification

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1627]
To reproduce:
- Log in with user Y
- Request to become partner in part-up X
- Log in with user Z that is already partner in part-up X
- See that this user has a notification of the partner request by user Y
- Click this notification
- See that you are routed to the update detail and that this update is not loaded
- See under All updates that the partner request does exist

**Comment by noelheesen** [comment]
I have tested this locally and the update loads fine for all users already a partner. This could also be because of the fixtures contain some faults. @ralphboeije Should I try to reproduce this one first or do the Intercom?

**Comment by noelheesen** [comment]
@ralphboeije I have been able to reproduce when user Y stops supporting a partup before a request to become a partner is either accepted or declined. Can you confirm this is the case in the scenario you tested as well?

**Comment by ralphboeije** [comment]
@noelheesen no this was not the case. Someone just asked to become partner and was still supporter. Have you testen on acceptance as well?
