### ISSUE TITLE
Edit pricing page to reflect new 2016 pricing policy

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#163]
The pricing strategy for 2016 is updated. Now we only have 3 categories to be shown on the website:
- Social impact: communities that steal our hearts can get a Part-up tribe for free, tribes: 1, support: chat, FREE
- Starter kit: for organizations and communities that want to create a flexible workforce, tribes 1-5, support: +telephone, 7500 per year (perhaps add: extra tribes at 2000 euro each)
- Enterprise: For large enterprises that want to become decentralized collaborative organizations, tribes: 25, support: +webinar, 25000 per year

Current design:
<img width="1440" alt="screen shot 2016-01-06 at 17 12 15" src="https://cloud.githubusercontent.com/assets/14044235/12147332/a80ba716-b498-11e5-8d70-0d081ac0b84d.png">

**Comment by ralphboeije** [comment]
@peterpeerdeman had Pim deze al met je besproken?

**Comment by peterpeerdeman** [comment]
yes, ik hij staat op de backlog om maandag met de high prio bugs samen op
te pakken

On Thu, Feb 4, 2016 at 11:34 AM, Ralph Boeije <notifications@github.com>
wrote:

> @peterpeerdeman <https://github.com/peterpeerdeman> had Pim deze al met
> je besproken?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/part-up/part-up/issues/163#issuecomment-179761725>.
>



-- 
http://www.peterpeerdeman.nl
<http://www.peterpeerdeman.nl/?utm_source=Mail_Signature&utm_campaign=Gmail&utm_medium=email>

<https://twitter.com/peterpeerdeman>
<https://www.linkedin.com/in/peterpeerdeman>
<https://www.flickr.com/photos/peterpeerdeman/>
<https://www.facebook.com/peterpeerdeman>

**Comment by andreleon** [comment]
Created a pull request fixing this issue
