### ISSUE TITLE
Delete profile button on profile settings

### ISSUE THREAD

**Issue by jplattel** [part-up/part-up#1636]
To comply with the GDPR we need a button on the profile settings page that lets you delete an account

The button should have the following actions:

- [x] Reset profile to a blank anonymous account (including Name to `Deleted User` and remove email)
- [x] Deleted flag on profile i.e. can't view a deleted profile.
- [x] Revoke current API access for all applications on the API
- [x] Profile images uit S3 verwijderen
- [x] Stop recommending the deleted users to other users

Results in: 

- Not in search results (for chats, invites etc)
- Profile not listed in tribes & partups
- Profile not accessible (in a better way, now flickers with content)
- Reference to the user should be anonymized.
- Query all updates to remove user name from updates & comments

**Comment by ralphboeije** [comment]
Next action: discuss this with @wouterd before starting to work on it

**Comment by jplattel** [comment]
Running into the issue that I cannot delete a user when that user is a only tribe admin... Archiving a tribe doesn't help with this as each Tribe needs at least one admin. @ralphboeije , any ideas on how to solve this?

**Comment by jplattel** [comment]
Spliced of the removal of older profile images to: https://github.com/part-up/part-up/issues/1656 bit of scope loss if we do that in this issue.

**Comment by ralphboeije** [comment]
@jplattel let's change the tribe admin of those tribes to the Part-up admin account

**Comment by jplattel** [comment]
@wouterd I've made a filter for the UBCF algorithm in that repo to filter out all the deleted users, is that sufficient enough? 

The updated changes to the deleted profile should propagate through the API you build, but as I see that isn't the case currently, maybe we can add: 

```java
(e.deletedAt match {
  case Some(time) =>
    setProps(user,
      "deletedAt" -> time.format(neoDateFormatter),
      "deleted" -> true,
      "active" -> false
    )
  case None => Seq()
}) ++
```

**Comment by jplattel** [comment]
The User-API is not enabled yet on production, so we can skip this
