### ISSUE TITLE
Fix participation score

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1644]
The participation score is not reflecting the activity of the user anymore. Somehow it is not recalculated anymore.

It should be based on
25% - number of logins in the last month
25% - supporter in active part-ups
25% - average contribution rating
25% - number of contributions in active part-ups

The contribution rating part should be removed/replaced by number of new updates created in last month

**Comment by noelheesen** [comment]
The contribution part takes up 50% of the overall rating, should the amount of updates created also count for 50%?

**Comment by noelheesen** [comment]
Updates not related to activities should make up for the other 25%.
