### ISSUE TITLE
Private tribe message showing falsely 

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#165]
To reproduce (in IE11)
1. Become member of a private tribe (e.g. https://part-up.com/kwadraad-vakmanschap)
2. Open user menu
3. Click the tribe mentioned in 1.
4. See the private tribe message showing (see screenshot).

![ie 11 access control error](https://cloud.githubusercontent.com/assets/14044235/12247191/2cf81fcc-b8b3-11e5-919a-3c780b72cdaa.png)

**Comment by jessedvrs** [comment]
(Un)fortunately I did not manage to reproduce this in IE11. See screenshot.

<img width="1023" alt="screen shot 2016-01-21 at 15 59 03" src="https://cloud.githubusercontent.com/assets/5961598/12483933/f14534c2-c057-11e5-9c11-8dd2d64e0aa1.png">

**Comment by ralphboeije** [comment]
That's a pity. Couldn't be a historic thing? This tribe was created months ago (when we also still had the general issue with access to private tribes. Or is that impossible?

**Comment by jessedvrs** [comment]
Can't say for sure. Let's keep our eyes open ;)
