### ISSUE TITLE
Remove gender, age, and friends from FB profile data

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1655]
Because of the GDPR proportionality principle, we need to remove several items from the FB profile data API request.

Next to that, FB requires us to do an App review, see below.

------------
App Review required by 1 augustus 2018 to retain existing permissions and features  The Facebook App Review process and API permissions model have been updated. Meer informatie.In order to maintain your current API access, your app will need to be submitted for review by 1 augustus 2018. If your app is not submitted for review, you will lose access to these permissions and features.

- user_link
- user_gender
- user_age_range
- user_friends

The Facebook Platform APIs have been updated with these changes. Please review the Veelgestelde vragen to ensure you request the correct permissions and features with your app review submission.If access to the permissions and features is approved, the app may need to be associated to a verified business to complete App Review.

**Comment by jplattel** [comment]
@noelheesen , want to look into this today? We already had a look and the meteor internals might make this pretty hard... :(

**Comment by ralphboeije** [comment]
Checked with @jplattel and @noelheesen We don't need to do a submission, as we don't use the data from these permissions in Part-up. We still need to write a migration to remove the data that is currently in our database.

**Comment by jplattel** [comment]
Maybe we can also remove phone & skype data that is currently in the database
