### ISSUE TITLE
Improve landing page of closed part-ups

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1658]
Issue: invited users to closed part-ups land on the landing page of closed part-ups when they are not logged in / registered. On this page they are not prompted in a clear way to log in or register before they can visit the part-up. See screenshot below

<img width="1680" alt="screen shot 2018-05-15 at 15 59 18" src="https://user-images.githubusercontent.com/14044235/40061515-624ce494-5859-11e8-92f6-7905c0f67c18.png">

Needed: 
- [x] change paragraph text to (NL) De partners in deze part-up kiezen ervoor de part-up besloten te houden. Ben je al Part-up gebruiker? Log dan in om toegang te krijgen. Ben je uitgenodigd en heb je nog geen Part-up profiel. Klik dan op "Gratis aanmelden". Na het aanmelden kom je dan automatisch bij deze part-up terug. (EN) The partners in this part-up decided to make this a non-public part-up. Are you a Part-up user? Log in to access the part-up. Did you receive an invite and don't you have a Part-up profile yet? Click "Register for free". After registering you are automatically redirected to this part-up.
- [x] Add log in and register for free buttons right below the paragraph text (instead of the "Take me back to discover" link

**Comment by noelheesen** [comment]
Hi AlexErling, yes it is. If you need any help feel free to @mention me.

**Comment by ralphboeije** [comment]
Hi @AlexErling I can edit the texts in Phraseapp, our translation management tool. The buttons are the main thing here.
