### ISSUE TITLE
Styling issues

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1663]
- Hrefs are not orange anymore
- Overlay page (e.g. settings pages): hoover state of "close" link is white and therefore almost invisible. should be black
- increase white space between paragraphs 
- List items in activities have wrong font size

**Comment by MadhavBahlMD** [comment]
@ralphboeije I can help, can you tell exactly where these issues are happening?

**Comment by ralphboeije** [comment]
HI @MadhavBahlMD any help is appreciated! I think @noelheesen can point to the code in the repo. I can share the links were you can see the issues:
- close link on overlay page: e.g. invite overlay - https://acceptance.part-up.com/partups/nog-een-test-part-up-2CPr3CPihgpMFMmag/invite
- paragraphs in messages: https://acceptance.part-up.com/partups/nog-een-test-part-up-2CPr3CPihgpMFMmag/conversations (click New message)
- list item in activity description - https://acceptance.part-up.com/partups/nog-een-test-part-up-2CPr3CPihgpMFMmag/updates/sXLBPs65CyX7kbTN3

**Comment by MadhavBahlMD** [comment]
Hey @ralphboeije 
I understood the overlay page issue, and the list item size issue, 
although, I couldn't find where the paragraphs are not being rendered as paragraphs (point 2), can you send a screenshot maybe for point 2?

**Comment by ralphboeije** [comment]
@MadhavBahlMD cool! see attached screenshot for the paragraph styling issue
<img width="1253" alt="screen shot 2018-06-06 at 11 30 56" src="https://user-images.githubusercontent.com/14044235/41029866-25a9899a-697d-11e8-82bf-9a983d607704.png">

**Comment by eyalmendel** [comment]
Hi guys,
I'd like to help in this one? Anything up-for-grabs?

**Comment by MadhavBahlMD** [comment]
Hey @ralphboeije 
There were errors while running npm install and npm start, 
![image](https://user-images.githubusercontent.com/26179770/41135746-abe43478-6af0-11e8-84c3-bf3aecc9db27.png)
Any idea why?

**Comment by ralphboeije** [comment]
@MadhavBahlMD I'm not a dev myself, just the product manager. @noelheesen can you help him out?

**Comment by ralphboeije** [comment]
@noelheesen this one is becoming annoying for users (especially the HRefs color), so could please give this prio?

**Comment by ralphboeije** [comment]
@noelheesen not in board view (see screenshot)

<img width="522" alt="screen shot 2018-06-28 at 16 41 08" src="https://user-images.githubusercontent.com/14044235/42041402-1e2499ae-7af2-11e8-92b5-336e303c8f50.png">
