### ISSUE TITLE
Issues with new acceptance release incl meteor upgrade

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1669]
- [x] Linkedin log in fails: toaster message says: "Internal server error"
- [x] Papertrail log error: NotificationModel is not a constuctor (see last screenshot). Appears a lot and might be the root cause of the issues below
- [x] Adding comment works, but gives toaster: "error-method_comment_could_not_be_inserted
- [x] Newly added activities not showing
- [x] Inviting a user gives an "Internal server error" toaster message
- [x] Adding a message first gives the "Internal server error toaster message" and next "post" button keeps the spinner and the pop-up won't close by itself. Message updated is created however. See the console errors in the first screenshot.
- [x] Google Drive Attachment not rendered on the message update (first it is rendered, but when you (manually) close the pop-up, it disappears. This one is clearly related to the pop-up being manually closed (previous item)
- [x] Creating a new part-up gives a "part-up could not be inserted" toaster and the create button has an endless spinner. However, the part-up is created just fine (you find out after manually closing the overlay). And on the created part-up the creator is not showing as partner, but not recognized as partner (you find out when you try to add an activity)
- [x] Unable to partner request toaster message showing after adding motivation and clicking share motivation (endless spinner). Partner request update is created, but user did not become supporter
- [ ] Issues with Websocket connection (3rd screenshot)

<img width="1438" alt="screen shot 2018-05-19 at 15 40 07" src="https://user-images.githubusercontent.com/14044235/40269188-ff603abe-5b7a-11e8-8b9b-c0257b563fc2.png">

And a bunch of other console errors/warnings:

<img width="1434" alt="screen shot 2018-05-19 at 15 33 54" src="https://user-images.githubusercontent.com/14044235/40269132-0e1819ec-5b7a-11e8-9feb-58b4fe279d28.png">

<img width="1444" alt="screen shot 2018-05-19 at 16 00 50" src="https://user-images.githubusercontent.com/14044235/40269358-e88cc714-5b7d-11e8-908b-661349aa9bb9.png">

<img width="1259" alt="screen shot 2018-05-19 at 16 09 00" src="https://user-images.githubusercontent.com/14044235/40269450-1d51f6c6-5b7f-11e8-8c62-b09d6d1a115f.png">

**Comment by noelheesen** [comment]
@ralphboeije What kind of invite gives the error message? 

I've found almost all items related to a bug in sending emails on which the whole process just stops, but that's an issue to look at another time. The websocket is out of my hands at the moment, it could very well be because of server errors.
