### ISSUE TITLE
Integrate Vyte.in as extra tab on part-up page

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#168]
As an upper I want to quickly propose and agree upon meetings with the partners (and supporters sometimes too). Vyte.in offers a neat way of picking dates in groups. 

Prototype this integration using their API

**Comment by ralphboeije** [comment]
Documentation is here: https://vyte.readme.io/v1.0/docs

**Comment by ralphboeije** [comment]
Hi @bartwr do you have the time and motivation to take your hackathon prototype to a production level?

**Comment by bartwr** [comment]
Somewhere in the near future I'd like to work on this. @ralphboeije

**Comment by saintmac** [comment]
Hi @bartwr, Martin from vyte here.
Let me know if you need help on this, I can't wait to see Vyte integrated on part-up

**Comment by ralphboeije** [comment]
Hi @bartwr can you give a timeframe for when you would like to work on this?

**Comment by bartwr** [comment]
@ralphboeije Not get, but will let you and others know when I stay planning / working (on) it.
