### ISSUE TITLE
Improve double opt-in in register flow

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1688]
after #1640 is fixed, we need to improve the register flow to prompt the user to opt in in order to receive notifications

several users report that they keep receiving the confirmation email (?even after confirming? check needed)

**Comment by noelheesen** [comment]
Als notifications niet worden verstuurd dan ook:
 - reset password niet;
 - 

Doornemen verify email notificatie.

Filter voor elke notificatie en alleen emai bij whitelisted.

Huidige mensen die nog geen verified email hebben.

eens per week reminder instead of notificatie als geen verified email.
