### ISSUE TITLE
Add dropdown to select activity on invite modal

### ISSUE THREAD

**Issue by partupadmin** [part-up/part-up#17]
As an upper I want to select an activity to which I invite other uppers or non-uppers on the part-up invite modal using a dropdown. And I want the uppers list to be specific for that activity (as it is on activity invite modal).

<img width="1440" alt="screen shot 2016-02-26 at 10 36 42" src="https://cloud.githubusercontent.com/assets/14044235/13348627/d83c8cee-dc74-11e5-9226-c2604a75c12c.png">

**Comment by peterpeerdeman** [comment]
can we close this one for now, @ralphboeije ?
