### ISSUE TITLE
Guarded find for users

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1735]
Needed for profile visibility, to set visibility of profiles of users by their preference. Check needed on:
- [x] invites
- [ ] tiles (part-up and networks)
- [ ] profile page
- [ ] hoover tiles
- [ ] part-ups (supporter/partner list)
- [x] personal chat search
- [ ] tribe chat members online

complexity: 100

**Comment by noelheesen** [comment]
@Tribes Public tribes only show users with public profiles.

**Comment by noelheesen** [comment]
- [ ] Invite to `tribe / partup / activites` does no longer show results;
- [ ] Chats can find private with relation but does not load the object to client;
- [ ] Chat doesn't load;
