### ISSUE TITLE
Font size of bullets in activity description too large

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1751]
see screenshot, bullet text should have the save size as paragraph text

<img width="483" alt="screen shot 2018-08-07 at 09 24 22" src="https://user-images.githubusercontent.com/14044235/43760906-bf03d4fc-9a23-11e8-9363-0758acebd033.png">

**Comment by ralphboeije** [comment]
Hi @twisted-sres, you're more than welcome! Happy to have you on as a contributor. Please read: https://github.com/part-up/part-up/blob/master/README.md and https://github.com/part-up/part-up/blob/master/CONTRIBUTING.md to get started!

**Comment by rcmaples** [comment]
Noticed this hadn't been completed yet, decided to pitch in. I believe I've gotten it squared away in PR #1795. Let me know if anything else is needed :)

**Comment by ralphboeije** [comment]
Cool, tnx @rcmaples @noelheesen can you check this?

**Comment by noelheesen** [comment]
Fixed in #1795
