### ISSUE TITLE
Add activity when hitting Return

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1757]
Now I think Return is set to Cancel instead of on Add Activity

**Comment by i-reborn** [comment]
Hey, I would like to work on this issue. 

This would be my first issue. Please let me know how to get started.

**Comment by ralphboeije** [comment]
Hi @i-reborn sorry for my delayed response. Thanks in advance for your contribution. To get started, just check out: https://github.com/part-up/part-up/blob/master/CONTRIBUTING.md and https://github.com/part-up/part-up/blob/master/README.md If you have any questions, you'll find the ways to contact the devs right there.
