### ISSUE TITLE
Edit of activities in board view not always storing updated content

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1785]

**Comment by ralphboeije** [comment]
@noelheesen we have to look at this together tomorrow

**Comment by ralphboeije** [comment]
@noelheesen in prod right now, the fix is not working. To reproduce:
- add date and description to existing activity and save
- edit activity and remove date, next save
- try to edit activity again and see that the change is not saved

Maybe this has to do with the duplicate that is stored?

**Comment by noelheesen** [comment]
I cannot reproduce this.

The papertrail error is not related to the PR and is around for a while now.

Let's discuss further today.
