### ISSUE TITLE
After search for a private part-up, it doesn't show the part-up tile

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#184]
To reproduce:
- create a private part-up
- search for this private part-up on discover
- see that it shows the number of results, but not the tile for this part-up (see screenshot)

<img width="1440" alt="screen shot 2016-01-19 at 11 42 53" src="https://cloud.githubusercontent.com/assets/14044235/12416435/cc9a5c5e-bea1-11e5-8f87-f78c33d6b798.png">

**Comment by jessedvrs** [comment]
The count is being requested separately from the actual part-up objects. This causes less reliable results since they're not necessarily in sync. I'm going to see if I can find the source of the difference in results.

**Comment by jessedvrs** [comment]
Created pull request :)

**Comment by ralphboeije** [comment]
like!
