### ISSUE TITLE
Tribe admin transfer

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#205]
Concerning this design: https://redpen.io/qf785371885c8ff3f8 including:
- having up to 10 admins (NB: perhaps already take into account that later this year we want to be able to make the admin role dependent on a reputation score within the tribe).

**Comment by eriksoon** [comment]
I' ve got a +1 for adding a second admin to the tribe. During holidays of the tribe admin new users can't become new members to a tribe at the moment.

**Comment by ralphboeije** [comment]
@eriksoon Adding a +1 is easy, just click the emoticon in the right top corner of this issue
