### ISSUE TITLE
Configure the email tracking in mailgun

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#211]
We really need to have this tracking up and running soon. There was a technical challenge with regard to the server and sender alias or something?

**Comment by ralphboeije** [comment]
@peterpeerdeman We need to have this tracking enabled, to be able to improve te emails. Can you put it on the sprint of next week?

**Comment by ralphboeije** [comment]
Added this one to the next sprint as it is a high prio to enable testig of improvements to the emails.

**Comment by peterpeerdeman** [comment]
email.mg.part-up.com CNAME record was added to DNS records and email tracking is now enabled on mailgun. In [b584b96465f0471897aae407f4bcc2b97fcaae22] tracking tags for mailgun have been added to allow separate analytics for each sent email
