### ISSUE TITLE
Desktop notifications for Part-up notifications

### ISSUE THREAD

**Issue by jurjendevries** [part-up/part-up#218]
Send notifications to the browser desktop notification system. Information at https://developer.mozilla.org/en-US/docs/Web/API/notification . Ps. its not only at desktops, last year some mobile browsers are supporting this too.

**Comment by ralphboeije** [comment]
Hi @jurjendevries thanks for your first issue. It is a good one. It is quite a big one I think to have it for all of the major browsers. Assigned it prio 1. This is the prio for me to assign budget to it. Anyone is free to add to work on this issue voluntarily of course.

**Comment by ralphboeije** [comment]
duplicate to #227
