### ISSUE TITLE
Visualize archived part-ups

### ISSUE THREAD

**Issue by partupadmin** [part-up/part-up#22]
As an upper I want to be able to view my archived part-ups on my profile page or tribe page and to see the difference with the active part-ups, such that I can still view "old" part-ups. The copy of the "verwijder/delete" action on the part-ups settings should be renamed to "archive/archiveer".

**Comment by ralphboeije** [comment]
See https://redpen.io/nbc067447b4cde8e5b for the design of the archived part-ups and the filter on the tribes page (should also be visible on profile page (tabs partner part-ups and supporter part-ups).

**Comment by ralphboeije** [comment]
- be able to archive in part-up/settings
- hide archived from discover
- tribe page filter on part-ups tab
- profile page tab partners and supporters filter
- archived tribe tile
- Archived part-up design or modal
- Notifications of archived state to supporters and partners

**Comment by ralphboeije** [comment]
We refined this epic into the set user stories and put them in the tribes improvement milestone.
