### ISSUE TITLE
Image upload in Edge not functioning

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#226]
When trying to upload an image on start/details the loader keeps spinning (same as we also had in safari and IE). https://github.com/part-up/part-up/issues/161

**Comment by andreleon** [comment]
@ralphboeije I've tested and re-tested this issue in the EDGE browser on Windows 10, on both pu-staging.lifely.nl and pu-acceptance.lifely.nl. I've also tried to reproduce this locally, also without any issues.

Maybe I've missed something, can you please try to provide steps to reproduce this issue? Maybe it's a specific image format, maybe it's something else. Without more information on this matter I won't be able to tackle this issue.

**Comment by andreleon** [comment]
I even had it working on part-up.com:
![screen shot 2016-02-08 at 12 05 41](https://cloud.githubusercontent.com/assets/1391492/12884110/6335fc9e-ce5c-11e5-96a4-6694d4a54c5b.png)

**Comment by ralphboeije** [comment]
The original issue was found on image upload in a message

**Comment by ralphboeije** [comment]
@andreleon Just retested it on Edge on Win10 and it doesn't work. Steps to reproduce: 
1. Log in to part-up.com
2. Go to a part-up
3. Click New message button
4. Add text
5. Click Add Photo button
6. See finder pop-up appear and select an image
7. See pop-up close and loader start spinning
8. Wait for a couple of minutes to check loader is still spinning (see screenshot)

Expected behaviour: loader spins for a couple of seconds and photo is added to message.

![schermafdruk 202016-02-09 2012 46 27](https://cloud.githubusercontent.com/assets/14044235/12915428/7539b3de-cf2b-11e5-83d7-5527d7b5536d.png)

PS: I did relate the issue at the start to #161 in which these steps are already outlined. Please check the full description of the issue before diving into it.

**Comment by andreleon** [comment]
I reproduced this issue in Chrome (48.0.2564.103) on mac. I changed the extension of a .JPEG to .PNG. This causes errors because the file format does not match the extension.

**Comment by andreleon** [comment]
I have also reproduced it on EDGE in windows 10

**Comment by andreleon** [comment]
Also, it seems I can only reproduce this on staging/acceptance/production, not locally. Another thing that's weird, it only fails on images where I changed the extension from .jpg to .png and then just in some cases.

**Comment by ralphboeije** [comment]
@andreleon You're looking in the wrong direction I believe (although the finding is interesting as a general improvement). First we need to find the right configuration for you, because on all of the 3 win10+edge configs I triaged this user finding it simply doesn't work. In production, you can't upload an image in a new message. Regardless of MIME types and file extensions. Loader keeps spinning. Here are some details and screens and details of my last triage I did today.

Let's discuss with @peterpeerdeman and @tlimpanont (because of his work on new document upload tomorrow and friday) before we put more effort in finding the root cause. Does anyone at the Lifely office have a native win10 laptop (no vm)? As a last resort I can bring my home laptop in later this week.

Windows 10 Version 1511 on x64-systems
Microsoft Edge 15.10586.0.00
Microsoft EdgeHTML 13.10586

Tested with several images, none work:
- Mime type PNG and file-extension .PNG
- Mime type JPG and file-extension .jpg

![image 3](https://cloud.githubusercontent.com/assets/14044235/12946993/97b17672-cff8-11e5-83d3-b3026dee5751.png)
![image 2](https://cloud.githubusercontent.com/assets/14044235/12946994/9cb83944-cff8-11e5-9b8e-b5fed998acfd.png)
![image 1](https://cloud.githubusercontent.com/assets/14044235/12946996/a25354e2-cff8-11e5-80db-bfaaf73b8299.png)
![image](https://cloud.githubusercontent.com/assets/14044235/12946998/a43a5152-cff8-11e5-818d-0367f2cf3d45.png)
