### ISSUE TITLE
Typing in comment field instead of motivation modal

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#228]
To reproduce:
1. Go to a part-up of which you are not a partner and click the activities tab
2. Click "I want to do this" on one of the activities
3. See the motivation modal appear
4. Type your motivation and click backspace
5. Type some more and see that you are not typing in the modal but in the comment field of the activity (see screenshot)

![screenshot 202016-01-27 20at 2014 19 13](https://cloud.githubusercontent.com/assets/14044235/12617552/71dbc288-c510-11e5-8457-0ecc87f193b1.png)

**Comment by tlimpanont** [comment]
@andreleon it seems that the admin user have problem with opening the modal. 

I test it with admin and part-up: crowd-funding-part-up-organiseren

![crowdfunding-activity-motivation-modal-broken](https://cloud.githubusercontent.com/assets/617876/12910400/c9a1c806-cf0a-11e5-91c3-3a6896704e18.png)
