### ISSUE TITLE
Image upload on Edge bug

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#229]
NB: the same issue has been seen and fixed on IE and Safari already #161

To reproduce (browser: Edge):
1. Log in to part-up.com
2. Go to a part-up, e.g. https://part-up.com/partups/crowdsourced-ttn-voor-arnhem-nijmegen-greater-100-gelderland-YH3jE536NXekXE46E
3. Click New message button
4. Add text
5. Click Add Photo button
6. See finder pop-up appear and select an image
7. See pop-up close and loader start spinning
8. Wait for a couple of minutes to check loader is still spinning

Expected behaviour: loader spins for a couple of seconds and photo is added to message.

**Comment by andreleon** [comment]
@peterpeerdeman why hasn't this been closed yet?
