### ISSUE TITLE
Find root cause for not setting language of a part-up

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#245]
Language code is not stored in the part-up document, Theuy discovered. We ran this: db.partups.find( { _id: 'KMsYeXbWXdZeXNug2' }).pretty() and we could not find this property on the document "language" : "nl”

**Comment by peterpeerdeman** [comment]
on production is see the language value, set to a default of english:

![screen shot 2016-02-12 at 13 41 41](https://cloud.githubusercontent.com/assets/685599/13007149/652016ea-d18e-11e5-89ba-b3a60183b84c.png)

the errors in the production logs say the daily limit has exceeded:

error: Error while detecting language: Error: failed [403] {  "error": {   "errors": [    {     "domain": "usageLimits",     "reason": "dailyLimitExceeded",     "message": "Daily Limit Exceeded"    }   ],   "code": 403,   "message": "Daily Limit Exceeded"  } }

I have asked @ralphboeije to recheck the billing info in the google cloud console, stackoverflow says this problem occurs when the billing account is not setup properly, the quotas in the translate api also show a max quota of 0 characters per day:

<img width="965" alt="screen shot 2016-02-12 at 14 08 17" src="https://cloud.githubusercontent.com/assets/685599/13007668/286a80ec-d192-11e5-8210-8f303de68461.png">

**Comment by peterpeerdeman** [comment]
ralph updated the billing information, the api is unlocked again and should work properly on production now.
