### ISSUE TITLE
Order the part-ups on the tribe and profile page by most active

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#250]
As a viewer of the tribe/part-ups tab and profile/partner and profile/supporter I want to see the part-ups ordered by the most active (like the result of that filter on discover already does)

**Comment by ralphboeije** [comment]
@prik Hard to acceptance test this one. Can you tell me what the definition of active is you used? Does it look at activity in the past 30 days for example?

**Comment by prik** [comment]
@ralphboeije: Correct. I used the same sort as on the discover page, which is the sort on popularity score.

**Comment by ralphboeije** [comment]
There will be no findings then. Perfect!
