### ISSUE TITLE
Show archived state on part-up page

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#253]
As a viewer I want to see clearly when a part-up is archived (al functionality should remain enabled though). A design is first needed so that's why I assigned it first to Pim.

![gearchiveerd](https://cloud.githubusercontent.com/assets/685599/13180285/156cb56e-d728-11e5-857a-4e46ce5d8359.png)
(note from pim: white icon will be added on the left side of the message)

**Comment by ralphboeije** [comment]
@LifelyPim I didn't get the message that you added the design, because you somehow managed to add it to my original comment instead of making a new comment. Now, I only saw it once it was already in acceptance. 

My findings: because the b&w picture actually looks pretty good, and the font size of the archive state text is really small, it is easily overlooked and the part-up is easily mistaken fro being active. My suggestions:
- Increase font size and maybe bold or capitalized
- Change copy: Archived part-up / Gearchiveerde part-up

**Comment by andreleon** [comment]
This issue is fixed, the copy can be changed in the phraseapp when it is merged into develop
