### ISSUE TITLE
Dynamic tags on tribe based on part-up tags

### ISSUE THREAD

**Issue by peterpeerdeman** [part-up/part-up#257]
As a partup user I want to see tags on the tribe that correspond to the most often used tags from the tribes partups. E.g. if a tribe has 2 part-ups with the tag "development", the "development" tag should be shown first, followed by the tribes own tags

## affected pages
- tribe tile on swarm page
- tribe detail page

**Comment by ralphboeije** [comment]
@peterpeerdeman This one is not yet implemented on acceptance I guess? Any particular reason for it?

**Comment by peterpeerdeman** [comment]
it is, actually. if you look on https://pu-acceptance.lifely.nl/tribes/development?show=true the first tag is "infrastructure" because the tag "infrastructure" is the only one that occurs on more than 1 partup (1 archived an 1 unarchived partup)

**Comment by ralphboeije** [comment]
Ah, check. So the initial tags are overwritten when based on the occurances (>2) of the tags in the part-ups?

**Comment by peterpeerdeman** [comment]
exactly. one of the big advantages of this method is that clicking the dynamic tags will much more often result in finding partups that contain that tag
