### ISSUE TITLE
__count__ uppers needed in subtitle swarm page

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#259]
The key swarm-content-uppers-subtitle now only has a fixed number in stead of showing a __count__ of the uppers in all of the tribes in this swarm.

**Comment by peterpeerdeman** [comment]
was fixed in dda37c9a015657b882f3ca225793a94bf5b797f0

**Comment by ralphboeije** [comment]
@peterpeerdeman I can see it working on the https://pu-acceptance.lifely.nl/swarms/partup, but what does it count? I would suggest to have the total number of unique uppers in the tribes that are part of the swarm.

**Comment by prik** [comment]
@ralphboeije I programmed the counter like requested at https://github.com/part-up/part-up/issues/193.

To demonstrate this, I collected all the upper IDs from all tribes in your example swarm, and counted the unique values: https://jsfiddle.net/jz1y5hzk/. The count matches the count on the swarm page, so it's all good ;)

**Comment by ralphboeije** [comment]
Hi @prik that one works perfectly, I know. But I mentioned the specific key (i18n language key: swarm-content-uppers-subtitle) where it shows 2116 instead of 56. See in screenshot below: "Vind jouw volgende team in onze community en word 1 van de 2116 uppers."

<img width="1440" alt="screen shot 2016-02-23 at 20 15 33" src="https://cloud.githubusercontent.com/assets/14044235/13263694/fcae7954-da6a-11e5-96dc-7bbe50c7c444.png">

**Comment by prik** [comment]
Oops, I misinterpreted that one @ralphboeije. 
The 2116 reflects the current number of uppers registered on Part-up. When we were planning this feature, the design showed that "you'll become 1 of the x Part-uppers", so we thought it would need to reflect the total count. I'll change it to the unique swarm upper count, if preferred.

**Comment by ralphboeije** [comment]
Hi @prik that would be great.

**Comment by ralphboeije** [comment]
Acceptance test result: Perfect now.

**Comment by ralphboeije** [comment]
@prik not really this issue, but you also did the backend of the counters on the swarm page right? Somehow they do not work on this swarm page: https://part-up.com/haagsemakers. I added the tribe with a part-up and 3 uppers in it. So I am curious as to why it doesn't calculate the count?

**Comment by prik** [comment]
Hi @ralphboeije, this is because I've set up a cron job that calculates the stats for all swarms every 3 hours. So the data is not real-time.

**Comment by ralphboeije** [comment]
Hi @prik I didn't knew the exact timing of the cron, but nonetheless, this seems like a bug then. This specific swarm was created on friday evening and the counts still show 0 (just rechecked). The other swarms work fine though, somehow this seems to be an edge case, but I can't figure out the edge (we already have all types of tribes in the swarms, sa private and public). Can you look into it?

**Comment by ralphboeije** [comment]
@prik did you have a look at the crons? for most pages it works fine, but not for https://part-up.com/haagsemakers and https://part-up.com/ftopia. Is there a threshold maybe?

**Comment by prik** [comment]
@ralphboeije yes I did, and I was hoping that it would work by now. I ran the stats cron on my local server with production data, so also including the haagsemakers swarm, and that worked just fine. So there is something else going on that I haven't figured out yet. I'll keep you updated!

**Comment by prik** [comment]
@ralphboeije check it out: https://part-up.com/haagsemakers :-)

**Comment by ralphboeije** [comment]
@prik nice! You found the bug it seems?! Great to have it working at all times.

**Comment by prik** [comment]
@ralphboeije yes. There was something wrong with a particular cronjob that caused this one not to work anymore.
