### ISSUE TITLE
Improve update copy

### ISSUE THREAD

**Issue by partupadmin** [part-up/part-up#26]
When adding a comment to a message, the update should read "<name commenter> commented on the message of <name author>" instead of "<name author> posted a message" (see att)

![schermafbeelding 2015-10-26 om 15 10 56](https://cloud.githubusercontent.com/assets/14921786/10731164/57480482-7bf4-11e5-8745-0523c985f6e8.png)

**Comment by ralphboeije** [comment]
fixed when we fixed this for the app
