### ISSUE TITLE
Read more not visible (reactivity issue perhaps?)

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#264]
To reproduce (chrome on mac os with retina display and scaled resolution):
1. Go to: https://pu-acceptance.lifely.nl/swarms/partup
2. See that the read more text is missing (see screenshot)
3. try to increase and decrease the size of the browser window and see it appear and disappear at a certain point.

PS: also on iOS and safari and chrome this read more text is gone.

<img width="1440" alt="screen shot 2016-02-23 at 08 44 55" src="https://cloud.githubusercontent.com/assets/14044235/13255360/2009f286-da46-11e5-9814-d284896224e8.png">

**Comment by andreleon** [comment]
The read more button is visible again on all screensizes/devices in commit 5d0ad2304a0ac749db3de3597fadea972b93107d

**Comment by ralphboeije** [comment]
Thanks @andreleon !
