### ISSUE TITLE
Swarm page quotes: bottom align quotes

### ISSUE THREAD

**Issue by peterpeerdeman** [part-up/part-up#266]
reproduce:
https://pu-acceptance.lifely.nl/pildo

expected result:
userpictures and user names are aligned horizontally

<img width="972" alt="screen shot 2016-02-25 at 13 42 58" src="https://cloud.githubusercontent.com/assets/685599/13319969/b5c3db86-dbc5-11e5-9040-cc0cfe0ca2b1.png">

**Comment by andreleon** [comment]
I aligned the users horizontally in commit c2ec4c144a6be7432837417a5d938dddb0d6103d

**Comment by ralphboeije** [comment]
Acceptance test result: no findings (better said: lots of awesomeness :-)
