### ISSUE TITLE
Add search criteria to invite emails

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#269]
Hi [name],

Ik zag op Part-up de part-up: partupName. Volgens mij zou jij goed in het team passen. Ik vond jou doordat ik zocht op **< TAG/ZOEKTERM/LOCATIE/PERSONALITY >** en dit leek bij jou te passen.

**Comment by prik** [comment]
@ralphboeije what kind of copy do you want when a user is found by suggestion (the first uppers you get to see on the invite page)? 
Something like "Ik vond jou doordat je werd gesuggereerd als beste match."?
Or don't show an extra sentence in this scenario?

By the way, for the English version I have:
I found you based on the search query "{{ searchQuery }}" and it looks like this matches well with you.

Feel free to correct :)

**Comment by ralphboeije** [comment]
Hi @prik didn't know we were working on this one already. I'll ask Erik for the copy for this one.

**Comment by eriksoon** [comment]
@prik Nice, I would say: Ik vond jou, doordat je werd voorgesteld als beste match.

And it would be nice if we could always have two reasons to invite someone (if possible). Like: ik vond jou doordat ik zocht op ... en jouw persoonlijke kracht XXX past denk ik goed bij het team.

Although the last part might not be entirely true, I'd think it will give a bigger incentive to go and see if you would like to join. The personal strength can be matched based on the phase of the part-up.

**Comment by eriksoon** [comment]
Would be nice if you could add a personal reply adres. We often get mails replied to the system account. Or, even better, like Mailchimp be able to have your own mailadres displayed in the inbox of the receiver! That will definitely help in increasing the response rate.

**Comment by partupadmin** [comment]
@eriksoon there is no model for matching on personal strength. I am in favor of the second line though, but it should be just a personality trigger without a model behind it. For @prik to be able to use it, you should specify exactly the content of the whole email. Could you have another look and propose a full updated invite email?
