### ISSUE TITLE
Add more metadata to part-up tile

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#277]
The current part-up tiles hold quite some meta data already (tags, title, photo, partners, # supporters, # activities, tribe, completion). There are four more pieces of information really important to add:

1. Public or private
2. Type of part-up (revenue sharing, volunteer, commercial, in organization)
3. In a tribe is not visible enough (or should we just hide the part-ups in private tribes from discover)
4. Maybe (not sure yet) also the phase of the part-up

**Comment by ralphboeije** [comment]
similar to #86

**Comment by Timboliu** [comment]
I see this issue is a prio 1. I would like to give the public - private meta-data a +1
