### ISSUE TITLE
Add editable email address to upper profile settings

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#285]
As an upper I want to be able to change my email address on which I receive my notification emails on my profile settings.

NB: new verification required
NB2: how will this effect login+ww?

**Comment by peterpeerdeman** [comment]
we'd have to create an email management page where users can add an email address, see the verification status allow them to make a newly added email "primary" after it has been verified.  

NB: we can use the existing email verification functionality.
NB2: after adding an email, both emails can be used to login with email+password

please note that currently we do not do anything with the verified field yet, but it makes sense to start ensuring verification from this point on with new functionality (e.g., you can only change your email address to a verified address)

**Comment by ralphboeije** [comment]
Sounds like a plan and totally agree with you on the last point. NB we should first fix #136

**Comment by prik** [comment]
Backend is done, waiting for frontend implementation.

**Comment by andreleon** [comment]
Frontend is done

**Comment by ralphboeije** [comment]
Cool, @peterpeerdeman do you know if I can test the email verification in an acceptance release?
