### ISSUE TITLE
Archiving tribes from admin panel

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#287]
As an admin I can now delete a tribe, but this doesn't work if there was a part-up in it. We should change this delete action to a archive function. On click this should:
- give a warning of the number of active part-ups and ask to archive these part-ups first
- give a warning of the number of uppers still in the tribe and ask for confirmation to archive the tribe
- give archive state to tribe document in mongodb
- Show tribe archived message (right lower corner, green system message) on admin 

And also:
- exclude the tribe from several lists (my first thoughts: user menu, discover filter for public tribes)
- Show archived state as a different 404 on the tribe startpage (because you can still visit the tribe from the archived part-up link) without the option to close the startpage, but with a button to return to the part-up you came from.

**Comment by ralphboeije** [comment]
Maybe use this to a general improvement of the admin panel? https://almsaeedstudio.com/

**Comment by AnnotatedJS** [comment]
@ralphboeije, In answering your question, the following:
Before we focus on possible software solutions like almsaeedstudio is it relevant to do some speccing regarding the admin panel?
If that's the case then maybe we could create a part-up in the developers tribe?

**Comment by ralphboeije** [comment]
Hi @AnnotatedJS this was just for concepting and is definitely in the wrong issue. Sorry for that. Concepting the next level admin panel is a good idea though, but does not have priority yet. Let's first focus on the real issue described here, which actually does have prio 1.
