### ISSUE TITLE
Add extension filter to upload photo button

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#289]
When an upper uploads an image using the upload photo button on a message, it should filter all extensions except for: ['.gif', '.jpg', '.jpeg', '.png'], such that they cannot be selected in the Finder/Explorer view.

**Comment by tlimpanont** [comment]
add new accept attr in newmessage.html?
```
<input type="file" class="pu-fileinput" multiple data-photo-input accept="image/jpg,image/png,image/jpeg,image/gif" >
```

**Comment by tlimpanont** [comment]
resolved https://github.com/part-up/part-up/commit/31e1c6abfd0ea04284a0a1b00f486a0afe9d97cc
