### ISSUE TITLE
New tribe without part-ups shows popular part-up loader indefinitely

### ISSUE THREAD

**Issue by peterpeerdeman** [part-up/part-up#292]
Steps to reproduce

- Creating a new empty tribe
- Load tribe page, click start

result
- loader keeps spinning because there are no popular partups in the tribe yet.

expected result
- whole partup section is not shown

**Comment by andreleon** [comment]
The fallback is placeholder text

**Comment by andreleon** [comment]
Instead of a loader it now shows tribe partups and if there are no partups it shows fallback text (no active partups yet)
