### ISSUE TITLE
Add About page to tribe settings

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#298]
Concerning these designs: https://redpen.io/sbf0c9e874b043acf0 and https://redpen.io/evba5d4d63299d3292

NB: reuse upload media button with Dropbox/GDrive upload that Theuy has developed for part-up updates message.

**Comment by ralphboeije** [comment]
@andreleon acceptance test finding: on first view of the about page in settings, you can only add a paragraph and not the title and description. You can only do so after you added a first paragraph, which is kind of strange. See this design: https://redpen.io/sbf0c9e874b043acf0 and the current situation in acceptance below.

<img width="1440" alt="screen shot 2016-05-13 at 11 49 49" src="https://cloud.githubusercontent.com/assets/14044235/15244473/a375f328-1901-11e6-8923-d63cd278c142.png">

**Comment by ralphboeije** [comment]
Acceptance test result on mobile (tested iOS 9.3.2, safari and chrome): The WYSIWYG editor in the tribe settings/about page tab requires a double tap to activate. Singele tap on title of content block activates the input field, but for the editor requires two, which is not consistent. 

Next to that, the move up/down arrow don't work on this mobile setup, and also not on Win10+Edge (on win10+chrome it does work properly) and on mac+FF

**Comment by andreleon** [comment]
The sorting issue for mobile is fixed in commit 464f4863eb25ff1dfd1b6e37dfdef5412405d903
