### ISSUE TITLE
Add about tab to tribe page

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#299]
Concerning this design: https://redpen.io/gt6058c61e6ed76443

**Comment by ralphboeije** [comment]
Admins on about page are not alinged properly: see https://pu-acceptance.lifely.nl/tribes/development/about below

**Comment by ralphboeije** [comment]
This is fixed I see. No merge listed here though?

**Comment by ralphboeije** [comment]
@andreleon acceptance test result: lists not rendered correctly if list item takes more than one line. (see screenshot or https://pu-acceptance.lifely.nl/tribes/development/about

<img width="1440" alt="screen shot 2016-05-16 at 23 38 00" src="https://cloud.githubusercontent.com/assets/14044235/15304779/901b67f2-1bbf-11e6-8bae-1c14baa0a4ec.png">

**Comment by ralphboeije** [comment]
Acceptance test result on mobile (tested iOS 9.3.2, safari and chrome): The WYSIWYG editor in the tribe settings/about page tab requires a double tap to activate. Singele tap on title of content block activates the input field, but for the editor requires two, which is not consistent. 

Next to that, the move up/down arrow don't work on this setup.

**Comment by ralphboeije** [comment]
Next to that you, if you check [this about tab](https://pu-acceptance.lifely.nl/tribes/development/about), you see that the screenshot image is not rendered properly, even though it is a 2880 × 1800px 1,2MB PNG. Might it have something to do with #308 ?

**Comment by andreleon** [comment]
@ralphboeije I have changed this to te biggest size "1200x520". This is the max size used on part-up, if you want it any bigger maybe we should consider another image size for upload. Also I have altered the "max size: 400px" hint to "max size: 1200px x 520px". Maybe this will help users to upload the right size images.

As for the rotated portrait image, I will look into it

**Comment by andreleon** [comment]
@ralphboeije the issue with the rotated image has to do with the overall uploader we use in part-up, it's not directly related to this issue
