### ISSUE TITLE
Add search feature on tribe part-ups

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#300]
Part-ups tab on tribe page. This is the design: https://redpen.io/nbc067447b4cde8e5b

**Comment by ralphboeije** [comment]
Acceptance test finding: search doesn't include part-up description. On the Uppers tab it does and it should also do so on the part-ups tab.

**Comment by andreleon** [comment]
In my test it does include the description.

![screen shot 2016-05-12 at 13 52 41](https://cloud.githubusercontent.com/assets/1391492/15213641/d9ee5b34-1848-11e6-8c49-bcd50781d1c0.png)

**Comment by andreleon** [comment]
@ralphboeije It even works with spaces

![screen shot 2016-05-12 at 13 56 19](https://cloud.githubusercontent.com/assets/1391492/15213743/55cb4d16-1849-11e6-8929-a34c4574e4f1.png)

**Comment by ralphboeije** [comment]
Check, was too quick on this one. However, the thing I did notice, is it doesn't use fuzzy search like on the invite modal. E.g. type "infra" on https://pu-acceptance.lifely.nl/tribes/development?show=false in the search and you won't get a result. Only when you type "infrastructure" you find the "Platform development Q1 2016" part-up. If you type a part of a word on the invite modal, e.g. https://pu-acceptance.lifely.nl/tribes/development/invite you will get results. So the real finding here is: why wasn't fuzzy search implemented like on the invite modal?

**Comment by ralphboeije** [comment]
@peterpeerdeman this one is still open on the new acceptance env I think? Any reason why your team didn't use the fuzzy search like on the new invite modals?

Just discovered a rare edge case with low prio: cursor is visible in small search icon. To reproduce
1. type anything that leads to results: e.g. "platform" on https://pu-acceptance.lifely.nl/tribes/development?show=false
2. Delete the content in the search field and see the search bar remain maximized (which is good)
3. Navigate to another tab on your browser
4. Return to the Part-up tab on you browser
5. See that the cursor is visible in the small search icon

**Comment by peterpeerdeman** [comment]
fixed the backend issue (deploying to acceptance shortly), moving minor issue to separate lower prio issue
