### ISSUE TITLE
Improve scrolling behavior on part-up page in Chrome

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#307]
When scrolling down a part-up page in chrome, first the right column scrolls and only after you hit the bottom of the right column, the left also scrolls. In safari this is way smoother. And also, when you write a comment to chrome and it reaches the end of the screen, it doesn't scroll down, so you can't view the comment you are typing.

**Comment by andreleon** [comment]
@ralphboeije is this in a specific partup or with specific conditions?? When I scroll in a part-up, both columns scroll at the same time.

**Comment by ralphboeije** [comment]
@andreleon no, it is a general issue. Have you tried testing in production? Because I think local is too fast on lazy load to reproduce (tnx to @wouterd). To reproduce: before lazy load is triggered right column scrolls first. After lazy load is triggered, the scrolling behavior is fine again.

**Comment by ralphboeije** [comment]
Let's see if this one is fixed by moving the footer to the menu

**Comment by andreleon** [comment]
@ralphboeije Is it fixed? I am having issues reproducing this issue

**Comment by andreleon** [comment]
I tweaked the part-up page margins a bit to compensate for the comment box, this and the fact that the footer is gone should fix the issue
