### ISSUE TITLE
Add Heap Analytics to Part-up

### ISSUE THREAD

**Issue by andyhoek** [part-up/part-up#310]
To load Heap this code needs to be added to the head section of the HTML:

```
<script type="text/javascript">
      window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var n=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(n?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var o=document.getElementsByTagName("script")[0];o.parentNode.insertBefore(a,o);for(var r=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["clearEventProperties","identify","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=r(p[c])};
      heap.load("32736613");
</script>
```

To identify signed-in users this code needs to be added to the end of the body part of the HTML, please replace the value USERID with the unique user id of the signed in user:

```
<script type="text/javascript">
heap.identify({handle: USERID});
</script>

```

It would be great if the heap.identify is only loaded when a user is logged in.

Heap Analytics documentation can be found here: [https://heapanalytics.com/docs/](https://heapanalytics.com/docs/)

**Comment by wouterd** [comment]
Legal POV: if we start doing things like this (and on the blog), we should implement a proper cookie opt-in. Else we're breaking the law.

**Comment by ralphboeije** [comment]
Agree with you, Wouter. Will create an issue for it.

**Comment by wouterd** [comment]
From the Heap privacy policy:

```
Some browsers are configured with a "Do Not Track" header. Heap, like all major analytics products, is configured to ignore this header except for those customers that specifically request that they comply with "Do Not Track." We've chosen to defer the decision to conform to "Do Not Track" to our customers, instead of making that decision for them.
```

I wonder what the lawyer thinks of this. I'm not sure if this part made it into the cookie legislation, about do not track headers.

**Comment by ralphboeije** [comment]
I've asked him on part-up and mentioned you.

**Comment by andyhoek** [comment]
Any news from the lawyer?

**Comment by tlimpanont** [comment]
@andyhoek  Do you have account for heap so I can check the HEAP features more in detail?

**Comment by tlimpanont** [comment]
@andyhoek  I've installed the heap code in our partup.com staging env. Please check  http://staging.part-up.com/ (feat-heap-analytics). This heap code is based on the *.partup.com domain right?

**Comment by andyhoek** [comment]
@tlimpanont I can see the data flowing in, I've sent you an invitation for access to Heap.

**Comment by andreleon** [comment]
I am having issues with loging in on my local environment, also on acceptance

![screen shot 2016-09-02 at 15 10 19](https://cloud.githubusercontent.com/assets/1391492/18204879/68e0b2b8-711f-11e6-9be3-0a0f9d0fcd4c.png)

**Comment by tlimpanont** [comment]
heap is removed from source code according to https://github.com/part-up/part-up/issues/651

**Comment by tlimpanont** [comment]
recently deployed to acc https://ci.part-up.com/job/partup-deployment/358/ so the bug should be gone now

**Comment by tlimpanont** [comment]
@andreleon can you rebase develop to your fix branch please?

**Comment by andreleon** [comment]
@tlimpanont thanks, I will
