### ISSUE TITLE
Pre-acceptance test

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#314]
1. Duplicate search results - e.g. search for "algorith" and find Maurits 3 times
2. Search for a name - e.g. search for "Robin" doesn't lead to a right ordering (maybe related to 1, because this search string also gives duplicate results. But it is still strange that Josje will show up first when searching for Robin, but we might better fix that with the relevance algorithm
3. Cut introduction text to max the two most relevant lines (wrt search string), to save space for tags as presented in the design: https://redpen.io/df5c5d4e4a7170b544
4. Content match is not clear. When there is no match, every tag is bold. This should be grayed out. If there is a match, the matching tags is bold and the rest grayed out. That is good, but you don't see all the tags if, so it is better to also reorder the tags and show the matching tags always first.
5. Tags move below the invite button - if you have to cut them off, don't show them at all
6. Empty search result notification needed - e.g. search for "blabla" and see empty search results. Add copy: "no uppers found"
7. You can't add two search strings by placing a space between them - e.g. "design" reveals Pim as nr 1. "design web" doesn't show him at all, although he has both "design" and "web" as tags
8. Copy change needed for introduction and email invite introduction
9. Check with Erik on copy change of email

**Comment by ralphboeije** [comment]
@andreleon Point 3 is still not right. See screenshot. I search for a string that I know is outside the couple of lines of the description you show. It should then only show the part of the description that holds the matched string with that string highlighted and put ... before and after the part of the description shown. Please check the design mentioned above

<img width="1440" alt="screen shot 2016-04-04 at 22 13 38" src="https://cloud.githubusercontent.com/assets/14044235/14261847/e29918b8-fab2-11e5-8c97-6340b4da3c92.png">

**Comment by ralphboeije** [comment]
@andreleon Point 4 is also not correctly fixed. See screenshot. If I search for the string "graph" it returns Jasmijn as number 

<img width="1440" alt="screen shot 2016-04-04 at 22 18 24" src="https://cloud.githubusercontent.com/assets/14044235/14261916/3c5245be-fab3-11e5-9769-b8f16839187c.png">

**Comment by andreleon** [comment]
@ralphboeije point 3 and 4 have been fixed in the latest commit in develop

**Comment by andreleon** [comment]
I did another fix on develop where the tags would not highlight when a user doesn't have a description

fixed in commit 2c31c27c0122979e4f790a7343d24377bae5b30e
