### ISSUE TITLE
The page title should include information of what part-up, message it's part of

### ISSUE THREAD

**Issue by vvorski** [part-up/part-up#315]
The page title should include reference to part-up it's part of and the message, otherwise it's impossible to find anything within one's browser history:

<img width="490" alt="screen shot 2016-03-24 at 13 22 40" src="https://cloud.githubusercontent.com/assets/1789426/14018148/f4def328-f1c3-11e5-92e7-7f89be881f5d.png">

**Comment by ralphboeije** [comment]
True and [a PR is waiting](https://github.com/part-up/part-up/pull/181) for it, but that is not yet finished. So anyone is invited to take this to production level.

**Comment by ralphboeije** [comment]
fixed in latest release
