### ISSUE TITLE
cannot input global or online for part-up location

### ISSUE THREAD

**Issue by vvorski** [part-up/part-up#316]
Much collaboration is virtual only these days.

<img width="615" alt="screen shot 2016-03-24 at 13 38 15" src="https://cloud.githubusercontent.com/assets/1789426/14018504/0ce42478-f1c6-11e5-9352-6bbdccd8eb88.png">

**Comment by ralphboeije** [comment]
tnx @vvorski was a known issue, but has had low priority until so far.

**Comment by ralphboeije** [comment]
related to #383

**Comment by ralphboeije** [comment]
duplicate to #383
