### ISSUE TITLE
Add markdown support to messages and comments

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#321]
As an upper I want to be able to use "enter" to create a "< br >" in a message and a comment and want to be able to use a - to start a "< li >"

NB: spaces added, because GH supports html

**Comment by ralphboeije** [comment]
Will you be demoing this issue tomorrow?

**Comment by tlimpanont** [comment]
jupp well do

**Comment by tlimpanont** [comment]
@ralphboeije couple things to add

1. Markdown does not support multiple breaks ENTER + ENTER + ENTER + ...... will leave you with single break
2. Right now chat not have Markdown rendering support
3. Markdown icon will be placed at the bottom of the input where Markdown is implemented.
4. Single line input fields will not be Markdown supported (has to do with styling i.e. commenting on messages)

<img width="621" alt="screen shot 2016-08-21 at 20 27 48" src="https://cloud.githubusercontent.com/assets/617876/17839093/060d1428-67de-11e6-988e-981796ccb8e0.png">


6. Markdown supported: Message on Part-up activity, Description section of activity input 

<img width="760" alt="screen shot 2016-08-21 at 20 27 35" src="https://cloud.githubusercontent.com/assets/617876/17839084/e0cff7fc-67dd-11e6-98cd-02dbb63eabdd.png">

<img width="797" alt="screen shot 2016-08-21 at 20 27 09" src="https://cloud.githubusercontent.com/assets/617876/17839089/f0685358-67dd-11e6-811e-edd198c06201.png">

**Comment by ralphboeije** [comment]
Thanks for this update. Let's release this later this week.

**Comment by tlimpanont** [comment]
![screen shot 2016-08-22 at 21 22 24](https://cloud.githubusercontent.com/assets/617876/17868369/e95ccf2c-68ae-11e6-837e-95fdc5a0ac12.png)
![screen shot 2016-08-22 at 21 22 12](https://cloud.githubusercontent.com/assets/617876/17868370/e985bd10-68ae-11e6-8513-05a348a7edca.png)

**Comment by tlimpanont** [comment]
test

test







test

**Comment by bkht** [comment]
Hoi Theuy,

ik heb mijn github username iets korter gemaakt:
https://github.com/bkht
GitKraken heeft een probleem met te lange repository URLs.

Mvg,
Jack.
