### ISSUE TITLE
Create Mongo clone for data team to query

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#322]
Joost has the need to query the db, but is not fond of using production database. The data team therefore needs a clone of the db with preferably an hourly update (at least daily). Maybe not as a first step, but if easily done, access control should be in place to allow access to specific collections.

**Comment by AnnotatedJS** [comment]
What will the data team do with this production database clone?

**Comment by jplattel** [comment]
@AnnotatedJS I'd rather query a clone instead of the production database for running some experiments on datasets. This reduces risk and we can have this clone with separate permissions for the data-tribe. 

As for the usage, I'd like to implement in a dashboard that makes it easy to run tests, queries and experiements to have Partup become more data-driven :)

**Comment by AnnotatedJS** [comment]
Okay, if that is the case the requirements for the 'clone production database' solution has to be extended with a feature to anonymize the content in a way that the structure of the content remains more or less the same but that it will not be possible to relate the content to real clients of part-up.

Especially, given the separate (ie. less stringent) permissions for the data-tribe.

**Comment by jplattel** [comment]
Anonymization of the data in a way is certainly a good idea. Names and contact-details aren't required for running experiments.

**Comment by vanderGoes** [comment]
Yeah, it is great that I can access that again. We were brainstorming about an automated solution. A database copy just for analysis purposes. But @wouterd suggested that this can maybe also be resolved with read-only rights on the production MongoDB.

Most of all is it part of a bigger plan that also should include an agreement that protects the property and privacy. To create the opportunity for more selected data analysts to crunch the part-up data to understand our users and support operations.
