### ISSUE TITLE
Add recommended part-ups in overlay on discover page

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#323]
Related to #95 for which @jplattel will create a Pull Request shortly.

The header of the discover page (see arrow in screenshot below) has to be improved to make explicit that the recommended part-ups are just a few of the total number of part-ups. To this end the header should read the following if the sorted by filter is set to Recommended:
- Discover x recommended part-ups (out of x) // Discover x aanbevolen part-ups (uit x)

![discover recommended filter](https://cloud.githubusercontent.com/assets/14044235/14120514/6b189390-f5f3-11e5-9aef-6a389a993a4a.png)

**Comment by AnnotatedJS** [comment]
This issue is put on hold, because it's related to the design result (i.e new specifications) of [issue 324](https://github.com/part-up/part-up/issues/324).

**Comment by ralphboeije** [comment]
UX't this with @LifelyPim and our idea is to create an overlay for this that shows only the 4 top recommended for you with possibly an explanation of the why of the recommendation (what data do we have on this @vanderGoes ?? Design will follow shortly

**Comment by ralphboeije** [comment]
Button needed on discover and notification to get to this overlay.

**Comment by vanderGoes** [comment]
Currently we can't show the explanation. I suggest to keep this first version simple. But definitely include it as an feature for the 2nd or 3rd generation recommendation engine.

**Comment by ralphboeije** [comment]
ok, cool. Regarding the notification. Can we tell if there are new part-ups in the recommended list for this user since last time? How often is the recommended list re-calculated?

**Comment by vanderGoes** [comment]
No, but I can ask GraphAware to add a timestamp to the recommendation (with a PR).
Rough guess every minute. Depends on the uppers & part-ups catalogue size.
