### ISSUE TITLE
As a logged in user I want to be triggered to view recommended part-up and view them

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#324]
Update: changed the issue completely based on the concepting with @LifelyPim and resulting design of Bas Dobbelaer: https://redpen.io/ho3ed4b3676abcac1f and https://redpen.io/dabf7ad1e0052c5d32

**Comment by AnnotatedJS** [comment]
What are the proposed implications when a user clicks on "newest" or ¨popular"?
Remove first the recommended part-ups and then show newest or latest starting with first batch?
Or add the first batch after the recommended part-ups?

With 'total' in ¨The total number of part-ups shown in the recommended view will be 30." do you mean always 30 or maximum 30?

Will the recommender feature recommend a total/maximum number of 30 views?
Now?
In the future?


Formulating above questions, I came to the following thoughts.

The concept 'recommended' has 2 aspects,

1. a way to sort items; this item is more recommended than that item
2. a way to filter items: these 30 items are recommended by us, all the other items are not recommended by us.

This is of course the same with 'newest´ and 'popular'. So far, part-up.com has chosen to use  'newest´ and 'popular' only as a way to sort items, not as a way to filter. (Is this assumption correct?)

But somehow part-up.com proposes to use 'recommended' differently from  'newest´ and 'popular'. Not only as a way to sort but also as a way to filter. From a user perspective this could be confusing.

And it part-up.com continues with using 'recommended' also as a filter, there is the issue of the other filter keys. Which one gets precedence? For instance, as a user, do I get all the part-ups in Berlin from the set of 30 recommended part-ups or do I get 30 recommended part-ups from all the part-ups in Berlin. Both could be relevant use cases. For the user, with the current proposed feature, this could be confusing.

**Comment by ralphboeije** [comment]
Hi @AnnotatedJS thanks for the thoughts. You are correct that the 'newest' and 'popular' are currently just sorts, not filters. Recommended will be both a sort and a filter, because it will only return the first 30 recommended part-ups. Just discussed with Maurits and we think it is best to use 20 as a fixed number of results for the recommended, but can change in the future. It is a fixed number for now. 

Your last question is a very good one and actually puts us back to the drawing table. we didn't think the UX through enough given the development on the recommender service. The search and select bar can't be used together with the recommended filter I think.

**Comment by AnnotatedJS** [comment]
@ralphboeije While at the drawing table, please take also the following in consideration.

Speaking in general terms, each filter item type could become a sort item. Quite a cryptic statement but let me explain.

Given: A part-up has, among other data, Language and Location
If I use Location to filter, for instance on Berlin, then there is no reason to use it as a sort option. However, it is nice to be able to filter on Language.
And the other way around, if I filter on Language, for instance English, it is nice to be able to sort on Location.
(Note. This is only true as long as a user can filter only on one Language and/or one Location, as is the current situation with part-up)

As a user, I am thinking in a two step process.

First, filter: which data do I want to see.
Second: sort: in what order do I want to see this data.

A third step could be a choice regarding presentation. Currently part-up.com has chosen for Tiles only at the Discover page but there are more options possible.

**Comment by ralphboeije** [comment]
Tnx @AnnotatedJS will take that into account. For now you might better take on another issue, until this one has the required UX/Design in place. For example #341 is an important one.

**Comment by ralphboeije** [comment]
see #323 for changed focus of this issue

**Comment by ralphboeije** [comment]
rediscussed this one: 
- update continuously from NEO and older part-ups are decreased in ranking
- copy change RB to fit continous update
- weekly notification

**Comment by ralphboeije** [comment]
Button, modal
Get data from API
Notification (cron-backend en front-end)
Send event to API

**Comment by AnnotatedJS** [comment]
@ralphboeije The designated place for the recommendations button ( https://redpen.io/ho3ed4b3676abcac1f ) conflicts with the invitation sentence to improve one's profile.
![part-up - discover 2016-06-16 13-53-02](https://cloud.githubusercontent.com/assets/11474975/16115772/8d4ee05e-33c9-11e6-8b61-44f92bf7f529.png).

Any suggestions?

**Comment by ralphboeije** [comment]
@AnnotatedJS Yes I know, we decided to remove this sentence as it is not in the right place for a call to action on the profile completeness.

**Comment by AnnotatedJS** [comment]
Is there an issue regarding removing this sentence and associated code?

**Comment by ralphboeije** [comment]
nope

Ralph Boeije
+31617094018

**Comment by tlimpanont** [comment]
Mock Recommendation Api with JSON data 
http://www.json-generator.com/api/json/get/cevZMrFPpK?indent=2

It's based on the local development fixtures:
```
WxrpPuJkhafJB3gfF: Partup Premium Part-up
vGaxNojSerdizDPjb: Organise a Meteor Meetup
ASfRYBAzo2ayYk5si: A semisecret ING partup, plus ones are ok
gJngF65ZWyS9f3NDE: Crowd funding Part-up organiseren
```

**Comment by tlimpanont** [comment]
See API issue https://github.com/part-up/api/issues/39

**Comment by tlimpanont** [comment]
See related issue https://github.com/part-up/api/issues/39#issuecomment-236894216

**Comment by ralphboeije** [comment]
Yes, see https://redpen.io/dabf7ad1e0052c5d32 Allignment and spacing of the text
