### ISSUE TITLE
Add autofocus to comment field after clicking comment

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#332]
When you click comment on an update, the focus should go to the input field, at least with cursor blinking in that field, but preferably also visually (scroll to).

**Comment by ralphboeije** [comment]
@AnnotatedJS this will be an easy one after todays success I guess?

**Comment by AnnotatedJS** [comment]
Not as easy as issue #1249 you are referring to.
It is easy to add `autofocus=''` at the 'right' statement but that doesn't solve the issue, at least not most of it.

I will commit a demo branch to show what I mean, but note that this branch is not intended to be PRed.

**Comment by AnnotatedJS** [comment]
@ralphboeije @noelheesen 

Please have a look at [staging of fix-focus-comment-easy](https://fix-focus-comment-easy.staging.part-up.com), ==> Lifely tribe ==> Organise a Meteor Meetup part-up

So, in some situations the autofocus works
1. after refresh
1. 1. Chrome: it works in all situations
1.2. Firefox: it never works
2. when one enters a comment, a new comment is automatically opened and this comment field has autofocus

I am not sure why the autofocus doesn't work after the first time. Any suggestions?

**Comment by ralphboeije** [comment]
@AnnotatedJS I use this sequence to test it and see that it does not work as intended:
- Go to any part-up on the staging env of your branch, e.g. https://fix-focus-comment-easy.staging.part-up.com/partups/crowd-funding-part-up-organiseren-gJngF65ZWyS9f3NDE
- Click the orange underlined "Comment" link under any update
- See the strange text "RPZZZZ: Hier het commentaar veld met autofocus erbij", but no autofocus on the new comment input field (the latter was intended in this issue).
- So the first time it doesn't work either in my experience. I personally don't think you invoked autofocus on the correct input field. @noelheesen any suggestions?

**Comment by AnnotatedJS** [comment]
@ralphboeije  This branch in its current stage is primarily mend to discuss this strange situation; the strange text is a pointer to know for certain what input field I am working on.

I tested again, on my windows machine, using the link you supplied. As follows,
- in FireFox it doesn't work.
- in Chrome, using this link, it doesn't work
- however, in Chrome, using this link, 
- 1. click on (for instance) the Activities tab
- 2. refresh the browser
- 3. click on the Conversations tab
- 4. click the orange underlined "Comment" link under any update
- 5, and the comment input field has autofocus (as is intended in this issue).

I'm quite sure that I have  invoked autofocus on the correct input field. 

@noelheesen any suggestions?

**Comment by ralphboeije** [comment]
Check, just used your steps and saw that it works indeed. Very strange behavior that it doesn't work before a navigation (for me it also worked on chrome by just clicking the activities tab and then the conversations tab - so without browser refresh)

**Comment by AnnotatedJS** [comment]
This issue can be closed?
