### ISSUE TITLE
Add placeholder key to add sender's name to email invites

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#336]
emails-invite_upper_to_partup-subject and emails-invite_upper_to_network-subject now read "Someone invites/Iemand nodigt je uit".

Someone should become **inviterName** and therefore a placeholder should be added to the key.

**Comment by ralphboeije** [comment]
@prik can you put this on this sprints' backlog? tnx!

**Comment by eriksoon** [comment]
I still like how eg Loomio does this. They use the name of the sender and make the headline personal as well. Now all mails are from part-up

![image](https://cloud.githubusercontent.com/assets/18055074/18081249/8be5f4b8-6e99-11e6-8bd4-a1c3adb8f53e.png)
