### ISSUE TITLE
Add media upload to activity description

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#339]
Frontend
- [ ] Extract media uploader class to be able to use it in the activity modal
- [ ] Add e2e tests
- [ ] Change the way the method handles the image and renders the thumbnail instead of the image itself
- [ ] Render media icon under activity description
- [ ] Add media upload icon (paperclip) to activity description
- [ ] Implement upload photo after select file
- [ ] Add description, date and attach file as modular expandable options

As an upper I want to be able to upload a document and/or image to the activity description. This issue first requires a UX/design for the add/edit modal, the update render, the activity list view render and the activity board view card render.

<img width="1440" alt="screen shot 2016-04-05 at 09 54 35" src="https://cloud.githubusercontent.com/assets/14044235/14274902/7209bd20-fb14-11e5-82a7-122654964474.png">
<img width="1440" alt="screen shot 2016-04-05 at 09 54 43" src="https://cloud.githubusercontent.com/assets/14044235/14274903/7215f694-fb14-11e5-9360-70a16575ac9f.png">
<img width="1440" alt="screen shot 2016-04-05 at 09 55 11" src="https://cloud.githubusercontent.com/assets/14044235/14274919/838e795a-fb14-11e5-8294-490c804feaf1.png">
<img width="1440" alt="screen shot 2016-04-05 at 09 56 29" src="https://cloud.githubusercontent.com/assets/14044235/14274966/b49aec04-fb14-11e5-8d6d-28c077367cfe.png">
<img width="1440" alt="screen shot 2016-04-05 at 09 56 35" src="https://cloud.githubusercontent.com/assets/14044235/14274967/b49d36e4-fb14-11e5-9aac-e349ccfe8855.png">

**Comment by prik** [comment]
@tlimpanont ik heb de backend klaargezet in de branch ft-activity-media.
De bestanden moeten in een array genaamd `media` meegegeten worden in het fields object bij een insert/edit call. 

Roep maar als er iets niet werkt.

**Comment by tlimpanont** [comment]
So how is that effecting the new message? Can we leave that as it is?

**Comment by tlimpanont** [comment]
Ah I See. It's an activity db model. OK nice!

**Comment by tlimpanont** [comment]
This template https://github.com/part-up/part-up/blob/develop/app/packages/partup-client-pages/app/partup/activities/activity/view/view.html is absolute crazy complex ([Cyclomatic complexity](url)). I refactored some code, but to implement this in **14 kind of if else** cases is crazy. Sorry guys but I would discourage the team to continue with the enhancement of this feature.
