### ISSUE TITLE
Show tribe in header, when part-up belongs to a tribe

### ISSUE THREAD

**Issue by eriksoon** [part-up/part-up#341]
I often get the feedback that people are easily lost in Part-up. Especially the ones working in tribes. I would like to give people the possibility to visit a part-up and easily go back to their tribe. Therefore I think we should show the tribe in the header when a part-up belongs to a tribe, with the possibility to go back to the tribe. This also improves the new registers on tribe level.

![part-up within a tribe](https://cloud.githubusercontent.com/assets/18055074/14308352/e9cb820a-fbd5-11e5-9f8a-5a24b43a2bd0.png)

**Comment by ralphboeije** [comment]
Interesting though indeed. Will assign the prio 1 to it and plan it for the next sprint after 18th.

**Comment by AnnotatedJS** [comment]
@eriksoon wrote, " I would like to give people the possibility to visit a part-up and easily go back to their tribe. Therefore I think we should show the tribe in the header when a part-up belongs to a tribe, with the possibility to go back to the tribe."

This sentence is not clear enough to start. 

Which tribe are we talking about? The tribe of the user or the tribe of the part-up?

**Comment by eriksoon** [comment]
The tribe of the part-up. The part-up is part of a tribe, which in not really clear and often difficult to return to for users. With this header and a 'go to tribe' call to action we can improve this.

**Comment by ralphboeije** [comment]
Hi @AnnotatedJS the tribe is listed in the lower right column "metadata": e.g. "This part-up is active until December 31, 2016 in the area of Tilburg. This part-up **is part of innovatienetwerkjeugd support tribe** and is open to everyone." Because it is below the fold, users miss it. Especially for users that are invited directly to the part-up and not to tribe first, they miss the link to all the part-ups in this tribe (ie the tribe page). So this one is important for onboarding process.

**Comment by AnnotatedJS** [comment]
This issue is put on hold, until discussed with designer.

**Comment by ralphboeije** [comment]
Discussed with @LifelyPim to add it to bar with the tabs on the part-up page. He will create the design for this next week.

**Comment by ralphboeije** [comment]
Here's the design @eriksoon I think it is good like this and that we need to work on onboarding guide on the part-up page soon. Then we can have a small modal (step 6 or so) to explain that this is the tribe the part-up is part of.

On click result for this should be the the startpage of a tribe.

**Comment by ralphboeije** [comment]
we'll tackle this when we redo the in-part-up navigation
