### ISSUE TITLE
Add media (Dropbox / images) > click icons instead of dropdown

### ISSUE THREAD

**Issue by eriksoon** [part-up/part-up#342]
I really love that we are now able to share files (with dropbox). But I think we should just display the icons of dropbox and an image instead of a dropdown. People know the icon of images from Word/Google Docs etc. And users that have Dropbox will recognize the icon as well. This way it is much clearer to the users what his options are.

![image](https://cloud.githubusercontent.com/assets/18055074/14308819/e820da1a-fbd8-11e5-895f-c8e8136d9b48.png)

**Comment by ralphboeije** [comment]
Agree to this. This is MVP on frontend, @tlimpanont is looking into filestack integration now and based on that we will either choose to use that or change the UI here.

<img width="672" alt="screen shot 2016-04-06 at 13 50 29" src="https://cloud.githubusercontent.com/assets/14044235/14315595/92ec8e92-fbfe-11e5-990a-7344a50f2463.png">
