### ISSUE TITLE
Adding attachments (now media) to an activity

### ISSUE THREAD

**Issue by eriksoon** [part-up/part-up#343]
When working on part-up most of the time execution is done trough activities. It would make sense to be  able to add attachments to an activity, just like with a message. Eg Activity "Make a project plan", quite logical to be able to attach a Dropbox file to it.

![image](https://cloud.githubusercontent.com/assets/18055074/14309042/2fcfed8c-fbda-11e5-96fa-a27cd5227a5e.png)

**Comment by ralphboeije** [comment]
duplicate to #339
