### ISSUE TITLE
Icons are misaligned on all Windows browsers (IE, Edge, Chrome etc)

### ISSUE THREAD

**Issue by andreleon** [part-up/part-up#345]
![screen shot 2016-04-07 at 16 32 44](https://cloud.githubusercontent.com/assets/1391492/14354652/63e71708-fcde-11e5-986b-7914c41cd0b4.png)

**Comment by andreleon** [comment]
I have removed and replaced the upload and download icons that were implemented in the ft-dropbox-chooser branch with the archive and unarchive icons since they look the most similar

I was unable to fix the original images @tlimpanont added, it seems that these specific icons are corrupt or something like that

**Comment by andreleon** [comment]
I also updated the section on adding new icons in the README.md to prevent future issues like this one

**Comment by tlimpanont** [comment]
@andreleon Can you explain me, why my SVG's are badly formatted? I received the SVG's from Pim
https://www.dropbox.com/sh/s843ndl4kxt9zwm/AABzH_r4ClyD4_FA-6MxJS8na?dl=0

It is a good idea to have a the same export SVG method.
