### ISSUE TITLE
Move on fast after delete/archive a part-up

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#35]
As an upper I want to delete/archive (see issue #22) the part-up fast and not wait for a couple of seconds before I am redirected to the discover page.

**Comment by andreleon** [comment]
> You see the content of the part-up being deleted before you are redirected to discover

@ralphboeije could you please re-test this on **acceptance**? I cannot reproduce this behaviour

**Comment by ralphboeije** [comment]
@andreleon last few weeks I also didn't see this issue occur anymore. So let's close this one for now.
