### ISSUE TITLE
Localhost cannot read Amazon https://s3-eu-west-1.amazonaws.com/partup-production/ images

### ISSUE THREAD

**Issue by tlimpanont** [part-up/part-up#350]
![screen shot 2016-04-10 at 15 37 15](https://cloud.githubusercontent.com/assets/617876/14410555/f2ae5e5a-ff32-11e5-91a1-0b89d75b321b.png)
![screen shot 2016-04-10 at 15 37 07](https://cloud.githubusercontent.com/assets/617876/14410556/f2b0c488-ff32-11e5-9fee-ff26413a895b.png)

**Comment by peterpeerdeman** [comment]
leon accidentally committed the "partup-production" value for key public.aws.bucket in config/development/settings.json. If you revert that value back to "pu-development" everything should work as before

**Comment by tlimpanont** [comment]
@peterpeerdeman thanks!
