### ISSUE TITLE
When part-up created in a Tribe, don't ask 'open or private' question

### ISSUE THREAD

**Issue by eriksoon** [part-up/part-up#351]
When a part-up is created from a tribe, you still get the question 'Waar wil je dat jouw part-up te zien is?'. Too often people make the mistake to choose 'private'. We should skip this option. Makes it more simple.

![image](https://cloud.githubusercontent.com/assets/18055074/14412516/d419204c-ff64-11e5-88da-c045458ab1fa.png)

**Comment by ralphboeije** [comment]
Erik, did you see #50 Not exactly the same but related

**Comment by eriksoon** [comment]
I did, and that's what should be done as well. But leaving out this question makes it easier and less possibilities on flaws.
