### ISSUE TITLE
Uppers tab still not available for tribe admins

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#375]
#306 had to fix this and I thought it was, but now it seems that is still broken.

To reproduce (mac+chrome tested):
1. Log in to part-up with a tribe admin account
2. Go to the tribe settings
3. Click the Uppers tab
4. See the strange 404 with the typo appear like in the screenshot below

<img width="1440" alt="screen shot 2016-04-12 at 11 17 54" src="https://cloud.githubusercontent.com/assets/14044235/14455524/3845728c-00a0-11e6-995b-5a01bcd519a8.png">

**Comment by peterpeerdeman** [comment]
fixed in a962f13f8a6c59dc8e5ea1edbccd293e503cfe5f
