### ISSUE TITLE
Can't update tribe locally due to translate API

### ISSUE THREAD

**Issue by vanderGoes** [part-up/part-up#377]
When I try to update an tribe in my local test environment the new value are not stored due to a usageLimit of the Google Translate API. The website notifies that the tribe is updated though

`meteor_1 | error: Error while detecting language: Error: failed [403] {  "error": {   "errors": [    {     "domain": "usageLimits",     "reason": "dailyLimitExceeded",     "message": "Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/translate/quotas?project=364113953901",     "extendedHelp": "https://console.developers.google.com/apis/api/translate/quotas?project=364113953901"    }   ],   "code": 403,   "message": "Daily...`

**Comment by vanderGoes** [comment]
Weird, actually the new values are stored, but I can't find them in the docker logs or mongo event log. The quest continues.

**Comment by vanderGoes** [comment]
@peterpeerdeman Are the API keys of Google Translate not included in local versions?

**Comment by peterpeerdeman** [comment]
That is correct. The translate API is not free and charges per request,
which is why it is only configured on production (and i believe acceptance
had it as well)

**Comment by vanderGoes** [comment]
OK, why does it get triggered when updating a tribe?
And why can't I access the admin panel locally while using admin@example.com

**Comment by peterpeerdeman** [comment]
tribes have an automatically detected language based on the description as well. For me, the admin@example does load the admin panel locally, theuy could also get it to work, can you maybe check with him?
