### ISSUE TITLE
Partner's tab has duplicate results

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#380]
The new partners tab on the upper profile shows duplicate results. Check https://part-up.com/profile/7f9hyJfDQ66tB6zpF/partners and see that you can scroll down endlessly. Moreover, it the title says "Eva has 63 partners, but in here profile card it says 38 partners (see screenshot).

<img width="302" alt="screen shot 2016-06-02 at 12 04 00" src="https://cloud.githubusercontent.com/assets/14044235/15741482/359baed8-28ba-11e6-8985-3e28ef0b72e9.png">

Please also check if the partners tab only displays the partners you have been in a part-up with (no supporters).

**Comment by andreleon** [comment]
@ralphboeije The number on the user tile is not the same as the number of partner the upper has worked with. The number on the upper tile represents the amount of Part-ups the user is a Partner of. It also does not take into account the number of archived part-ups. The exact same is true for the Supporters count on the upper tile.

If you want this changed, you can update the copy for these statistics or open a **new issue** to change these values to represent different statistics.

**Comment by andreleon** [comment]
@ralphboeije I fixed the duplicate issue in commit 	937c41e

**Comment by ralphboeije** [comment]
@andreleon check, of course. To quick on the draw here. Thanks for this fix.
