### ISSUE TITLE
Add Google drive file picker to add message modal

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#385]
@tlimpanont already has worked on this, I will add the findings of the acceptance test below.

**Comment by ralphboeije** [comment]
Finding 1: consent screen is visible for a sub second, which looks like a glitch, because the consent screen has a different size than the filepicker dialog.

**Comment by ralphboeije** [comment]
Upload png and jpg gives internal server error. Doc works fine, other files not tested yet.

**Comment by ralphboeije** [comment]
Uploading anything but images still fails @tlimpanont Same error as last Friday I believe (see screenshot). Thought you said you found a fix?

<img width="1440" alt="screen shot 2016-04-24 at 23 53 36" src="https://cloud.githubusercontent.com/assets/14044235/14770683/c7d75556-0a77-11e6-9cb5-ea33ee6678ee.png">

**Comment by ralphboeije** [comment]
Not a big issue, but I discovered that the Initial connection to api.google.com renders drop down unresponsive for a sec on first load.

**Comment by ralphboeije** [comment]
We need a warning message on posting a message with a doc shared from GDrive stating: "You are posting a message with a file from Google Drive attached. By doing so, you agree to make this file visible for anyone that has access to this part-up. This part-up is visible to <metadata on part-up privacy level and tribe>." // "Je plaatst een bericht met een bestand vanaf Google Drive als bijlage. Hierdoor wordt dit bestand zichtbaar voor iedereen die toegang heeft tot deze part-up. Deze part-up is zichtbaar voor <metadata on part-up privacy level and tribe>."

**Comment by ralphboeije** [comment]
Another idea: we need to inform users better of the limits in doc uploads when they want to add too much media. Can we highlight the counter in orange when the number of uploads is larger than allowed?

**Comment by ralphboeije** [comment]
Not a new one I caused by this feature think, but just saw it: NL copy makes loader image disappear behind dropdown icon (see screenshot)

<img width="1440" alt="screen shot 2016-04-25 at 15 25 10" src="https://cloud.githubusercontent.com/assets/14044235/14785219/058ba1b8-0afa-11e6-8820-1382f04359a8.png">

**Comment by eriksoon** [comment]
When I want to add a Drive file it opens all folders. I rather have the same structure as in My Drive and Shared with me. Can this be changed @tlimpanont 
![image](https://cloud.githubusercontent.com/assets/18055074/15016418/38281458-1211-11e6-9268-b5667fdcd4cd.png)

**Comment by tlimpanont** [comment]
There's not much config options anymore, but you can try to find it your self. https://developers.google.com/picker/docs/reference#DocsUploadView

**Comment by eriksoon** [comment]
Don't really get what I could find...

**Comment by ralphboeije** [comment]
@eriksoon of course we checked the options during development. Would also love MyDrive as default, but this is the best there is. MyDrive (your default view in Drive) is not an option in the API as default view of the file picker. You can find MyDrive as one of the folders in this view though. Anyway, search in drive is pretty good, so also in this file picker.
