### ISSUE TITLE
missing bingbot in SEO routes

### ISSUE THREAD

**Issue by tlimpanont** [part-up/part-up#390]
```
 var botAgents = [
        /^facebookexternalhit/i, // Facebook
        /^linkedinbot/i, // LinkedIn
        /^twitterbot/i, // Twitter
        /^slackbot-linkexpanding/i, // Slack
        /^bingbot/i // Bing
    ];
```

**Comment by ralphboeije** [comment]
Hi @tlimpanont Bing still does not rank Part-up.

**Comment by tlimpanont** [comment]
@ralphboeije have my doubts about the solution mentioned above. I remembered that this solution is suggested by @peterpeerdeman

**Comment by andreleon** [comment]
![screen shot 2016-10-19 at 15 51 21](https://cloud.githubusercontent.com/assets/1391492/19521425/ea10bcca-9613-11e6-9284-85b2cfefd77c.png)
