### ISSUE TITLE
Duplicate search results in invite modal

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#391]
#314 acceptance test result number 1 still not completely fixed. To reproduce:

1. In https://part-up.com/partups/share-technology-at-permanent-beta-dag-8-amsterdam-iNDoiyN6zExAHCdQt/invite you see that Samir Lahiri is presented twice.
2. See this screenshot below. Was reported by a user and reproduced it for the screenshot, but can't reproduce it now somehow...

<img width="1440" alt="screen shot 2016-04-21 at 15 40 28" src="https://cloud.githubusercontent.com/assets/14044235/14711986/b8705b06-07db-11e6-9550-cdc5c8c5b11a.png">

**Comment by andreleon** [comment]
@ralphboeije I cannot reproduce this issue on any environment. Any steps would be really useful, without I can't fix it.

**Comment by ralphboeije** [comment]
I can't either. It was consistent with the steps listed here back then. Automagically fixed...
