### ISSUE TITLE
Move part-ups in and out of tribes

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#392]
As Part-up admin I want to be able to move a part-up from the public platform into a tribe (public and/or private) and to move a part-up from a tribe (public and/or private) to another tribe (public and/or private).

In the admin panel the part-ups should be listed like the tribes and swarms are in their tabs, with a search like the Overview tab has for Uppers. For each part-up the tribe should be listed and be clickable like the admin for tribes are on the tribes tab. On-click results is a pop-up with a search for tribes.

NB: uppers in a part-up do not automatically become members of the tribe if they aren't yet.

**Comment by AnnotatedJS** [comment]
Where can I find the admin panel?

**Comment by AnnotatedJS** [comment]
Is it correct to assume that with 'Part-up' we mean the system/service Part-up (= part-up.com) and with 'part-up' we mean a part-up as started by an 'upper'?

**Comment by ralphboeije** [comment]
your assumption is correct. the trigger would be a user asking for it. The reason being that he/she starts a tribe after first starting a part-up and next wants to add the old part-up to the new tribe.

**Comment by ralphboeije** [comment]
admin panel should be in part-up.com/admin, but I see that it is not visible on local and staging. Will ask @peterpeerdeman about it today.

**Comment by peterpeerdeman** [comment]
it looks like the problem might have something to do with intercom not loading properly on staging. During the meeting today everyone was able to get the admin panel working locally so it should just work for you as well. Are you sure you are loggedin as admin user? user: admin@example.com pw: user
