### ISSUE TITLE
Confirmation email images not showing

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#394]
Part-up confirmation email doesn't show correct images for Part-up logo in header, and of socials twitter, FB, LI in footer. See screenshot.

<img width="916" alt="screen shot 2016-04-21 at 22 46 09" src="https://cloud.githubusercontent.com/assets/14044235/14723755/ee2016a6-0812-11e6-80b6-60b8d8898d84.png">

**Comment by ralphboeije** [comment]
And does anyone know how we can change the image of laurens to the Part-up logo in the sender?

**Comment by peterpeerdeman** [comment]
@ralphboeije My guess is that you'll have to open the google admin console on the part-up.com google account, find out which account currently has laurens' image attached to it and change it in that profile. team@part-up.com might be an alias for laurens, and therefore inherit that picture?

closing the original issue now
