### ISSUE TITLE
Create improved datadump on new jenkins

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#399]
Patrick and Joost would like to access an anonimized datadump for R&D use. As discussed in the standup of 26/4/16, @peterpeerdeman suggests to create a new configuration on the new jenkins, instead of upgrading the existing one on the old jenkins.

**Comment by wouterd** [comment]
Ideas of what need to happen:
- replace all IDs with new ones, but keep the right relations
- strip all personal data (or scramble)
- find a place to host the dump

**Comment by ralphboeije** [comment]
Hosting can be AWS I think, we do RBAC there for a specific container. We already strip stuff in the current datadump, like pwd hashes, so it needs to be extended.

**Comment by ralphboeije** [comment]
Discussed that we don't want to use data dumps anymore given the privacy risks. We decided to create more test data for development and a specific machine for production testing with permissions and access rights.

**Comment by wouterd** [comment]
As discussed with @jplattel earlier, we should create some sort of query console that's accessed via the web via HTTPS and integrates with IAM on AWS so we can give/revoke specific people access to query.

If there will ever be another datadump then a datadump should only expose public partups/profiles and only the data in there that can be accessed publicly via the website without specific ACL.

**Comment by ralphboeije** [comment]
@wouterd so I think this issue can be closed now?

**Comment by wouterd** [comment]
Well, we have the technology in place. There's a datadump for the dashboard.
IF that's enough, then we can close the thread. :)

**Comment by ralphboeije** [comment]
for now, it is enough
