### ISSUE TITLE
Add archived part-ups to discover

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#400]
As a user I want to be able to find archived part-ups on the discover page when I search for them.

This issue is related to the redesign of the discover page mention in #324

**Comment by ralphboeije** [comment]
My idea is to add it to the newest/popular filter on discover

**Comment by AnnotatedJS** [comment]
Currently there is no newest/popular filter on discover. Newest and popular are used to **sort** the filtered.
Being archived or not is a Boolean property of a part-up and as such reminds me of the standard Todo Demo App. 
Generally speaking, a user wants to see,
- All part-ups,
- Only the active part-ups,
- Only the archived part-ups.
(This of course in the context of his other filter settings.)

See also discussion of https://github.com/part-up/part-up/issues/324

**Comment by ralphboeije** [comment]
You are totally right. I think active or archived would suffice in general as it is implemented on the tribe and profile pages.
