### ISSUE TITLE
Improve activities and contributions ux

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#411]
Problems:
- Contribute to activity is hidden
- Hard to find archive option on activity
- Copy on "I want to do this button" and "Available activities filter" suggests only one person can do the activity
- 2 clicks needed to see the comments
- Edit activity is 2 clicks away and only visible on hoover

Possible solutions:
- Add archive to on hoover (or checkmark on activity for partners?)
- Add edit to on hoover
- Show "contribute" and "invite" buttons on hoover and go to activity detail on click, do this also for archived, and show first activity expanded

**Comment by AriellevdLinde** [comment]
@ralphboeije I've made some first drafts and a prototype to see how it works, you can find the prototype here: https://marvelapp.com/15dfee2. Tomorrow I can show the other screens.

**Comment by AriellevdLinde** [comment]
@ralphboeije Here you can find a first draft of the activities in an trello-like board: https://marvelapp.com/1ga461f

**Comment by ralphboeije** [comment]
@eriksoon kijk je mee?

**Comment by ralphboeije** [comment]
Some findings when comparing to Trello and Github:
- Overall I love it, and I think we can improve on the 'chunky feeling' of a card (check Trello)
- Title is a bit chunky (font size?)
- Description makes the card take too much vertical space
- Contributors take quite some space (but love the images)
- How will we manage responsiveness of the four lanes?
- How will edit flow go (afraid of four clicks)?

**Comment by AriellevdLinde** [comment]
@ralphboeije I've made everything less chunky: https://marvelapp.com/12gd539

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon 
Here you can find both versions for the activities. My suggestion is to keep both ways of activities (list and 'trello' board). When people start a part-up they can choose which one they want. This way we can test which version is most appreciated by the users (or maybe we see that people like to have the choice, depending on the type of project).

**## Improved list**

**1.1 Improved activities overview**
![411 1 1 improve activities - overview](https://cloud.githubusercontent.com/assets/22590642/20490403/28133a7a-b00e-11e6-8fe8-cbc27ce08f66.png)

**1.2 Improved activities overview - hover**
![411 1 2 improve activities - overview hover](https://cloud.githubusercontent.com/assets/22590642/20490402/2811d482-b00e-11e6-9404-91ac18f110e1.png)

**1.3 Improved activities overview - hover first (already a partner)**
![411 1 3 improve activities - overview hover first](https://cloud.githubusercontent.com/assets/22590642/20490404/2813feba-b00e-11e6-84b6-215177f1a6aa.png)

**1.4 Improved activities overview - archive**
![411 1 4 improve activities - archive](https://cloud.githubusercontent.com/assets/22590642/20490406/28150c24-b00e-11e6-88ac-29e27594b106.png)

**1.5 Improved activities overview - detail activity**
![411 1 5 improve activities - overview hover](https://cloud.githubusercontent.com/assets/22590642/20490405/281514f8-b00e-11e6-91d8-eb1f08687913.png)


**## Ideal version ("Trello" board)**

**1.1 Ideal - Improved activities overview**
![411 ideal 1 1 improve activities - overview agile version](https://cloud.githubusercontent.com/assets/22590642/20490407/28166920-b00e-11e6-8bbb-2bdced8a10b7.png)

**1.2 Ideal - Improved activities overview - Drag & drop**
![411 ideal 1 2 improve activities - overview agile version - drag drop](https://cloud.githubusercontent.com/assets/22590642/20490410/2828bc2e-b00e-11e6-8c3c-43e79e134b11.png)

**1.3 Ideal - Improved activities overview - options**
![411 ideal 1 3 improve activities - overview agile version - options](https://cloud.githubusercontent.com/assets/22590642/20490409/282771d4-b00e-11e6-8959-f3736fae07c3.png)

**1.4 Ideal - Improved activities - detail activity**
![411 ideal 1 4 improve activities - overview agile version - detail](https://cloud.githubusercontent.com/assets/22590642/20490411/282c600e-b00e-11e6-9b0c-d2f18ad8588d.png)

**1.5 Improved activities - detail activity - hover**
![411 ideal 1 5 improve activities - overview agile version - detail](https://cloud.githubusercontent.com/assets/22590642/20490412/282ddc0e-b00e-11e6-805d-83992a34c906.png)

**Comment by ralphboeije** [comment]
@AriellevdLinde need a design for setting the preference in the start a part-up form https://part-up.com/tribes/<tribename>/partups/create. Idea of @andreleon is to use two example images and a click to choose/highlight

**Comment by ralphboeije** [comment]
@AriellevdLinde design needed for activity detail view when accepting contribution. You don't want that in a dropdown like we put the other buttons in

**Comment by ralphboeije** [comment]
Lastly a responsive design is needed

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon 
Here (and also on Zeplin) you can find the two examples of activities:
![411 ideal 1 0 improve activities - choose between two types of activites](https://cloud.githubusercontent.com/assets/22590642/22298167/d6718b6e-e31f-11e6-9c36-aaaf6d103b42.png)

Copy needs to be looked at.

**Comment by AriellevdLinde** [comment]
The responsive (mobile) version of the agile activities:
![411 ideal iphone 375px - 1 1 improve activities - overview agile version](https://cloud.githubusercontent.com/assets/22590642/22299274/ca7df082-e323-11e6-8be8-85fdd4c942b2.png)
![411 ideal iphone 375px - 1 2 improve activities - overview agile version - move to right](https://cloud.githubusercontent.com/assets/22590642/22299275/ca807c3a-e323-11e6-843e-c98f8682c93c.png)

**Comment by AriellevdLinde** [comment]
And last, the activity detail. The dropdown will work te same as in the above screen (you have to click it away): 
![411 ideal iphone 375px - 1 4 improve activities - overview agile version - detail](https://cloud.githubusercontent.com/assets/22590642/22299569/f3385606-e324-11e6-8b0f-e00c0cb9b74c.png)

**Comment by eriksoon** [comment]
Ziet er goed uit, wat mij nog opvalt is dat de tekst bovenin met de stappen
transparant is. Hierdoor is een overloop met de achterliggende tekst soms
rommelig. Kan hier ook een smal wit kader achter?

Op 25 jan. 2017 5:02 p.m. schreef "AriellevdLinde" <notifications@github.com
>:

@ralphboeije <https://github.com/ralphboeije> @andreleon
<https://github.com/andreleon>
Here (and also on Zeplin) you can find the two examples of activities:
[image: 411 ideal 1 0 improve activities - choose between two types of
activites]
<https://cloud.githubusercontent.com/assets/22590642/22298167/d6718b6e-e31f-11e6-9c36-aaaf6d103b42.png>

Copy needs to be looked at.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/part-up/part-up/issues/411#issuecomment-275148465>, or mute
the thread

**Comment by ralphboeije** [comment]
@eriksoon please specify what design you are referring at. Do you mean the choice for activity style in the start a part-up form?

**Comment by eriksoon** [comment]
No I mean the header which shows the three steps of creating your part-up.
The text is an overlay field which is transparant. My suggestion is to make
the background white.

Op 26 jan. 2017 9:14 a.m. schreef "Ralph Boeije" <notifications@github.com>:

**Comment by ralphboeije** [comment]
Check, this issue is mentioned in already #819

**Comment by andreleon** [comment]
@AriellevdLinde I can't export the partup-settings board button images from Zeplin.

**Comment by AriellevdLinde** [comment]
@andreleon You can now export the images from zeplin.

**Comment by ralphboeije** [comment]
@andreleon finding: on activity detail, when you click back to overview, you go back to updates, instead of activities. Is probably something that is like this for some time already, but good to fix that in this project.

**Comment by prik** [comment]
@ralphboeije when I start a part-up in scrum mode, the 2 added activities that I added during the setup are shown (https://acceptance.part-up.com/partups/testing-HfWr3GJ8PLoZjma7t/activities).
So I don't really understand what you encountered with those last 2 findings. On what part-up was that?

**Comment by ralphboeije** [comment]
@prik These findings were before the acceptance release, so these are fixed already.

**Comment by ralphboeije** [comment]
@andreleon and @prik looking great. I am really happy with this new feature. I just stress-tested it a bit with @jplattel and we saw that it is possible to create a duplicate of an activity in the frontend when two users dnd the activity around. I think this is the last issue before the release. Is it possible to look at this today?

<img width="1440" alt="screen shot 2017-02-07 at 11 12 28" src="https://cloud.githubusercontent.com/assets/14044235/22687363/fdd86b48-ed27-11e6-909a-e0e0db77cbc5.png">

**Comment by ralphboeije** [comment]
BTW this is the link to view this: https://ft-board-view.staging.part-up.com/partups/go-for-it-mBKy2d49YyaobQ5js/activities
