### ISSUE TITLE
Featured part-ups is broken

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#412]
Findings: only 1 part-up shows, but more than 1 have been featured in admin panel, on several quotes, the author is missing.

To reproduce:
1. go to part-up.com, check featured part-ups and refresh
2. see that the featured part-up is still the same
3. see that the author is missing beneath the quote (see screenshot)
<img width="1440" alt="screen shot 2016-05-09 at 13 16 37" src="https://cloud.githubusercontent.com/assets/14044235/15111775/a7b6c086-15e9-11e6-9892-96e6ace55de6.png">

**Comment by andreleon** [comment]
@ralphboeije The random featured part-up seems to work just fine, are you sure there are more than one featured part-ups in the same language?

**Comment by ralphboeije** [comment]
random works now, yes. Strangely so, I tested it quite thoroughly I thought, but just leave it for now as it works.

**Comment by peterpeerdeman** [comment]
missing author confirmed fixed on acceptance
