### ISSUE TITLE
Two emails for one notification, 

### ISSUE THREAD

**Issue by AnnotatedJS** [part-up/part-up#413]
First I received an email with something like "Hi user, Somebody mentioned your name in part-up XYZ [etc.]" with a link to the specific message in this part-up.

About 15 minutes later I received a message with in the header "Notifications on Part-Up.com" and in the body the text along the line of "Hallo User, You have one new message, Have a look at https://part-up.com/."
And clicking on the link I'll get on the part-up homepage for already signed in people. This homepage contains a friendly "Goodmorning, User" but no explicit indication on what to do next.

From the user perspective this is confusing and/or annoying.

**Comment by ralphboeije** [comment]
The second email is a daily digest, so that is not an error. The call two action and the on click result should be improved though.
