### ISSUE TITLE
Tribe chat search

### ISSUE THREAD

**Issue by peterpeerdeman** [part-up/part-up#418]
As a partup user I want to be able to search through a tribe chat history and see a highlighted overview of chat messages containing a certain search query

see https://redpen.io/bf53633a8a19a9ea32

**Comment by ralphboeije** [comment]
Question by @tlimpanont and @wouterd: how are we going to implement search in the web app (mongo? anything else?) and how?

**Comment by peterpeerdeman** [comment]
search in the webapp is currently implemented using mongodb regexes or using text searches. In the future we might have to think about indexing content to a separate system such as elasticsearch but we do not see the need for that at this scale yet. @tlimpanont @wouterd
