### ISSUE TITLE
Dynamic context on Window Title 

### ISSUE THREAD

**Issue by tlimpanont** [part-up/part-up#428]
See PR Fix window title https://github.com/part-up/part-up/pull/181

**Comment by tlimpanont** [comment]
https://github.com/part-up/part-up/pull/181

**Comment by ralphboeije** [comment]
Part-ups: part-up title, tribes: tribe title, swarms: swarm-title, profile: profile name
Fallback for else: Part-up

**Comment by tlimpanont** [comment]
@AnnotatedJS @ralphboeije please keep in mind that title such as "Forgot password" are not translatable right now. But we will create a new issue for it to make it happened

**Comment by tlimpanont** [comment]
@AnnotatedJS please refactor your according to this comment of Peter:

```
Ik had nog een paar extra puntjes feedback, voornamelijk de formatting van windowtile.js (even jscs overheen draaien) en het aanroepen van de windowtile.init methode, het zou netter zijn om die te verplaatsen naar bootstrap.js 
we hebben voor al die partup namespace files in client-base/client best wel een strakke standaard structuur, zou fijn zijn om die gelijk te houden over alle (nieuwe) files

```

**Comment by tlimpanont** [comment]
@AnnotatedJS I've refactored the code https://github.com/part-up/part-up/commit/63520733be637094d7dad2adcbb68f3fd623f647
