### ISSUE TITLE
Unicode Profile settings in Tag does not work

### ISSUE THREAD

**Issue by tlimpanont** [part-up/part-up#430]
If I put for example ëkobîkôns as a Tag, then the system is gonna crash
<img width="638" alt="screen shot 2016-05-17 at 16 59 37" src="https://cloud.githubusercontent.com/assets/617876/15327266/20c896e4-1c51-11e6-8449-f852f37a8fc8.png">

**Comment by ralphboeije** [comment]
In the Swarm title the & sign is rendered as &AMP; e.g. if you don't upload a logo to this tribe it shows VOOGD&AMP;VOOGD - https://part-up.com/voogdandvoogd

**Comment by andreleon** [comment]
@ralphboeije I don't get how this has anything to do with this issue, could you please elaborate?

**Comment by ralphboeije** [comment]
I don't either ;-) there completely separate...
