### ISSUE TITLE
Spurious 'User is invited' text when I want to invite users for a part-up activity

### ISSUE THREAD

**Issue by AnnotatedJS** [part-up/part-up#433]
After defining a new activity within a part-up, I clicked on 'I invite someone' (NL: Ik nodig iemand uit).

The app opens a modal which contains Recommended uppers for this activity. Two of them with a button 'Invite' followed by 8 uppers with the text, 'Already invited' (NL:  Uitgenodigd).

What does that mean? I haven't invited anybody, so what gives?

![part-up invite 2016-05-19 11-37-52](https://cloud.githubusercontent.com/assets/11474975/15389492/7ee7d5ca-1db7-11e6-99c9-5cca1e4133c6.png)

**Comment by ralphboeije** [comment]
Good UX observation, @AnnotatedJS Are they already partners in your part-up? In that case it can be explained by the fact that you cannot invite uppers that are already partner.

**Comment by AnnotatedJS** [comment]
No, at this moment I am the only partner. I wanted to invite at least one of my two supporters but that didn't work. See issue  #434

**Comment by AnnotatedJS** [comment]
@ralphboeije I re-checked my part-up page and I noticed a message of Eva that I had missed before.

Some questions and a remark:
- Who the Bleep is Eva?
- Why does she invite people to my part-up?
- Why those people?
- Has she some 'magical' abilities in her chest?
- What does happen when someone accepts the invitation?
- Is that person than a partner, a supporter?
Very confusing!


![part-up spurious 2016-05-23 20-15-47](https://cloud.githubusercontent.com/assets/11474975/15479929/0ab85606-2123-11e6-850c-d88633770528.png)

**Comment by AnnotatedJS** [comment]
I clicked again on 'I invite someone' (NL: Ik nodig iemand uit). There is no functionality to de-invite a person.

**Comment by ralphboeije** [comment]
fixed in #692
