### ISSUE TITLE
 'Match failed' error when using suggested uppers to invite to a part-up activity

### ISSUE THREAD

**Issue by AnnotatedJS** [part-up/part-up#434]
After defining a new activity within a part-up, I clicked on 'I invite someone' (NL: Ik nodig iemand uit).

The app opens a modal which contains recommended uppers for this activity of which two with a button 'Invite'
If I click on the button I get the message, "Match failed".

See also #427 

![part-up invite 2016-05-19 11-39-02](https://cloud.githubusercontent.com/assets/11474975/15389612/1a95ac2c-1db8-11e6-85f3-1fe4c2b84a95.png)

**Comment by ralphboeije** [comment]
fixed in the commit mentioned in #427
