### ISSUE TITLE
Some notification types not configured properly according to related i18n key

### ISSUE THREAD

**Issue by jessedvrs** [part-up/part-up#436]
In short: some i18n keys need to be updated and some code according to it.

**Current situation**
Notifications have types. For instance: `partups_messages_inserted`. Therefore, the i18n translation key to compose the notification message is `dropdown-notification-partups_messages_inserted`. So the rule is `dropdown-notification-<notification_type>`.

For 23 notification types, this is correctly configured. Though, for 2 notification types, this is not the case:

```
notification type: partups_archived
i18n key: dropdown-notification-partup_archived_by_upper

notification type: partups_unarchived
i18n key: dropdown-notification-partup_unarchived_by_upper
```

**The problem**
Until now, only the web client uses the key, and since we have Blaze files for every notification type we don't use a key abstraction like `dropdown-notification-<notification_type>` so for the web client it's just code inconsistency, not really a problem. Though, the Part-up app uses an abstraction but the app uses a temporary set of i18n keys since we haven't integrated Phraseapp yet. Now, a third case is coming up: the Part-up server sending a push notification to devices. Since the app also use an abstraction of the i18n, this will be a problem.

**In a PR, the following steps should be taken:**
Since notification types are hardcoded into a database and we want to prevent performing any migrations when possible, I assume we use `partups_archived` instead of `partup_archived_by_upper` and `partups_unarchived` instead of `partup_unarchived_by_upper`.

- [x] This should be changed in Phraseapp.
- [x] This should be changed in app/packages/partup:client-dropdowns/notifications/notification/types/partup/archived.html and -/unarchived.html.
- [ ] The exception in the app should be removed (if Phraseapp has been integrated before this issue is fixed). I'll reference to this issue in the app using `// Issue #436` (use global search to find it).
- [ ] The exception in the server should be removed (if push-notifications has been integrated before this issue is fixed). I'll reference to this issue in the app using `// Issue #436` (use global search to find it).

**Comment by ralphboeije** [comment]
@tlimpanont we need this one to use phraseapp properly for the app.

**Comment by tlimpanont** [comment]
@jessedvrs can you help me with this?

**Comment by ralphboeije** [comment]
@andreleon dropdown-notification-partup_archived_by_upper is still not properly configured as it still doesn't show the copy that I've set in Phraseapp
