### ISSUE TITLE
Text of 'Nodig iemand uit voor deze part-up' not consistent

### ISSUE THREAD

**Issue by AnnotatedJS** [part-up/part-up#448]
Minor issue: When you want to invite a person to your part-up the text of the modal "Nodig iemand uit voor deze part-up' is not consistent.
Specifically the sentences,
- We hebben vast een voorbeeldmail voor je gemaakt. 
- Voeg je persoonlijke noot toe en stuur hem op!
- Verwijder de [name] en [url] tags in de uitnodiging niet. 

"Voorbeeldmail" suggests that I have the freedom to change everything, discard the text, replace it with my own text.
"Voeg je persoonlijke noot toe" suggest that I have to leave the text as is and just add some text of my own to this text.
"Verwijder de [name] en [url] tags in de uitnodiging niet" suggests that we can chang anything in the text except the [name] and [url] tags

**Comment by ralphboeije** [comment]
I changed the copy to:

You might want to work with someone you know, but who is not an upper yet. Here you can invite them to become upper and join your part-up.

We drew up an invitation email for you. Feel free to rewrite it, but don’t remove the [name] and [url]. This is where we will automatically fill in the right data, such that everyone receives a personal email.
