### ISSUE TITLE
More spurious 'User is invited' text when I use filter to find a user for a part-up activity

### ISSUE THREAD

**Issue by AnnotatedJS** [part-up/part-up#449]
In the context of inviting a user for an activity of my part-up, I decided to use the filter to get to a specific upper. The filter worked correct, it showed me the upper I was looking for, however the upper also was marked as 'already invited' 
That is not correct; I had not already invited this upper. Also Eva had not already invited this upper (&nbsp;see second screenshot of issue #433 ).

(Maybe another issue ==>) And when I remove the text in the filter input field, I get back to the screen as on the first screenshot of issue #433 In other words, without the upper that came up through the filter marked as already invited. That suggest to me that there are more uppers already invited for this part-up than I know off. 

Feature request: A list with all the uppers already invited to my part-up with an indication who and for what reason they where invited?

![part-up invited 2016-05-23 21-22-36](https://cloud.githubusercontent.com/assets/11474975/15482400/b9f69e96-212f-11e6-8946-cb4770901ac2.png)

**Comment by ralphboeije** [comment]
The request here is listed in #454. Next to that, it is totally unclear to users that you cannot invite a partner or already invited upper (on another activity or the part-up in general) to the activity. We should remove those restrictions.

**Comment by ralphboeije** [comment]
fixed in #692
