### ISSUE TITLE
Update homepage layout for public viewers 

### ISSUE THREAD

**Issue by tlimpanont** [part-up/part-up#452]
![gs5gpdbqzshbnwfsp-gs5gpdbqzshbnwfsp](https://cloud.githubusercontent.com/assets/617876/15546337/cf57a1ec-229f-11e6-8d33-5f44bc990e5b.jpg)

**Comment by tlimpanont** [comment]
![cf57a1ec-229f-11e6-8d33-5f44bc990e5b](https://cloud.githubusercontent.com/assets/617876/15555938/71db64a0-22cb-11e6-95e8-e3e900c31d13.jpg)

@ralphboeije

**Comment by ralphboeije** [comment]
Tnx @tlimpanont, copy is changed in Phraseapp. You can do a pull.
