### ISSUE TITLE
Part-ups within (certain) tribes aren't loading

### ISSUE THREAD

**Issue by eriksoon** [part-up/part-up#469]
Since the last release, some tribes (with part-ups) aren't loading their part-ups or uppers. Both in Chrome and Edge with Windows 10.

**Comment by ralphboeije** [comment]
@eriksoon please provide examples for us to reproduce this one!!

**Comment by ralphboeije** [comment]
Just retested this issue and it is a problem with private and invite tribes. They do not display the uppers and part-ups in these tribes.

**Comment by peterpeerdeman** [comment]
got fixed in 38a932d01022ba5b9a81a434d3e8d0b0bdf434d6, deploying hotfix 1.19.1 to acceptance and production now
