### ISSUE TITLE
Log in issues

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#471]
Since about a week we have login issues reported by several users, but couldn't reproduce them so far on Mac+Chrome. Here we gather all the error reports to try to find the root cause. General observations:
- Cookie tossing error #467 
- Language selection: you now always first see everything displayed in EN en only later it changes to NL (in private with dutch IP)
- Linkedin login sequence (Win10/Linux+Chrome): pop-up opens, but closes directly and leaves the spinner on the linkedin login button (on Part-up) spinning endlessly

**Comment by ralphboeije** [comment]
Laurens reports having a blank screen (see screenshot) and only intercom and cookie bar being loaded. On both wifi and 4g, even after a restart of the system, restart of the browser and cache clearing.

![schermafdruk 2016-05-30 21 52 15](https://cloud.githubusercontent.com/assets/14044235/15665796/61045858-270d-11e6-917a-414b46d6445a.png)

**Comment by ralphboeije** [comment]
User on Ubuntu + Chrome reports this error log (can use FF on his laptop):

![lijkt echt een chrome issue te zijn](https://cloud.githubusercontent.com/assets/14044235/15665911/1d0c03de-270e-11e6-93b5-31996ea6772e.jpg)

![slack for ios upload png](https://cloud.githubusercontent.com/assets/14044235/15665935/3c8b1f92-270e-11e6-8439-f7b756c3b676.jpeg)

![slack for ios upload](https://cloud.githubusercontent.com/assets/14044235/15665941/418d201c-270e-11e6-97c3-c39037cb6eb8.jpg)

**Comment by ralphboeije** [comment]
Erik reports this issue on Win10+Chrome

![img_4529](https://cloud.githubusercontent.com/assets/14044235/15666010/a13c5802-270e-11e6-826d-477724e0f015.JPG)

**Comment by peterpeerdeman** [comment]
the fix fixes all of the issues mentioned except for the last one, which is a (currently) harmless deprication warning for which we should create a separate github issue to fix this later @ralphboeije

**Comment by ralphboeije** [comment]
Great, and will create the issue for the deprecation
