### ISSUE TITLE
Add the mongol and the jetsetter packages to the develop branch

### ISSUE THREAD

**Issue by AnnotatedJS** [part-up/part-up#472]
To make development easier.

https://atmospherejs.com/msavin/mongol
With Mongol, you can view and edit any client document right in the browser. And because Mongol is a debugOnly package, it does not compile to your production build.

https://atmospherejs.com/msavin/jetsetter
With JetSetter, you can view and edit your Session data right in the browser. And because JetSetter is a debugOnly package, it does not compile to your production build.

Another option is to buy http://meteor.toys/ which includes mongol and jetsetter

**Comment by ralphboeije** [comment]
Is this still relevant?

**Comment by AnnotatedJS** [comment]
It can be relevant for development in local environment but we also learned that a branch with mongol does not work in the staging environment.

Therefore we can close this issue.
