### ISSUE TITLE
Improve stopped supporting copy

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#478]
When you click on stop supporting on a part-up, the updates reads: "became supporter": https://uploads.intercomcdn.com/i/o/6922210/885179d81f3b9ea5cb68fa5c/Schermafbeelding%25202016-06-02%2520om%252015.19.03.png

**Comment by prik** [comment]
How it works now is that the 'stopped supporting' message is being displayed as a system message in the 'became supporter' update:

![screen shot 2016-06-16 at 17 20 52](https://cloud.githubusercontent.com/assets/510222/16122478/8c69fa02-33e7-11e6-9f97-575053013a33.png)
So we have 3 options: 
- leave it like this;
- update the title of the update to a 'stopped supporting' title, and don't post a system message anymore;
- let the 'became supporter' update as it is, and create a new 'stopped supporting' update.

Problem with the 2nd one is that there is a possibility that someone becomes a supporter, a partner replies with 'nice!', the supporter clicks 'stop supporting', and then you have an update that says 'stopped supporting' with a reply saying 'nice!'. 

Your call @ralphboeije ;)

**Comment by wouterd** [comment]
Are becoming a supporter and stopping being a support not two separate events that are registered?

**Comment by prik** [comment]
Yes, but they currently act on the same update.
I'll create a new update for the 'stopped supporting' event.
