### ISSUE TITLE
Fix mention issues

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#479]
When you want to mention an upper with a short name (e.g. in screenshot is "Di") you can't find them in the mention list.

<img width="1440" alt="screen shot 2016-06-02 at 15 24 27" src="https://cloud.githubusercontent.com/assets/14044235/15746268/1cfa6f9c-28d6-11e6-9d6c-ce5f5530411f.png">

**Comment by ralphboeije** [comment]
And when you mention someone with three words in their username you can't find them after entering the space after the second word, e.g. "Eva de ". See screenshot. 

<img width="1440" alt="screen shot 2016-06-02 at 15 28 19" src="https://cloud.githubusercontent.com/assets/14044235/15760269/a95a2284-2912-11e6-9952-a9db3e2d4eff.png">

**Comment by andreleon** [comment]
Fixed in commit 211c4021ebcc33e3699bb3da8ba2eaba6110b386

**Comment by peterpeerdeman** [comment]
re-opened this issue, because the fix caused other errors (see #519)
