### ISSUE TITLE
[UX] On the discover page it is hard to get to the footer part of the page

### ISSUE THREAD

**Issue by AnnotatedJS** [part-up/part-up#480]
The discover part has an automatic show more part-up feature. Great, unless one want to see the footer part, for instance to click the About link. In that case a user has to click PageDown button (or a similar action with the mouse) several times until all 'selected' part-ups are shown.

**Comment by ralphboeije** [comment]
We know, that's why we are getting rid of the footer altogether and create a new header with a menu instead.
