### ISSUE TITLE
[DX] Some links in the footer point directly to https://part-up.com/..... 

### ISSUE THREAD

**Issue by AnnotatedJS** [part-up/part-up#481]
[Developer Experience] 
The links 'about' and 'pricing' in the footer point to https://part-up.com/..... using the i18n language feature.
Not direct an issue for end users but less attractive for developers because it takes one out of the staging environment.

**Comment by ralphboeije** [comment]
@AnnotatedJS I don't get the point, a lot of of keys are in the PhraseApp translation. @tlimpanont do you know why it could be an issue on staging?

**Comment by AnnotatedJS** [comment]
@ralphboeije To answer your question, the url for the about page in the footer is coded as a blaze template, as follows: href="{{_ 'footer-menu-company-about-url' }}"
In the phraseapp you will find: "footer-menu-company-about-url": "https://part-up.com/about", with the "part-up.com"hard coded. If you are testing in a staging environment that part should be for instance, develop.staging.part-up.com/¨.

**Comment by ralphboeije** [comment]
don't think this is relevant enough to put in some effort
