### ISSUE TITLE
translation key {NL-pages-app-notfound-backbutton} is missing

### ISSUE THREAD

**Issue by tlimpanont** [part-up/part-up#482]
![screen shot 2016-06-06 at 17 05 10](https://cloud.githubusercontent.com/assets/617876/15826701/df5dac72-2c08-11e6-8dde-34a80b508a19.png)

**Comment by tlimpanont** [comment]
@ralphboeije does this exist in phraseapp?

**Comment by ralphboeije** [comment]
yes it does now, so what are the others to translate?
