### ISSUE TITLE
Link to English language landingpage from English landing homepage

### ISSUE THREAD

**Issue by andyhoek** [part-up/part-up#483]
The English language landingpage for organisations is almost finished, final todo's will be done today. Please link the 'Part-up for Organisations' links to http://transitie.part-up.com/organisations-en

**Comment by tlimpanont** [comment]
@andyhoek are you maintaining this transition website? Can we discussed about the language switcher param. I would like to have like this http://transitie.part-up.com/?lang=nl

**Comment by ralphboeije** [comment]
Fixed this in the copy on Phraseapp as we have seperate keys per language.

**Comment by andyhoek** [comment]
@tlimpanont fyi, these landingpages are hosted on Instapage which doesn't support language switching. @ralphboeije thnx!
