### ISSUE TITLE
Date field not working on iPad and iPhone

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#485]
When using an iPad, an upper can't activate the date field. Even checked for pop-up blocker and other strange settings, but it simply does not work.

![ipad bug date field](https://cloud.githubusercontent.com/assets/14044235/15857264/bd10cab6-2cba-11e6-8d78-ab73b1046ff6.jpg)

**Comment by jplattel** [comment]
Maybe it's a click event instead of touch?
Op di 7 jun. 2016 om 14:20 schreef Ralph Boeije <notifications@github.com>

**Comment by ralphboeije** [comment]
Also an issue on the iPhone

**Comment by ralphboeije** [comment]
duplicate #221
