### ISSUE TITLE
Copy paste of text to about page of tribe doesn't work properly

### ISSUE THREAD

**Issue by eriksoon** [part-up/part-up#486]
When writing the text for the about page I used Google Docs with it's own format. I then copy paste the text to the about page of the tribe. When using normal copy paste the text first appears in Times new roman style, but then isn't published when clicking the save button. When pasting unformatted the bullets (which were added through the text editor on the about page) were not coming trough.

MS10, Chrome

**Comment by ralphboeije** [comment]
@eriksoon which tribe is this? Did you first strip all formatting in the editor before trying the second time?

**Comment by eriksoon** [comment]
The customer cocreation tribe. No i did not strip all formatting. I simply copied paste by clicking the mouse (right button) and selecting unformatted paste.

**Comment by ralphboeije** [comment]
It works fine as long as you paste unformatted. It's like this with most online cms.
