### ISSUE TITLE
Windows phone doesn't load part-up at all

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#49]
Windows 10 mobile + Edge (RTM)

**Comment by AnnotatedJS** [comment]
Part-up works on my Windows Phone, homepage, login, etc.

**Comment by andreleon** [comment]
@ralphboeije I have tried to load partup in an **emulation** environment, and it seems to work. I wonder if this is still an issue..?

**Comment by ralphboeije** [comment]
Can't reproduce this either. Probably fixed in the mean time.
