### ISSUE TITLE
Migrate "Footer" to "Menu"

### ISSUE THREAD

**Issue by peterpeerdeman** [part-up/part-up#495]
as designed in https://redpen.io/occ86c7e3ef15ba212

**Comment by wouterd** [comment]
Make sure you keep the semantics in HTML for SEO. So it should be footerish in HTML.

**Comment by ralphboeije** [comment]
Request by Andy hoek: Can we have in link in the footer that links to https://blog.part-up.com/app for the iOS and Android apps? With the text 'Apps for iOS & Android' or 'iOS/Android Apps'.

**Comment by ralphboeije** [comment]
@tlimpanont has added the apps to the more @andyhoek
