### ISSUE TITLE
Check partupAutolink occurrences for cross-site scripting

### ISSUE THREAD

**Issue by peterpeerdeman** [part-up/part-up#496]
the partupAutolink global helper is used in the following cases. We must ensure that all content fed to these global helpers is htmlsanitized before rendering

app/packages/partup:client-base/helpers/autolink.js|2 col 26| 
app/packages/partup:client-comments/Comments.html|79 col 102|
app/packages/partup:client-comments/Comments.html|82 col 49| 
app/packages/partup:client-network-chat/ChatMessage.html|11 col 28| 
app/packages/partup:client-pages/app/partup/activities/activity/view/view.html
app/packages/partup:client-pages/app/partup/partup-sidebar.html|23 col 96|
app/packages/partup:client-update/types/description-changed.html|3 col 107|
app/packages/partup:client-update/types/message-added.html|16 col 41|

**Comment by andreleon** [comment]
I checked all mentioned files, i also tested each of these instances. They are all safe.
