### ISSUE TITLE
Click trough on profile to LinkedIn doesn't work

### ISSUE THREAD

**Issue by eriksoon** [part-up/part-up#497]
When visiting a profile page and clicking the linkedin profile the link often doesn't work. I tried so with the profile of Arielle https://part-up.com/profile/bDbomJBC5itPpsRjs and Sladjana https://part-up.com/profile/43QmWbcJ4SwX5Lupa

I then get this message:
![image](https://cloud.githubusercontent.com/assets/18055074/16021308/37be8e6e-31b2-11e6-8056-1c6d40bdf797.png)

Windows 10, Chrome

**Comment by ralphboeije** [comment]
I know, they have pasted the wrong url: https://linkedin.com/profile/view?id=hVDF76zJ1y. This is a personal url, and will never work if you share this online.
