### ISSUE TITLE
Irregular appearance of the user name and icon in tribe chat

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#501]
If a user adds a text and clicks send, the new chat is added with a user name and user icon. When you type another text and click send right after, the new text is added as a follow up chat message. However, this sometimes does not happen and there are two user names behind each other which is a waste of vertical screen estate.

Suggestion: only show the user name+icon again if the time difference between the new message and the last is more than 2 minutes.

<img width="1440" alt="irregular appearance of user name and icon" src="https://cloud.githubusercontent.com/assets/14044235/16058750/3502adbc-3280-11e6-8279-f7a9b9f2855f.png">

**Comment by andreleon** [comment]
@ralphboeije it was 20 seconds, now it is 2 minutes
