### ISSUE TITLE
New messages not showing correctly

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#506]
The new messages bar is showing when there are new messages not in view. However, the bar keeps appearing falsely after a scroll up and down after you have seen the latest new chat already for some time.

<img width="1440" alt="screen shot 2016-06-14 at 23 20 14" src="https://cloud.githubusercontent.com/assets/14044235/16060199/de103702-3286-11e6-9038-157775b8c05f.png">

**Comment by andreleon** [comment]
I cannot reproduce this issue in the ft-1-on-1-chat branch. This could have something to do with my recent fixes in this branch.
