### ISSUE TITLE
Tribe chat on mobile rendering issues

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#513]
See screenshot. Findings:
- Chat window runs over footer
- Pinch and zoom not working anymore

![img_4579](https://cloud.githubusercontent.com/assets/14044235/16097672/4f85985a-334f-11e6-870a-18ac998962d1.PNG)

**Comment by andreleon** [comment]
In the 1-on-1 chat branch the footer is removed, so this issue is automatically fixed
