### ISSUE TITLE
Chat dropdown should only show one line of the last chat

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#517]
Currently the entire last message of the chat is shown in the dropdown. This takes quite some screen estate. Better cut it of at one line in the dropdown and add ... at the end.

<img width="1440" alt="screen shot 2016-06-16 at 09 08 42" src="https://cloud.githubusercontent.com/assets/14044235/16108460/84029a02-33a3-11e6-981b-dd129bb56477.png">

**Comment by ralphboeije** [comment]
To stress this point, see screenshot when having 3 tribes with tribe chat
<img width="1440" alt="screen shot 2016-06-16 at 12 20 15" src="https://cloud.githubusercontent.com/assets/14044235/16115277/55c38d22-33c6-11e6-8358-a59811d1d853.png">

**Comment by tlimpanont** [comment]
@peterpeerdeman if you can mange to fix this, i planned to release this evening thanks!
