### ISSUE TITLE
@mention fix has killed multiple @mentions in a comment or post

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#519]
See sreenshot. To reproduce:
1. Type 1 @mention in a comment or post and see that it works fine
2. Try to add another @mention in the same comment or post
3. See that you can only find the users that were suggested before selecting the first @mention 
4. Erase the first @mention and try to add a new @mention 
5. See that you can only find the users that were suggested before selecting the first @mention 

<img width="1440" alt="screen shot 2016-06-16 at 11 51 25" src="https://cloud.githubusercontent.com/assets/14044235/16112711/ea51a888-33b8-11e6-865d-09e880293578.png">

**Comment by ralphboeije** [comment]
Hi @andreleon just did some extra testing on this one. Seems to work in Safari (both iOS and Mac), but not on Chrome and FF, didn't have the chance yet of testing it on Windows browsers.

**Comment by AnnotatedJS** [comment]
@andreleon @ralphboeije I have tested on Windows 8.1 IE and there the same error occurs.

**Comment by andreleon** [comment]
@ralphboeije I reverted the commit that made 3 word mentions possible. This is a quick fix to allow multiple mentions again.

**Comment by ralphboeije** [comment]
Ah, no prettier solution today @andreleon ?

**Comment by ralphboeije** [comment]
related to #479

**Comment by peterpeerdeman** [comment]
closing this issue because the fix was reverted. please continue discussion in #479
