### ISSUE TITLE
Part-up picture not loaded in FB share

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#52]
![pic](https://cloud.githubusercontent.com/assets/14044235/11169715/f821b5b2-8bbf-11e5-8e78-292706f55ba3.png)

**Comment by andreleon** [comment]
The image does load on production, so I think this isn't an issue seeing as you tested it on acceptance.

It isn't strange that something like this won't work on a test environment.

![screen shot 2016-03-03 at 14 20 20](https://cloud.githubusercontent.com/assets/1391492/13495459/2a93bb72-e14b-11e5-8f70-4dcd6fb4461e.png)
