### ISSUE TITLE
Remove the invitation sentence to improve one's profile

### ISSUE THREAD

**Issue by AnnotatedJS** [part-up/part-up#523]
Remove the invitation sentence to improve one's profile and associated code.

![part-up - discover 2016-06-16 13-53-02](https://cloud.githubusercontent.com/assets/11474975/16118803/05425316-33d9-11e6-8bd6-f6d69c7ce793.png)

Related with issue #324

**Comment by tlimpanont** [comment]
@AnnotatedJS nothing fancy i see. only removal codes. I will merge it for you. Thanks!

**Comment by AnnotatedJS** [comment]
And thank you!
