### ISSUE TITLE
Modal doesn't close

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#535]
See screenshot for error. Happens irregularly, but have seen it on several occasions. In this case I edited the part-up settings and changed the date and location.

<img width="1440" alt="screen shot 2016-06-22 at 13 54 24" src="https://cloud.githubusercontent.com/assets/14044235/16265817/bf390010-3881-11e6-9049-275f471b64cc.png">

**Comment by AnnotatedJS** [comment]
Is this issue related to #488 Closing of modal does not work in situation where another modal is called before/by this modal ?

**Comment by ralphboeije** [comment]
no, this was in logged in state.

**Comment by andreleon** [comment]
These links are related to the issue:

[Chrome 51 error: The basic HTML.TransformingVisitor does not support foreign objects in attributes](https://forums.meteor.com/t/chrome-51-error-the-basic-html-transformingvisitor-does-not-support-foreign-objects-in-attributes/23961/3)

[[Chrome 51] HTML.TransformingVisitor does not support foreign objects in attributes](https://github.com/meteor/meteor/issues/6793#issuecomment-227606218)

It has something to do with our version of Iron-Router

**Comment by ralphboeije** [comment]
Do you know if it is fixed in 52?

**Comment by ralphboeije** [comment]
not an issue anymore
