### ISSUE TITLE
Unable to differentiate between 1-on-1 chats and tribe chats

### ISSUE THREAD

**Issue by jplattel** [part-up/part-up#538]
With the current schema that we have it is hard to differentiate between tribe-chats and 1-on-1 chats. The only way to do this currently is to look at the chatmessages and see if it has multiple readers... 

Easy way to fix is add an network_id (from the tribe) to the chat model if it is a tribe chat.

**Comment by peterpeerdeman** [comment]
@jplattel you can lookup the tribe that has a chat_id corresponding to the chat object you are looking at. If that tribe exists, it's a tribe chat. If it doesn't exist it is a personal chat right?
