### ISSUE TITLE
At chat C2A to user profile (and to profile card)

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#545]
As an upper I want to start a personal chat from the user profile.

To be designed: 
- action button preferably close to the user profile pic on user profile
- action button on profile card (requires profile card to remain displayed if you hoover towards it, because now it disappears before you get there) - NB: including the uppers tab on tribe and partners tab on user profile.

**Comment by peterpeerdeman** [comment]
resolved in #ffa2b5450c02b6f82d4011fc011cbd880331ab0e
