### ISSUE TITLE
GoogleDrive have some delay with loading the JS 

### ISSUE THREAD

**Issue by tlimpanont** [part-up/part-up#550]

**Comment by tlimpanont** [comment]
please check whether we need to load the script in up front

**Comment by ralphboeije** [comment]
Invalid 'X-Frame-Options' header encountered when loading 'https://docs.google.com/picker?protocol=gadgets&origin=https%3A%2F%2Fpart-u…docs%22%7D))&rpctoken=4v30rswqkok8&rpcService=lwuzvnch6efs&thirdParty=true': 'ALLOW-FROM https://part-up.com' is not a recognized directive. The header will be ignored.
