### ISSUE TITLE
Edit your profile from profile page

### ISSUE THREAD

**Issue by eriksoon** [part-up/part-up#551]
As a user I expect to be able to edit my profile from the profile page. This is currently not possible anymore. It used to be, with the setting wheel (which is gone). To me it makes most sense if I could click an edit button or link in the top of my profile.

![image](https://cloud.githubusercontent.com/assets/18055074/16337782/413235ea-3a18-11e6-9eda-154a694aee3c.png)

**Comment by peterpeerdeman** [comment]
was fixed by @andreleon in a recent commit on the ft-1-on-1-chat branch, thath as recently been merged to develop

**Comment by eriksoon** [comment]
@peterpeerdeman I can't find the possibility? Is it just me, or did you guys hide it somewhere? ;)

**Comment by partupadmin** [comment]
@eriksoon wait for tonight's release :-D

**Comment by eriksoon** [comment]
Cool!
