### ISSUE TITLE
Refactoring column determination for tile components

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#557]

**Comment by AnnotatedJS** [comment]
First step: centralize the column calculations in one Function

Current situation is:

![screenshot from 2016-06-28 12 10 26](https://cloud.githubusercontent.com/assets/11474975/16414893/af53a84a-3d3a-11e6-91ba-b1db90b7c9b2.png)

**Comment by AnnotatedJS** [comment]
- [ ] Add 6 part-ups to Judy for visual testing
- [ ] Tackle the discover page;  create a working function
- [ ] Generalize function
- [ ] Apply function to other pages (see screenshot above)

**Comment by AnnotatedJS** [comment]
Some observations,
a. It is not possible to create local a new part-up; location field gives an error that can be resolved.
b. the last line of tiles, tiles float right
