### ISSUE TITLE
Right column is a bit over the footer

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#56]
![photo](https://cloud.githubusercontent.com/assets/14044235/11169746/8e7e34e0-8bc0-11e5-97c8-bbebeab05f35.png)

**Comment by roberrrt-s** [comment]
This actually gets worse when you try and resize the page, when going from >1000px to ~500px and back, it displays content over the footer

![](https://i.gyazo.com/4796185394aa074518f4d8b4fa1eba76.png)

**Comment by peterpeerdeman** [comment]
putting this (hard to solve) bug on lower prio, as new design is going to replace the bottom footer completely (agree @ralphboeije?)
