### ISSUE TITLE
Mixed content warning in browser

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#562]
On android you now get a 'not safe warning' in the browser. Looking at the js console, I see a mixed content warning (see example below).

chrome-extension://fdjamakpfbbddfjaooikfcpapjohcfmg/content/contentScripts/kwift.CHROME.min.js:1 Mixed Content: The page at 'https://part-up.com/tribes/swarmorganizing/chat' was loaded over HTTPS, but requested an insecure image 'http://www.newworldcampus.nl/wp-content/uploads/logo-nwc.png'. This content should also be served over HTTPS.

**Comment by peterpeerdeman** [comment]
hi @ralphboeije, this problem occurs when users add images to their page that are hosted without https (e.g. http://blabla.com/image.jpg) to our https environment. There is not really anything we can do about this, other than asking users to host their external pictures on a https domain, or that we forbid including images from http environments altogether. The latter would result in an extra validation and an error message when trying to submit the form.
