### ISSUE TITLE
Fix copy below chat search private tribe

### ISSUE THREAD

**Issue by tlimpanont** [part-up/part-up#566]
<img width="1340" alt="screen shot 2016-06-28 at 16 03 25" src="https://cloud.githubusercontent.com/assets/617876/16418446/22248c22-3d4a-11e6-84f1-9157bdbade55.png">

**Comment by tlimpanont** [comment]
it seems this issue is only relevant to PRIVATE tribe

**Comment by ralphboeije** [comment]
duplicate to #537
