### ISSUE TITLE
Show if tribe is open or closed

### ISSUE THREAD

**Issue by eriksoon** [part-up/part-up#567]
As a user I would like to be able to quickly see weather a tribe is open or private. Currently it is only possible to see this on the part-up page (in the lower right corner). Can we use something like an visibility sign or something?

![image](https://cloud.githubusercontent.com/assets/18055074/16418538/8bfa58c0-3d4a-11e6-9ab1-9e7959504bc1.png)

**Comment by ralphboeije** [comment]
fixed in new tribe landing page
