### ISSUE TITLE
Remove rating notification

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#579]
I believe the notification to rate your partners is hardly used, as there are hardly any ratings given. I asked @jplattel to check on this data before this issue is to be planned on a sprint.

**Comment by jplattel** [comment]
Is it currently used by the recommendation engine? Instead of removing it, we might use it as a case to develop some a/b testing etc? 

As for the numbers, the total ratings are 516. 27 in the last month and 16 ratings in the last week.

**Comment by ralphboeije** [comment]
Duplicate to #731 which is solved
