### ISSUE TITLE
Tribe chats not visible in chat dropdown for new and old tribes

### ISSUE THREAD

**Issue by peterpeerdeman** [part-up/part-up#593]
- When a new tribe is created, the accompanying chat should also be created. 
- Furthermore, the chat dropdown publication should also publish tribe chats that do not contain chat messages yet.
- To completely fix this problem, a migration has to be written that creates a tribe chat for all tribes that do not have a tribe chat yet

**Comment by jessedvrs** [comment]
Create chat on network creation: f4efe46e92e9061d26a6e2b366e55fc3871cadeb
Migration for that: c71575fb1a6a2a41fcfe87a7378f1853b7c5a12d
Fixtures for that: 2cf2936d5e988b8c54eb0f3bed5b393052fe1948
Dropdown fix: 1d1912572373b4e11e8665ee42acb96dcdc1f9d5

**Comment by jessedvrs** [comment]
![smiley-world-image-smiley-world-36813158-900-864](https://cloud.githubusercontent.com/assets/5961598/16951360/fd4436ec-4dc4-11e6-87d6-6f3b004edb78.jpg)
