### ISSUE TITLE
After clicking a notification for a new message the part-up page turns blank

### ISSUE THREAD

**Issue by eriksoon** [part-up/part-up#600]
When clicking a 'new message' notification you are directed to the message on the part-up pages. But when loading the page, the message stays blank. (message of theuy)

Windows 10, Chrome

![image](https://cloud.githubusercontent.com/assets/18055074/16873682/15553322-4a95-11e6-91ce-9632becc68f7.png)

**Comment by andreleon** [comment]
It seems the message was deleted, I will implement a fallback placeholder for updates (messages) that have been deleted
