### ISSUE TITLE
Part-up atmosphere packages with : (colon) in folder name caused problems on Windows 

### ISSUE THREAD

**Issue by tlimpanont** [part-up/part-up#602]
@AnnotatedJS I know that the convention is like https://atmospherejs.com/i/publishing. But we really try to be as much cross platform as possible. Read this https://kb.wisc.edu/luwmad/page.php?id=2533

I think we should avoid the : in the folder name. Beside atmosphere is becoming more and more deprecated and we should start using npm module convention.

### name

The most important things in your package.json are the name and version fields. Those are actually required, and your package won't install without them. The name and version together form an identifier that is assumed to be completely unique. Changes to the package should come along with changes to the version.

The name is what your thing is called.

**Some rules:**

The name must be less than or equal to 214 characters. This includes the scope for scoped packages.
The name can't start with a dot or an underscore.
New packages must not have uppercase letters in the name.
The name ends up being part of a URL, an argument on the command line, and a folder name. Therefore, the name can't contain any non-URL-safe characters.

Source: https://docs.npmjs.com/files/package.json

**Comment by AnnotatedJS** [comment]
@tlimpanont I agree. And an added benefit is that it becomes easier for open source contributers to develop for part-up.

Here is a list with characters that are not allowed in windows environment:


Use any character in the current code page for a name, including Unicode characters and characters in the extended character set (128–255), except for the following:

    The following reserved characters:
        < (less than)
        > (greater than)
        : (colon)
        " (double quote)
        / (forward slash)
        \ (backslash)
        | (vertical bar or pipe)
        ? (question mark)
        * (asterisk)
    Integer value zero, sometimes referred to as the ASCII NUL character.
    Characters whose integer representations are in the range from 1 through 31, except for alternate data streams where these characters are allowed. For more information about file streams, see File Streams.
    Any other character that the target file system does not allow.

From https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

**Comment by tlimpanont** [comment]
@AnnotatedJS thanks!
