### ISSUE TITLE
Part-ups on tribe page are not shown

### ISSUE THREAD

**Issue by eriksoon** [part-up/part-up#607]
When coming from a part-up and going to the tribe page (clicking the tribe name on the right column) the part-ups are not shown on the tribe page. After refreshing the page, the part-ups are shown again.

Step 1:
![image](https://cloud.githubusercontent.com/assets/18055074/17137744/1494a7dc-533d-11e6-9b30-c45dc7dd989b.png)

Step 2:
![image](https://cloud.githubusercontent.com/assets/18055074/17137704/dcc266be-533c-11e6-8891-03cf26b77c8c.png)

Windows 10, Chrome

**Comment by ralphboeije** [comment]
@eriksoon do you still experience this issue? Just retested it on mac+chrome and could not reproduce. Can you please be more specific on OS+browser and include the exact steps taken?

**Comment by ralphboeije** [comment]
Just reproduced this issue. The error message is in the screenshot below. 

<img width="1440" alt="screen shot 2016-07-28 at 17 08 44" src="https://cloud.githubusercontent.com/assets/14044235/17217832/0b2c4c90-54e6-11e6-8249-888d7badaac9.png">

**Comment by eriksoon** [comment]
Windows 10 and Chrome
