### ISSUE TITLE
In InPrivate browser, homepage does not load part-ups

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#614]
<img width="1440" alt="screen shot 2016-07-29 at 11 46 18" src="https://cloud.githubusercontent.com/assets/14044235/17244432/14faae28-5582-11e6-9745-2fef22112c0b.png">

**Comment by peterpeerdeman** [comment]
i strongly believe this problem is remediated in the latest release, @ralphboeije please recheck this one when https://github.com/part-up/part-up/pull/631 is pushed to production
