### ISSUE TITLE
When previewing an image it is not possible to zoom

### ISSUE THREAD

**Issue by eriksoon** [part-up/part-up#616]
When you want to preview an image that is shared on the part-up page (in a message), it is not possible to zoom in. When zooming it will only effect the background (browser).

Win 10, Chrome

![image](https://cloud.githubusercontent.com/assets/18055074/17294955/211f9680-57fa-11e6-9a62-afceb4089f77.png)

**Comment by andreleon** [comment]
With a very tall image like that, the image quality will be very bad. Maybe we have to look into changing the image upload settings before we try to fix this issue.

**Comment by ralphboeije** [comment]
Moved this one to all issues because of Leon's feedback. It has to do with the way we treat uploading and viewing of images. Requires more thinking and is not a bug.
