### ISSUE TITLE
Selecting a date in the past kills the date-picker

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#621]
To reproduce:
1. Log in to part-up.com
2. Click start a part-up in the header
3. Scroll down to date picker
4. Click date before today
5. See that the month/year in the header of the datepicker change to "<Month> 0"
6. Try to pick another date and see that it is not possible (grey dates)

Improvement suggestion: disable clicking dates that are in the past

<img width="1440" alt="screen shot 2016-08-04 at 12 28 26" src="https://cloud.githubusercontent.com/assets/14044235/17399028/3b3a945a-5a40-11e6-9780-5647db35d533.png">

**Comment by andreleon** [comment]
@ralphboeije It's actually not disabled after clicking a date in the past, it just takes you to the year 0 somehow.

I will look into it

**Comment by ralphboeije** [comment]
@andreleon just reproduced the bug on acceptance. I know it's an edge case, but nonetheless annoying: when you click between two dates it still directs you to the year 0.

<img width="1440" alt="screen shot 2016-08-15 at 13 25 39" src="https://cloud.githubusercontent.com/assets/14044235/17663302/fe46f39a-62eb-11e6-8195-92b8f97b748d.png">

**Comment by ralphboeije** [comment]
@peterpeerdeman forgot to mention this one in our call just yet.
