### ISSUE TITLE
Chat performance improvement

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#634]
Here I share three screencasts of the current chat performance. This is not good enough, so we need to examine the cause.

https://drive.google.com/file/d/0Byie6itUWBvIR2trUGhFRmRUMjQ/view?usp=sharing
https://drive.google.com/file/d/0Byie6itUWBvIcTEtT3RHTExKWFk/view?usp=sharing
https://drive.google.com/file/d/0Byie6itUWBvILWhyRUJuNmY0NVk/view?usp=sharing

Frontend
- [x] Profile ??repaints?? research
- [x] Profiele meteor methods research
- [x] optimization template helpers
- [x] Latency compensation in FE
- [x] Profile events research

Backend
- [ ] Local production dump
- [ ] Check Kadira for performance improvements (CPU profiler)
- [x] limit data gathering in production

**Comment by Krijger** [comment]
Two occurrences on Ubuntu, Chrome.

https://drive.google.com/file/d/0B357rmgz5N7tTmdaTXJBUzBUSzA/view?usp=sharing
https://drive.google.com/file/d/0B357rmgz5N7tNlZlWXZDRXFNdW8/view?usp=sharing

**Comment by partupadmin** [comment]
related to #582
