### ISSUE TITLE
Duplicate chat messages on tribe chat

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#641]
Frontend
- [x] Trace chatmessage loop (also in disabled linkscraper helper)
- [x] Add E2E test for adding chat message after chat submit

Backend
- [x] Trace chatmessage loop (also in disabled linkscraper helper)
- [x] Add tribe and 1-on-1 chat fixture data

Since last release quite often we see multiple entries of the same message on the tribe chat. See screenshots. Can't reproduce consistently though. First two screenshot show obvious duplicates. Last two screenshot shows two 👍 where I only typed one in the app. In between are messages from other users.

<img width="1440" alt="screen shot 2016-08-22 at 10 55 01" src="https://cloud.githubusercontent.com/assets/14044235/17849030/16fc0b12-6857-11e6-8790-1157992a7179.png">
<img width="1440" alt="screen shot 2016-08-22 at 10 55 34" src="https://cloud.githubusercontent.com/assets/14044235/17849031/16fd4d24-6857-11e6-92f3-2fb5d9fc44ab.png">
<img width="1440" alt="screen shot 2016-08-22 at 10 55 57" src="https://cloud.githubusercontent.com/assets/14044235/17849033/1700d296-6857-11e6-9c9b-9f922f813735.png">
<img width="1440" alt="screen shot 2016-08-22 at 10 56 16" src="https://cloud.githubusercontent.com/assets/14044235/17849032/16ffa344-6857-11e6-88dc-fe5cb43a7c24.png">

**Comment by ralphboeije** [comment]
@peterpeerdeman I can also reproduce it on acceptance with this message:

Hi guys! I've just published a new release blog. Hope you like (and share) it! blog.part-up.com/blogs/release-creeer-cirkels-va.. If you have feedback/comments, please contact me through the personal chat. The English version will be published later today.

Here you see the error:

<img width="1440" alt="screen shot 2016-08-25 at 12 45 59" src="https://cloud.githubusercontent.com/assets/14044235/17966475/035e651a-6ac2-11e6-9874-3497f251bf4d.png">

**Comment by ralphboeije** [comment]
@andreleon too bad, the duplicates are still not completely fixed. See screenshot. @wouterd were you on the app when posting this message?

![img_4926](https://cloud.githubusercontent.com/assets/14044235/18547537/364b36e6-7b44-11e6-892c-83d2637ce309.PNG)

**Comment by wouterd** [comment]
Yes I was in the app on iOS.

**Comment by ralphboeije** [comment]
@tlimpanont I see you added a commit 4 days ago. Is this already on production?

**Comment by ralphboeije** [comment]
Still a bug

<img width="1440" alt="screen shot 2016-09-27 at 08 46 45" src="https://cloud.githubusercontent.com/assets/14044235/18862918/0e8361c0-848f-11e6-9ee7-bf746610d5d7.png">

**Comment by AriellevdLinde** [comment]
<img width="1440" alt="screenshot 2016-10-03 13 13 26" src="https://cloud.githubusercontent.com/assets/22590642/19035698/63978336-896b-11e6-8000-32f1dec55cc4.png">

**Comment by ralphboeije** [comment]
@prik here it is clearly an issue with the links

<img width="1440" alt="screen shot 2016-10-03 at 16 11 24" src="https://cloud.githubusercontent.com/assets/14044235/19040434/55b18dfc-8984-11e6-8229-7c8629de9b96.png">

**Comment by ralphboeije** [comment]
@prik and yet another with quite some time in between

<img width="1440" alt="screen shot 2016-10-04 at 22 58 13" src="https://cloud.githubusercontent.com/assets/14044235/19092233/15be914c-8a86-11e6-9ce5-8c00f44fd9cd.png">

**Comment by ralphboeije** [comment]
@prik just had two occurrences of this yesterday:
- With a link in private chat between me and @wouterd, send from web  (see screen 1)
- With an emoticon in tribe chat send from app https://part-up.com/tribes/development/chat. I only send one 👍 and not two (although it looks quite natural here, see screen 2)

Hope you manage to find and fix the problem here.

<img width="1440" alt="screen shot 2016-10-12 at 10 07 03" src="https://cloud.githubusercontent.com/assets/14044235/19302296/c14f7e44-9063-11e6-9683-993923c17d65.png">

<img width="1440" alt="screen shot 2016-10-12 at 10 09 52" src="https://cloud.githubusercontent.com/assets/14044235/19302389/33cbf4f2-9064-11e6-9a8c-4f330b55266f.png">

**Comment by wouterd** [comment]
It had me fooled on the second screen. 😀

**Comment by peterpeerdeman** [comment]
should be fixed by merging pullrequest #716
