### ISSUE TITLE
Profile page content gone of Who is tab gone

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#642]
Frontend
- [ ] Add e2e test to check if tiles are displayed on the profile page
- [x] Investigate empty profile page "Who is" tab of profile

Backend
- [x] Investigate & fix
- [x] Add fixture data to include content on "Who is tab" of profile

Chat button was first also gone, @tlimpanont restored it in last release.

<img width="1440" alt="screen shot 2016-08-25 at 14 15 20" src="https://cloud.githubusercontent.com/assets/14044235/17968720/9df343b4-6ace-11e6-9620-072e85895f04.png">

**Comment by tlimpanont** [comment]
weird, could't find `pages-app-profile-open-existing-chat` on phraaseapp anymore
