### ISSUE TITLE
Pop-up "Take part" doesn't allow pinch to zoom out

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#66]
iPhone iOS9 Safari
![img_3887](https://cloud.githubusercontent.com/assets/14044235/11183097/11b6112a-8c70-11e5-91c5-54d32e5f8a86.jpg)

**Comment by ralphboeije** [comment]
Won't be needed in new part-up page design.

**Comment by andreleon** [comment]
@ralphboeije Do I need to fix this, or can this issue be closed?

**Comment by ralphboeije** [comment]
please fix it if it is a small thing

**Comment by andreleon** [comment]
@ralphboeije I have tested this on multiple phone sizes in the iOS simulator and also on  my own iPhone 5, It just works fine.
