### ISSUE TITLE
Notifications for personal chat messages not showing on web

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#666]
Hard to reproduce, but it happens regularly (lots of user reports on this one lately) that you don't receive a notification on the web for new personal chats.

**Comment by andreleon** [comment]
I need steps to reproduce this issue. I cannot reproduce this on any environment (local, acceptance or production).

**Comment by ralphboeije** [comment]
That's strange, just send you a personal chat to reproduce this issue on production.

**Comment by ralphboeije** [comment]
Given you don't reply @andreleon I reckon we reproduced it on production?

**Comment by andreleon** [comment]
I have found the problem and passed it on to @prik because it's a back-end issue
