### ISSUE TITLE
Remove spacing after paragraph if it is the last in the message

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#677]
@tlimpanont it's a bit too much now

<img width="781" alt="screen shot 2016-09-15 at 17 03 34" src="https://cloud.githubusercontent.com/assets/14044235/18554986/6a8747e8-7b66-11e6-9cdc-c958af6a8cc4.png">

**Comment by tlimpanont** [comment]
you mean padding top and bottom between text and container?

**Comment by ralphboeije** [comment]
padding top seems ok, padding bottom between text and container is more than it was before you added the padding after a paragraph in 1.21.9
