### ISSUE TITLE
Review the time it takes to have a newly added messages show in the frontend

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#686]
These ones seems to occur quite often when you post a message/fill a form input field. Result is that the mouse click is not recorded in the frontend

 - TypeError: Cannot read property 'autosave' of undefined
 - TypeError: Cannot read property 'off' of undefined
 - See screenshot in second comment for custom_atributes invalid error

**Comment by peterpeerdeman** [comment]
should be fixed by merging pullrequest #716
