### ISSUE TITLE
Clean up global header

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#688]
- FE:
 - Remove "Start a part-up" from global header bar
 - Remove "Discover" from global header bar
 - Remove part-ups/tribes from profile dropdown
 - Restyle profile dropdown to keep settings, profile, logout

NB: don't release this improvement before issues #689 and #690  are ready for release to production.

**Comment by AriellevdLinde** [comment]
@andreleon @ralphboeije 
Designs for the global header (one design for the header, one for the profile dropdown):
![1 cleanup header - clean up](https://cloud.githubusercontent.com/assets/22590642/19042539/b571ed88-898c-11e6-8a8a-acf0ed3cfea8.png)
![2 cleanup header - profile dropdown](https://cloud.githubusercontent.com/assets/22590642/19042538/b5708178-898c-11e6-9572-071e8be4c42e.png)

**Comment by ralphboeije** [comment]
@andreleon please check header design on mobile browsers. Doesn't look right as it has a vertical spacer between left corner and Discover/My tribes and the header items do not all have the same font/size.

Next to that, on logged in state, the homepage scales to half of the screen width.

![img_5094](https://cloud.githubusercontent.com/assets/14044235/19439325/03846fae-947e-11e6-9344-2ca47cc3cc2e.PNG)
