### ISSUE TITLE
Add discover tribes

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#689]
Given I am a viewer of part-up.com
And I see the "My tribes" dropdown opened from the global header bar
When I click the "Discover more tribes" link in the dropdown
Then I am on the discover tribes page
And I can see tribe tiles
And I can search tribes by sector and type

Design:
- Design needed for Discover tribes page
  FE:
  BE:

**Comment by AriellevdLinde** [comment]
@ralphboeije 
What information is needed in the tribe tiles? I already started with an idea of needed information:

- Tribe logo
- Tribe name
- Tribe image
- Intro text
- Tags
- Members
- Nr. of members | Nr. of Part-ups | Last active ?

**Comment by ralphboeije** [comment]
I think this is a great list to start with and I will ask the stakeholders this friday for input.

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon 
I've made the designs for discover. You can find them below with some explanations:

**1.1 Discover tribes:** the lay-out of the discover page changed a bit. Now you can find tabs below the topbar with "Discover by tribes", "Discover by part-ups" and "Recommended for you". Below that you can find the title with the number of tribes and on the right the sort functionality. The filter/search you can now find on the left side of the page. I would suggest to not have anything sticky besides the topbar.

In a tribe tile (or row in this case) you will find the following information: 
- Tribe image
- Tribe logo
- Tribe name
- Nr. of Part-ups | Last active (if this last one is possible, it is connected to the last activity of a part-up within the tribe)
- Intro text
- Tags
- Members and nr. of members
- Needs (needs are collected from the part-ups within the tribe)
![1 1 discover - discover tribes](https://cloud.githubusercontent.com/assets/22590642/19477561/13960fd0-953f-11e6-979c-237733bbea03.png)

**1.2 Discover tribes - needs hover:** when hovering "5 more needs", you will see a layover with all needs listed. Should we also add something like a call to action here? Something like: "Do you think you can add value to this tribe? [   Join the tribe   ]"
![1 2 discover - discover tribes - needs hover](https://cloud.githubusercontent.com/assets/22590642/19477564/139af11c-953f-11e6-8cba-5f22fcb4b07f.png)

**2.1 Discover part-ups:** discover part-ups still has the same tiles, but now with the needs added. The part-up filters are different from tribe filters, but they will also be shown on the left side of the page:
![2 1 discover - discover part-ups](https://cloud.githubusercontent.com/assets/22590642/19477563/139a3b32-953f-11e6-8299-1e1fa118e218.png)

**2.1 Discover part-ups:** the same hover as for the tribe needs:
![2 2 discover - discover part-ups - needs hover](https://cloud.githubusercontent.com/assets/22590642/19477560/13960774-953f-11e6-8499-396454b40fc7.png)

**3.1 Discover - recommended for you:** "recommended for you" doesn't need a filter, therefor there are 4 part-ups on a row:
![3 1 discover - recommended for you](https://cloud.githubusercontent.com/assets/22590642/19477562/1399c35a-953f-11e6-8439-9f1c1798e23b.png)

**3.2 Discover - recommended for you - loading:**
![3 2 discover - recommended for you - loading](https://cloud.githubusercontent.com/assets/22590642/19477565/13ae1224-953f-11e6-81a1-630b61304a0e.png)

**3.2 Discover - recommended for you - no results:**
![3 3 discover - recommended for you - no results](https://cloud.githubusercontent.com/assets/22590642/19477566/13aea572-953f-11e6-83b6-9d7c169bc878.png)

**Comment by ralphboeije** [comment]
@vanderGoes here you can see how we intend to take the recommendations to production. Any feedback from your side?

**Comment by vanderGoes** [comment]
It looks great with the tabs. Love the attractive and clear, but still simple way the tribes are presented btw.

Suggestions for copy:
"We are searching selected part-ups for you to discover" -> "We are loading the selected part-ups for you to discover"
"Sorry, your selected part-ups can't be loaded this time" -> "Sorry, there are currently no recommended part-ups for you. We're analysing your activity to find interesting part-ups quickly. Please try again soon. Meanwhile you can discover already all part-ups."

**Comment by ralphboeije** [comment]
Feedback by stakeholders:
- add by organization to search input
- too many filters (maybe add advanced)

**Comment by ralphboeije** [comment]
@AriellevdLinde forgot about this: #567

**Comment by ralphboeije** [comment]
Have a look @LifelyPim

**Comment by ralphboeije** [comment]
Type is not relevant

Need to show access level icon on tribe tile @AriellevdLinde

**Comment by LifelyPim** [comment]
I see that the background of the subnav the same color is as the body background. Perhaps it's better to make it white. Like your profile page (after scroll) https://part-up.com/profile/suXXzuJe4ModxJjs7

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon 
I've updated the previous screens with the icons and the white background in the subnav.

**Icons:**
[Part-up - Icons closed open.zip](https://github.com/part-up/part-up/files/588961/Part-up.-.Icons.closed.open.zip)

**Comment by ralphboeije** [comment]
copy improvement by Ilan: current needs

**Comment by ralphboeije** [comment]
@andreleon @AriellevdLinde Acceptance test findings:
- Discover should also load tribes and/or part-ups when not logged in
- private tribes should be visible for all users (not the case right now)
- type should list: private/besloten or public/publiek. Now I also see invitation, which is just a sub-type of a private tribe.
- Sector works fine!
- Full text search doesn't work at all, typing a text results in no tribes visible and number of tribes in header still on total number
- Location filter works fine!

<img width="1440" alt="screen shot 2016-12-06 at 13 38 58" src="https://cloud.githubusercontent.com/assets/14044235/20925823/5ee7913e-bbb9-11e6-84a8-3b31280b5150.png">
<img width="1440" alt="screen shot 2016-12-06 at 13 20 27" src="https://cloud.githubusercontent.com/assets/14044235/20925828/63e8f70e-bbb9-11e6-8cb2-6fa0a3d0aeae.png">
