### ISSUE TITLE
Limit type of part-up question options

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#694]
FE:
- Limit type of part-up question to commercial (with budget) / non-commercial (=default)

**Comment by ralphboeije** [comment]
@vanderGoes will this impact the recommender system?

**Comment by vanderGoes** [comment]
Nope not negatively. The algorithm only now uses tags and location. Next to the implicit variable days active (creation date), language and team size (partners). With almost only Dutch and English teams language is a minor factor.

Maybe this move even positively impacts the algorithm as the quality of the limited requested information increases.

Good idea!
