### ISSUE TITLE
Be able to re-invite users to a part-up

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#696]
Given I am a viewer of part-up
And I am on the invite modal of a part-up
When I click "Invited"
Then I see the user tiles of the invited users
And I see if they accepted the invitation
And I see a resend invite link for users that didn't accept the invitation

**Comment by AriellevdLinde** [comment]
@andreleon @ralphboeije 
The first drafts for resend invite can be found below:

**The screen for invite new uppers (with search)**
![1 re-invite users - invite screen](https://cloud.githubusercontent.com/assets/22590642/19090822/788be9ce-8a80-11e6-824f-e1e87b47efe4.png)

![2 re-invite users - pending invites](https://cloud.githubusercontent.com/assets/22590642/19090823/78b0429c-8a80-11e6-8feb-2301f33d2e1c.png)

**Comment by ralphboeije** [comment]
Nice @AriellevdLinde The only issue I see is with the search. In #691 we defined the need to filter on tribes and linked to what we did earlier on https://redpen.io/vp72c2c4d11a7b4ccb.

**Comment by AriellevdLinde** [comment]
@ralphboeije Good point, I've added the search + filter to the "invite new partners" screen. 
Is it needed to also have a search + filter for the screen "pending invites"? I didn't add it here. 

I will upload the improved designs in my previous post.

**Comment by ralphboeije** [comment]
Just gave some last feedback on this design. Arielle will finish it today.

**Comment by AriellevdLinde** [comment]
@ralphboeije I've added the "invite by email" screen

**Comment by andreleon** [comment]
@ralphboeije @AriellevdLinde Can you both check this feature on http://feat-invite-filters.staging.part-up.com/ ?
