### ISSUE TITLE
Be able to re-invite users to a tribe

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#697]
Given I am a viewer of part-up
And I am on the invite modal of a tribe
When I click "Invited"
Then I see the user tiles of the invited users
And I see if they accepted the invitation
And I see a resend invite link for users that didn't accept the invitation

NB: include bulk invited users

**Comment by AriellevdLinde** [comment]
The designs for the (re-)invite users to a tribe:
![1 re-invite users tribe - invite screen](https://cloud.githubusercontent.com/assets/22590642/19263950/19e3f622-8f9f-11e6-89f6-aa0ff78dbe18.png)
![2 re-invite users tribe - pending invites](https://cloud.githubusercontent.com/assets/22590642/19263951/19edb8a6-8f9f-11e6-824d-5ebb73f91223.png)

**Comment by AriellevdLinde** [comment]
@ralphboeije I also finished the tribe version of the (re-)invite users including the "invite by email".

**Comment by andreleon** [comment]
@ralphboeije @AriellevdLinde Can you both check this feature on http://feat-invite-filters.staging.part-up.com/ ?

**Comment by ralphboeije** [comment]
@andreleon works like a charm!
- One visual improvement I see is in the spacing. The goal was to have only one line sentence in the paragraph text above the search and invite. I see that the spacing is now different from the design by @AriellevdLinde. When I manually change it via the console and remove two margins (below paragraph and below search box) it looks a lot better. The result is that the invite button is still than above the fold. As this is the only action button, this is an important one. 

For next sprint: Invited user is still displayed in the recommended list. I think we should remove it on invite and show a "user invited" confirmation in the right bottom corner as we do regularly with error messages and other confirmations.

**Comment by ralphboeije** [comment]
This feedback also holds true for #696 of course

**Comment by andreleon** [comment]
Thanks for the feedback

@ralphboeije I just finished up fixing the styling of the invite modal, it should be deployed on http://feat-invite-filters.staging.part-up.com/  any minute now, when you approve I will create a PR of the feature branch
