### ISSUE TITLE
Turn tribe start page into landing page

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#699]
**Background**
Given I am a user

**Scenarios**
- Show tribe landing page
  - Given I am on a tribe landing page
  - When I scroll down
  - Then I can view text and a video explaining me why I should join
  - And I can click a button to join the tribe
  - And I can view images and names of the tribe ambassadors
  - And I can view a link to start a personal chat with one of the ambassadors
  - And I can view the images of all members of this tribe
  - And I can view a selection of the most active public part-ups in the tribe
- Chat with a tribe ambassador
  - Given I am on a tribe landing page
  - When I click the link to start a personal chat with a tribe ambassador
  - Then the personal chat opens with this ambassador
  - And I can edit the message in the chat input bar
  - And I can send the chat message

**Comment by ralphboeije** [comment]
@AriellevdLinde can you share the design here?

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon 
Design for the tribe onboarding you can find below. At the moment it is half wireframe, half design :)
![1 tribe onboarding - landingspage](https://cloud.githubusercontent.com/assets/22590642/19041988/964e0420-898a-11e6-8347-d6341a31d4cf.png)

**Comment by AriellevdLinde** [comment]
@ralphboeije I've updated the tribe screens in my previous post. Could you let me know if the designs are ok?

**Comment by ralphboeije** [comment]
looking good. I will present it on friday to the stakeholders and will let you know about their feedback.

**Comment by ralphboeije** [comment]
@AriellevdLinde I will put this back on the design sprint backlog for after your holiday as the needs still have to be included here.

**Comment by ralphboeije** [comment]
@AriellevdLinde check this example of a tribe landing page: https://amsterdamsmartcity.com/

**Comment by ralphboeije** [comment]
@AriellevdLinde we were asked by the stakeholders to add the privacy type of the tribe (public/private) here also (next to tribe discover) using an icon if possible.

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon 
I've added the privacy type and needs to the tribe page landing page. You can find the designs in my previous post.

**Comment by AriellevdLinde** [comment]
@ralphboeije Is there still design needed for the tribe landing page?

**Comment by ralphboeije** [comment]
@AriellevdLinde do you know if you already did a responsive design for this one?

**Comment by ralphboeije** [comment]
Responsive design is in zeplin and in issue #788

**Comment by andreleon** [comment]
@AriellevdLinde @ralphboeije I just cant seem to find this version of the tribe page in Zeplin, do I have an out of date version? The responsive version is in zeplin

**Comment by ralphboeije** [comment]
I can't find it either on Zeplin. Just called Arielle to put them on also. She'll do it asap.

**Comment by AriellevdLinde** [comment]
Ze staan op Zeplin onder de tag: #699 - Turn tribe start page into landing page
Groetjes, 

Arielle

----



Arielle van der Linde <https://part-up.com/profile/bDbomJBC5itPpsRjs>
UX Designer
06-53521995 

Part-up <http://www.part-up.com/> | Blog <http://blog.part-up.com/> | Twitter <https://twitter.com/partupcom> | Facebook <http://facebook.com/partupcom> | Linkedin <https://www.linkedin.com/company/part-up>
New World Campus, Den Haag <http://www.newworldcampus.nl/>

**Comment by ralphboeije** [comment]
@andreleon just did a thorough test on staging. Looking great! Here are a few issues (screens below):
- General: 
 - "Lock-icon" is missing to indicate public/private tribes (see design above and in zeplin)
 - tribe landing not visible for non-logged in users
 - remove "read more" that is next to purpose at the top of the landingpage
 - tribe tags and part-up tags point to discover and should go to tribe/partups with search on this tag
 - if I don't have a video, I can't save my landing page. In the first sprint planning we decided it should be able to add an image URL (just as on your personal profile).
 - added a vimeo and a Youtube link to the vide url field, but it still shows the still of the part-up video and on click it turns white and doesn't show the video
 - Chat (All members) field won't store the value. When returning to the form it is empty again
 - When you don't enter a text in on of the title fields it gets flagged as required field, but it is filled on creation of the landingpage, so I would rather leave the copy as is on creation, when no new copy is entered in the respective fields
 - When clicking a menu item and scrolling back up to top, that menu item has no on-click result anymore

- Mobile (tested on safari): 
 - bullets have weird emoji instead of bullet
 - you can scroll to the right outside of the page view (maybe has to do with the menu scroll?)

![schermafbeelding 2017-04-19 om 20 27 11](https://cloud.githubusercontent.com/assets/14044235/25195684/b096f918-253e-11e7-805a-786e553b96ba.png)

![schermafbeelding 2017-04-19 om 20 27 50](https://cloud.githubusercontent.com/assets/14044235/25195683/b095ed3e-253e-11e7-8868-8482a214f630.png)

![schermafbeelding 2017-04-19 om 20 41 06](https://cloud.githubusercontent.com/assets/14044235/25196312/95b97196-2540-11e7-9431-f78247b946e0.png)

![img_5694](https://cloud.githubusercontent.com/assets/14044235/25195310/8b9bb12c-253d-11e7-8575-ec757ace02da.PNG)

![img_5694](https://cloud.githubusercontent.com/assets/14044235/25195320/906d0bd8-253d-11e7-92cb-918eafca4c16.PNG)

**Comment by ralphboeije** [comment]
Great work @andreleon ! One new finding on ios/safari appeared:
- [ ] Instagram icon on next line: https://feat-tribe-landingpage.staging.part-up.com/tribes/lifely-open?show=true

As a last improvement, it would be great if the still of the video could be changed from the current Part-up animation still to preferably the youtube or vimeo still, or else to the first frame of the video.

I just remembered that the open tick-box item in my previous comment on tags is probably related to this backlog item: #780 So if there is a time constraint, let's leave this one for now and add it to that issue.

If the two issues (insta and still) are done, you can create a PR that @noelheesen and @jplattel  will review.

**Comment by ralphboeije** [comment]
@andreleon this is the link to a file with the copy updates for this branches z-files: https://docs.google.com/document/d/1lYzHl8EJxY6Au6xpPOpg3UN8YHbISkjwjxjkVlqr91Q/edit?usp=sharing

**Comment by andreleon** [comment]
@ralphboeije The translations are incomplete

**Comment by ralphboeije** [comment]
@noelheesen I added the missing keys to the file listed above. Maybe quicker to copy paste and commit instead of doing it all through Phraseapp in this case.
