### ISSUE TITLE
Recommendations page should tell you it's loading

### ISSUE THREAD

**Issue by wouterd** [part-up/part-up#708]
Now, when loading recommendations, Part-up tells you there's no recommended partups for you. That not true, it simply doesn't know yet and is asking.

**Comment by AriellevdLinde** [comment]
@ralphboeije @wouterd 
I've made a design where you can see the recommendations are loading (copy not final), with just a simple loader that is used on different pages of part-up.

![1 recommendations - loading](https://cloud.githubusercontent.com/assets/22590642/19467571/2431f46c-9512-11e6-934c-89238cab3101.png)
