### ISSUE TITLE
Recommendations should tell the user if recommendations can't be loaded

### ISSUE THREAD

**Issue by wouterd** [part-up/part-up#709]
(Parts of) the API can be unavailable and as such, recommendations can sometimes fail to load.
Now, the page tells me I don't have any recommendations, it should say something like "Sorry, currently recommendations cannot be loaded".

**Comment by AriellevdLinde** [comment]
@ralphboeije @wouterd 
I've made a design for when the recommendations can't be loaded (copy not final):

![1 recommendations - no results](https://cloud.githubusercontent.com/assets/22590642/19467871/f3a74d9a-9513-11e6-8058-a07f912ae738.png)
