### ISSUE TITLE
Hide notification bulb on chat menu item after first click

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#712]
This makes the experience coherent with the notification bulb on the notifications menu item.

Given I am a logged in user
And I have one or more tribe and/or personal chats that I did not view before
And I see the orange notification bulb dancing
When I click "Chats" in the header to open the chats dropdown
Then the the orange notification bulb should disappear until the next new chat comes in

**Comment by noelheesen** [comment]
I am currently working on this and have found a solution. Although it works, I'm still not satisfied by the amount of calls made to update the variable containing the information on whether to show or hide the bulb. I will try to reduce these calls before pushing.

**Comment by noelheesen** [comment]
It took a while to find out why the build to staging failed, I used syntax not yet supported by uglify.js.

The notification bulb should:
 - Hide when clicked;
 - Show on new message not from self;
    - Except when message is in current active chat;

Tested by logging into 2 users, when a message is received:
- Receiver has chats closed => active;
- Receiver has different chat open => active;
- Receiver has same chat open => inactive;

@ralphboeije It has finally built on staging, https://fix-notification-bulb.staging.part-up.com

**Comment by ralphboeije** [comment]
Tested and approved. Great work! You can do a PR and merge it. I can't provide you with a four-eyes on the code though, maybe @jplattel can review the PR?

Discover a new finding though, not related to the bulb. The blue divider line with the new messages text is not working correctly. Findings:
- When you come to the private chat from a notification it doens't show
- When you are on the chat and a new message is added, it shows the line also for your own messages, which is unnecessary
- When you are on the chat and the other person adds one message and later another, without you viewing it, it only shows the divider line before the last message, not the last message you viewed (maybe it is hard to track what you haven't viewed, but this would be the ideal situation).

**Comment by noelheesen** [comment]
@ralphboeije I'm not sure I understand, lets talk it through tomorrow.
