### ISSUE TITLE
Add documents as tab to in part-up navigation

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#720]
Given I am a visitor or logged in user
And I am on a part-up
When I click "Documents & links" in the in-part-up navigation
Then I see the timeline filtered on messages that have attachments and/or links

**Comment by ralphboeije** [comment]
@AriellevdLinde related to #710 you are working on right now.

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon 
I've added the document tab:
![v1 1 in-part-up navigation - overview - breadcrumb](https://cloud.githubusercontent.com/assets/22590642/19480781/fa036d08-954b-11e6-82c8-0c953289e51e.png)

**Icon:**
[Icon_documents.zip](https://github.com/part-up/part-up/files/536454/Icon_documents.zip)
