### ISSUE TITLE
Redesign public homepage (not logged in state)

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#724]
Problem
- Part-up vision and business proposition are not clearly explained

Solution space
- Complete redesign in co-creation with stakeholders. First action is to organize a brainstorm with them.

**Comment by AriellevdLinde** [comment]
@ralphboeije Here you can find the homepage design. The designs can also be found on Zeplin. The explanation about the tool is not finished yet, but I can finish them January 25th. 

**1.1 Homepage  - not logged in user** 
![724 1 1 homepage not logged in user](https://cloud.githubusercontent.com/assets/22590642/21358999/f892dba0-c6da-11e6-8a92-552c79dbb5f7.png)

**1.2 Homepage  - not logged in user - Wat is part-up unfolded** 
![724 1 2 homepage not logged in user](https://cloud.githubusercontent.com/assets/22590642/21359001/f8986142-c6da-11e6-9320-e5d2d7b8f001.png)

**1.2 scroll topbar - Homepage  - not logged in user - Wat is part-up unfolded** 
![724 1 2 scroll homepage not logged in user](https://cloud.githubusercontent.com/assets/22590642/21359000/f8974276-c6da-11e6-8f49-d55c6f6c2232.png)

**1.2B Homepage  - not logged in user - Wat is part-up unfolded - Solutions next to each other** 
![724 1 2b homepage not logged in user](https://cloud.githubusercontent.com/assets/22590642/21359002/f898f4ae-c6da-11e6-896a-326640e5e124.png)

**Comment by ralphboeije** [comment]
To Do:
- responsiveness
- Remove copyright from footer and add links to terms of use and privacy policy (terms.part-up.com and privacy.part-up.com)

**Comment by ralphboeije** [comment]
- check with andy about where form leads
- good luck with the horizontal form and responsiveness @AriellevdLinde ;-)

**Comment by AriellevdLinde** [comment]
Below you can find the Homepage (responsive design) + all images for the slider. All screens can also be found in Zeplin, where you can download the images. 

![724 1 iphone 375px - homepage not logged in user](https://cloud.githubusercontent.com/assets/22590642/22295827/9066b394-e318-11e6-9b50-78822e3bda52.png)
![724 1 1 homepage not logged in user](https://cloud.githubusercontent.com/assets/22590642/22295826/90619b2a-e318-11e6-8141-b544dbeeeb1a.png)
![724 1 1 ipad 768px - homepage not logged in user](https://cloud.githubusercontent.com/assets/22590642/22295824/9058f574-e318-11e6-8905-8ecd203b5796.png)
![724 1 1 ipad 768px - homepage not logged in user](https://cloud.githubusercontent.com/assets/22590642/22295823/90558c54-e318-11e6-95ac-d2b91aa82cb8.png)
![724 1 2 homepage not logged in user](https://cloud.githubusercontent.com/assets/22590642/22295825/906058d2-e318-11e6-97f6-e459ec6c881d.png)
![724 1 2 ipad 768px - 1 2 homepage not logged in user](https://cloud.githubusercontent.com/assets/22590642/22295828/90682d0a-e318-11e6-8247-f8bd8c3c2171.png)
![724 1 2 iphone 375px - 1 2 homepage not logged in user](https://cloud.githubusercontent.com/assets/22590642/22295829/9078b3c8-e318-11e6-81e5-58a7b042540c.png)
![724 1 2 scroll homepage not logged in user](https://cloud.githubusercontent.com/assets/22590642/22295832/9088f5e4-e318-11e6-91ae-3f0c3255ee72.png)
![724 1 2 scroll ipad 768px - 1 2 homepage not logged in user](https://cloud.githubusercontent.com/assets/22590642/22295830/907ee3d8-e318-11e6-9b75-990e53d7bf41.png)
![724 1 2 scroll iphone 375px - 1 2 homepage not logged in user](https://cloud.githubusercontent.com/assets/22590642/22295833/90a97602-e318-11e6-939d-7d577b4c00d5.png)
![724 part-up tool sliders](https://cloud.githubusercontent.com/assets/22590642/22295831/907fdd74-e318-11e6-9d19-c1d2b6b4c590.png)

**Comment by andreleon** [comment]
@AriellevdLinde heb je die carousel afbeeldingen los voor mij? Dan kan ik ze integreren

**Comment by AriellevdLinde** [comment]
Ja deze staan ook in Zeplin! Je kunt ze daar downloaden.
Groetjes, 

Arielle

----



Arielle van der Linde <https://part-up.com/profile/bDbomJBC5itPpsRjs>
UX Designer
06-53521995 

Part-up <http://www.part-up.com/> | Blog <http://blog.part-up.com/> | Twitter <https://twitter.com/partupcom> | Facebook <http://facebook.com/partupcom> | Linkedin <https://www.linkedin.com/company/part-up>
New World Campus, Den Haag <http://www.newworldcampus.nl/>

**Comment by andreleon** [comment]
@AriellevdLinde het lukt me niet om de afbeelding in z'n geheel te downloaden

**Comment by andreleon** [comment]
@AriellevdLinde sorry, het is al gelukt 😅

**Comment by AriellevdLinde** [comment]
Dat is raar, ik heb het gisteren getest en dat ging prima. Ik kan er nu helaas niet naar kijken, aangezien ik bij een andere opdrachtgever werkzaam ben. Lukt het ook niet in het overzicht van de verschillende sliders?
Groetjes, 

Arielle

----



Arielle van der Linde <https://part-up.com/profile/bDbomJBC5itPpsRjs>
UX Designer
06-53521995 

Part-up <http://www.part-up.com/> | Blog <http://blog.part-up.com/> | Twitter <https://twitter.com/partupcom> | Facebook <http://facebook.com/partupcom> | Linkedin <https://www.linkedin.com/company/part-up>
New World Campus, Den Haag <http://www.newworldcampus.nl/>

**Comment by AriellevdLinde** [comment]
Mooi!
Groetjes, 

Arielle

----



Arielle van der Linde <https://part-up.com/profile/bDbomJBC5itPpsRjs>
UX Designer
06-53521995 

Part-up <http://www.part-up.com/> | Blog <http://blog.part-up.com/> | Twitter <https://twitter.com/partupcom> | Facebook <http://facebook.com/partupcom> | Linkedin <https://www.linkedin.com/company/part-up>
New World Campus, Den Haag <http://www.newworldcampus.nl/>

**Comment by andreleon** [comment]
@ralphboeije De laatste versie van de homepage staat op https://ft-homepage-redesign.staging.part-up.com

Ik heb alle translation keys geimplementeerd, dus je kan met phraseapp alle content erin zetten

**Comment by ralphboeije** [comment]
Cool @andreleon I just had a look and I am very pleased! I have some findings. 
- @AriellevdLinde I think you meant the scroll down to also be possible and trigger the same animation as clicking the What is Part-up button?
- Header buttons not logged in should match design (only What is Part-up?, Discover, and Login. No More on homepage)
- Title should be on one line (on my screen it isn't)
- Find a community button should link to discover tribes
- Last line of footer should contain terms of use and privacy policy links instead of copyright (check latest designs)
- Animation on click of What is Part-up button is a bit abrupt and not really smooth
- Animation of feature slider is also a bit off. Text seems to fade in from the right, but image just appears? Maybe take more time for the fade in?
- Feature slider should return to first image after reaching the end (endless), both in automatic and in manual slider mode
- When entering the emailadres, typing "Return" on keyboard should also trigger the sign up button action
- @AriellevdLinde I see that we have used the wrong image in the Chat feature mobile app view (dutch and not the text about the language picker)
- On mobile (safari) the What is Part-up content block doesn't show before you click the button
- On mobile the footer doesn't have the two column view of the latest designs
- @AriellevdLinde on mobile the grey "Oplossing 1" text is a bit squeezed in between the image and the title. Might it be better to put it on top of the image? What do you think?
- On mobile the titles of the "Oplossingen" should have a smaller font I think to fit on one line?

PS: can you implement the language picker of #817 here also?

**Comment by ralphboeije** [comment]
@andreleon I have set the copy in Phraseapp, @wouterd will pull it to the branch such that we can see it live on staging soon.

**Comment by andreleon** [comment]
- Animation of feature slider is also a bit off. Text seems to fade in from the right, but image just appears? Maybe take more time for the fade in?

@ralphboeije since every image has identical layout, I chose not to animate the position (too much movement and also meaningless). The direction in which the text animates indicates the direction in which you move through the pages of the carousel (which are also indicated by the dots).

**Comment by ralphboeije** [comment]
@AriellevdLinde could you have a quick look at it this weekend and share your ideas from a design perspective?

**Comment by andreleon** [comment]
@ralphboeije I still need to know where the "Start a community" segment should lead.

Also the form (at the bottom) still needs to store the data somewhere. If you submit now, it will log the content. (partup-client-pages/app/home/blocks/Home_Form.js)

**Comment by ralphboeije** [comment]
@andreleon I found that the logged in state shows a blue circle around both the orange notification bulb and around the profile image. This is something I noticed after the responsiveness redesign, but now shows up badly in the new design. Could they be removed please? 

PS: will get back to you soon on the form and segment button end points

<img width="1440" alt="screen shot 2017-01-30 at 10 46 59" src="https://cloud.githubusercontent.com/assets/14044235/22418527/b40dd16e-e6d9-11e6-8260-b6fd2cf1f3b9.png">

**Comment by ralphboeije** [comment]
Hi @andreleon like we just discussed, we would like to have the pages-app-home-footer-help link to open the intercom message. @peterpeerdeman shared that this is the way to do it. There is a way to control the intercom message using Javascript: if you create an `<a>` with `onclick=Intercom('showNewMessage', 'Stel je vraag/Ask a question:')` it will open a new chat.

**Comment by andreleon** [comment]
@ralphboeije @AriellevdLinde All i need now is the final version of the slides (with appstore icons??)

**Comment by ralphboeije** [comment]
Just found the minor issue with the slider. When reaching the end of the slider and going back to the first, the animation reverses direction, which breaks the visual smoothness.

**Comment by AriellevdLinde** [comment]
@andreleon @ralphboeije 
Looks very good! I have some updates and some feedback. First the update: the slides with the app icon are now on zeplin (in this [design](https://zpl.io/Z1g9rOI), you can find the english version of the appstore icons in the second slider). Also the right chat is now updated for the slider.

My feedback:

**Header**
What I understood from the homepage meetings is that you will only see more of the homepage when clicking on the button, but I think this will be a good AB test. My guess it will be better to already scroll down. At the moment I think it is not going that fluently. Also, when clicking on the button, I still stay at the header position, while I think it would be better if you already move to the "what is part-up" block. 

**What is part-up** 
I would like to see as much margins on the top of the video as on the bottom. That way we will use the margins more consistent. 

**Are you looking for**
 the buttons should have more padding on the sides (see Zeplin). I also have the idea that they are not aligned. on the top there is more padding then on the bottom (if you count only the small letters)

**Slider**
I like the slider with only the screens changing. 

**What means part-up for your organisation**
When clicking on the different links, It looks like the images aren't loading smooth. 

**More information form**
Also here the button is not aligned right (see zeplin for paddings)

**Footer**
Also the bottom with social icons, is not aligned vertically.

**Comment by ralphboeije** [comment]
@andreleon re the form and the button on-click result:
- Form needs to be connected to [Marketo API](http://developers.marketo.com/rest-api/endpoint-reference/lead-database-endpoint-reference/#!/Leads/pushToMarketoUsingPOST), so that is too much for now. Let's just comment out this part for the first release.
- Button on-click result is language dependent URL. Could you make it into a phraseapp key, such that I can set them myself?
