### ISSUE TITLE
Marketo Tracking Code

### ISSUE THREAD

**Issue by andyhoek** [part-up/part-up#725]
Can the tracking code for Marketo be placed in the head of the HTML?

This is the code:

<script type="text/javascript">
(function() {
  var didInit = false;
  function initMunchkin() {
    if(didInit === false) {
      didInit = true;
      Munchkin.init('449-VWG-450');
    }
  }
  var s = document.createElement('script');
  s.type = 'text/javascript';
  s.async = true;
  s.src = '//munchkin.marketo.net/munchkin.js';
  s.onreadystatechange = function() {
    if (this.readyState == 'complete' || this.readyState == 'loaded') {
      initMunchkin();
    }
  };
  s.onload = initMunchkin;
  document.getElementsByTagName('head')[0].appendChild(s);
})();
</script>

**Comment by ralphboeije** [comment]
Let's wait for the costs for SSL in Marketo before doing this as discussed with @andyhoek and @wouterd

**Comment by ralphboeije** [comment]
@wouterd and @andyhoek is it already clear if we can keep the secure state in the browser when using this tracking code?

**Comment by noelheesen** [comment]
@andyhoek I've created a branch with the script inside the <head> tag, you can test it here https://feat-marketto-script.staging.part-up.com/

**Comment by wouterd** [comment]
At the moment we're violating the "cookie law" by always running the marketo code, we need to ask for permission to track people before running this code.

Also, you're putting even more render-blocking javascript in the head, this kind of "non-neccesary" javascript should go in the bottom of the body.

Why are you creating the html tag that has the script using javascript instead of just adding the script tag to the html?

**Comment by noelheesen** [comment]
@wourterd I have changed how the script loads, please let me know if it meets the requirements? You can see the changes in the commit and test it on staging when it's done.

**Comment by andyhoek** [comment]
WJ and I have tested the tracking code on the staging branch, but we aren't
receiving any data.

We did receive data when we tested on the 21 of april.

@andyhoek <http://www.twitter.com/andyhoek> | LinkedIn
<http://nl.linkedin.com/in/andyhoek> | Invalshoek <https://invalshoek.nl>

2017-04-28 15:23 GMT+02:00 Noël Heesen <notifications@github.com>:

**Comment by wouterd** [comment]
Should start receiving data gain, the script loaded didn't quite work.

**Comment by noelheesen** [comment]
How to test:

1. Open the developer tools and select the first tab to view the DOM tree
2. If you have already accepted the cookies a script that says 'Munchkin.js' should be visible
3. Delete the cookies from acceptance.part-up.com and refresh your browser. This should make the cookiebar re-appear and the marketo script disappear
4. When accepting the cookies the marketo script should re-apper
