### ISSUE TITLE
Redo activity invite modal like network and part-up invite modals

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#733]

**Comment by noelheesen** [comment]
Bij de Tribe invite modal:
- Is de lookup wel goed? partpers van partup, members van tribe.
- Als iemand member is dan staat er bij pending invites dat deze partner is. dit suggest van een partup ipv member van een tribe.

**Comment by noelheesen** [comment]
Nice to have:
- De tabs van de tabview staan te veel naar links;
- De picker in tab 1 heeft te veel padding waardoor de tekst niet meer geheel leesbaar is.

**Comment by prik** [comment]
The lookup for tribe invites works as it should. The copy says 'Partner', but should be 'Member'.
Not sure if there is already a separate Phraseapp key for this, or if the front-end needs to implement one.

About the Partner in re-invite: this is also a member of a tribe, so same story as above. Not sure however why the member is still in the re-invite list. I thought this was already fixed. On which tribe did you see this?
