### ISSUE TITLE
Pending invites should not show existing partners and supporters

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#738]
<img width="1440" alt="screen shot 2016-10-26 at 20 08 41" src="https://cloud.githubusercontent.com/assets/14044235/19738572/3751091e-9bb8-11e6-91c3-7e4cf9ed7925.png">
<img width="1440" alt="screen shot 2016-10-26 at 20 08 48" src="https://cloud.githubusercontent.com/assets/14044235/19738573/376b60de-9bb8-11e6-903d-05b9c38c943f.png">

**Comment by andreleon** [comment]
I researched this a bit, and it seems to be a backend issue. I think it could be fixed with a migration, but I am unsure. I will comment on this during the planning session tomorrow
