### ISSUE TITLE
Notification-name showing instead of content. Translation or placeholder issue?

### ISSUE THREAD

**Issue by jplattel** [part-up/part-up#743]
Here's what I saw: 

<img width="531" alt="screen shot 2016-11-01 at 12 06 09" src="https://cloud.githubusercontent.com/assets/517775/19887929/c5969cf8-a02b-11e6-9414-bd89a109e4e1.png">

**Comment by ralphboeije** [comment]
@jessedvrs I think you missed this one in the #437 issue?

**Comment by andreleon** [comment]
As far as i can see, this is no longer an open issue. If a translation key is showing, it means it needs to be added to the translation json. In the code this key doesn't appear anywhere. Also I think this was fixed long ago.

**Comment by ralphboeije** [comment]
sorry about this @andreleon thought I checked it, but this is probably only in the app, not in the web
