### ISSUE TITLE
Responsive header

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#744]

**Comment by AriellevdLinde** [comment]
#583 is related

**Comment by ralphboeije** [comment]
+ check responsiveness improvements of the last release

**Comment by AriellevdLinde** [comment]
@ralphboeije Here you can find a prototype for the responsive topbar (and in-part-up navigation): https://marvelapp.com/92bge96

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon 
Here you can find all the screens I've designed for the responsive header (you can also find them in Zeplin):

**1.1 Logged in menu**
![744 1 1 iphone 375px - menu](https://cloud.githubusercontent.com/assets/22590642/20490016/df12abb8-b00c-11e6-9b81-876cbffcd548.png)

**1.2 Profile menu**
![744 1 2 iphone 375px - menu - profile](https://cloud.githubusercontent.com/assets/22590642/20490017/df13aa40-b00c-11e6-9d4f-b2ea419ea459.png)

**1.3 Profile menu - more**
![744 1 3 iphone 375px - menu - profile more](https://cloud.githubusercontent.com/assets/22590642/20490018/df17830e-b00c-11e6-938b-1203679ab287.png)

**2.1 My tribes menu**
![744 2 1 iphone 375px - my tribes](https://cloud.githubusercontent.com/assets/22590642/20490020/df187ade-b00c-11e6-93a5-44c6f9b99430.png)

**2.1 My tribes menu - tribe selected**
![744 2 2 iphone 375px - my tribes - tribe selected](https://cloud.githubusercontent.com/assets/22590642/20490019/df1859aa-b00c-11e6-9f39-374febed1ecd.png)

**3.1 In-part-up - part-up info**
![744 3 1 iphone 375px - menu - part-up info](https://cloud.githubusercontent.com/assets/22590642/20490021/df18e5f0-b00c-11e6-981f-a46f682103cf.png)

**4.1 In-part-up - navigation activities**
![744 4 1 iphone 375px - in-part-up navigation activities](https://cloud.githubusercontent.com/assets/22590642/20490023/df260438-b00c-11e6-851a-1ce3df88618f.png)


**5.1 Chat menu (with CTA to app)**
![744 5 1 iphone 375px - chat](https://cloud.githubusercontent.com/assets/22590642/20490022/df263962-b00c-11e6-93a5-cd1fc6d2a16d.png)

**6.1 In-part-up - navigation menu**
![744 6 1 iphone 375px - notifications](https://cloud.githubusercontent.com/assets/22590642/20490024/df2d5f6c-b00c-11e6-8fb4-f81d823449b4.png)

**7.1 In-part-up - Menu not logged in users**
![744 7 1 iphone 375px - menu niet ingelogd](https://cloud.githubusercontent.com/assets/22590642/20490025/df2f0fa6-b00c-11e6-9bf0-6fac3367550e.png)
