### ISSUE TITLE
Tribe tile responsive

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#745]

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon 
I've made a first version for the responsive tribe tiles on the "discover tribes" page:

**>768px (tablet portret)**
![1 1 ipad 768px - discover](https://cloud.githubusercontent.com/assets/22590642/20306071/eb663a0c-ab38-11e6-9d87-44b621fbefce.png)


**<768px - (smaller then tablet)**
![1 2 ipad 768px - discover](https://cloud.githubusercontent.com/assets/22590642/20306092/feedd026-ab38-11e6-8b7f-bb1ec1b1475f.png)


**375px (mobile)**
![2 iphone 375px - discover](https://cloud.githubusercontent.com/assets/22590642/20306144/2cf65718-ab39-11e6-8407-1a0c7dd5e6f6.png)

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon 
Here you can also find the responsive (375px) version of **discover part-ups** and **recommended**:

**Discover part-ups**
![745 3 iphone 375px - discover part-ups](https://cloud.githubusercontent.com/assets/22590642/20487262/fdc481bc-b002-11e6-8fdb-dcb2adadc634.png)

**Recommended**
![745 4 iphone 375px - recommendations](https://cloud.githubusercontent.com/assets/22590642/20487261/fdc3c498-b002-11e6-8208-97c120addf9c.png)

**Comment by ralphboeije** [comment]
Great! Minor detail is to also limit the copy to Part-ups selected for you. I can and will do that in Phraseapp.

**Comment by AriellevdLinde** [comment]
Here you can also find the unfolded filter: 
![745 5 iphone 375px - discover part-ups - filter](https://cloud.githubusercontent.com/assets/22590642/20488142/483fb484-b006-11e6-94fe-e04b11fe397f.png)

@ralphboeije In the designs I left three lines of text, or do you also want two lines of text here?
