### ISSUE TITLE
Less prominent place for Leave tribe (and use the button for invite to tribe)

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#748]
DoD:
- Change current button for leave tribe to Invite (and color to orange)
- Add settings cog next to button which opens a dropdown with link to settings (admin only) and "End membership" (is now "leave tribe" options)

**Comment by noelheesen** [comment]
@ralphboeije Are there any design specifications for the cog-wheel?

Current design:
![tribe-cog-centered](https://cloud.githubusercontent.com/assets/18031130/24949209/179754aa-1f6d-11e7-80f7-09ae02a4b0e3.png)

As you can see the wheel can either match the button to the right or the list items on the left (which are at the bottom). Is the invite button also as you have in mind? It will still behave like before and displays the options: request inv, pending inv, accept inv, and now invite instead of leave.

To change 'leave tribe' to 'end membership' only the phrase key needs to be changed.

**Comment by noelheesen** [comment]
The best I can come up with is the following, but something feels odd about it.

![network-cog-button](https://cloud.githubusercontent.com/assets/18031130/24950653/03a2247a-1f72-11e7-88c7-287b46e656ea.png)

**Comment by ralphboeije** [comment]
@noelheesen No there are no specs, the only comparison is on the part-up page. The second option is indeed a bit odd. I would suggest just the wheel, but maybe put it a little closer to the button. 

My idea is to use the dropdown styling of the share button on a part-up, because:
- better visual relation with the cog
- the dropdown is not half under the invite button, because of left alignment

<img width="384" alt="screen shot 2017-04-12 at 11 36 41" src="https://cloud.githubusercontent.com/assets/14044235/24951337/5624bb52-1f74-11e7-9e65-6fafec48c4e1.png">

**Comment by noelheesen** [comment]
@ralphboeije I have pushed an example to staging so you can test the design and give some feedback. https://feat-tribe-settings-menu.staging.part-up.com/

**Comment by ralphboeije** [comment]
Works like a charm @noelheesen ! The only thing I would like to change is the grey square behind the cog. I think we should remove that.

**Comment by noelheesen** [comment]
@ralphboeije Nice, I'll clean up the old code and create a PR. Should I implement the settings wheel the same way for #711?

**Comment by ralphboeije** [comment]
@noelheesen yes please!

**Comment by noelheesen** [comment]
@ralphboeije I'm currently testing on small screens (reduce browser width). The header changes to a dropdown and I'm not sure how to implement the 'end membership' option. Putting it in the menu makes it even more prominent :man_facepalming:. I'm thinking about moving the 'settings', 'invite members' and 'end-membership' to a cog-wheel for smaller screen sizes?

*As this would greatly increase the complexity of the cog-menu I'm asking before implementation*.

**Comment by ralphboeije** [comment]
@noelheesen I understand your line of thinking, but a cog with a dropdown on mobile is not prefered (also not for #711). My suggestion would be to limit the invite button to the invite icon such that it fits on regular screen sizes next to the menu dropdown. And to add the end membership option to the menu dropdown at the last position).

**Comment by noelheesen** [comment]
@ralphboeije I've been stubborn and asked around. For consistency between all screen sizes I have made an alternative which is now pushed to staging. Please let me know what you think.

**Comment by ralphboeije** [comment]
@noelheesen I can value a professional opinion ;-)! So thanks for being stubborn, as it looks great! Ready for a PR I think.
