### ISSUE TITLE
Access rights toggle of customer access levels should also save on click of toggle

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#751]
- See the toggles on tribe/<tribename>settings/access

This story is needed because:
- the save button is below the fold and because the cog on settings  tribe/<tribename>settings/uppers also saves on change

**Comment by andreleon** [comment]
@ralphboeije Have you considered that the label for the role is required when you enable this role? So when you toggle the role, and the form autosaves, it will display a form error saying that the label input field associated with the role is required.

**Comment by ralphboeije** [comment]
@andreleon didn't consider that no. Don't think the requirement is correct as there is a default label already. So if you can turn the requirement off, I think it is just fine. Or will that give other issues?

**Comment by andreleon** [comment]
@ralphboeije For custom roles there is no default label

**Comment by ralphboeije** [comment]
@andreleon Ok, let's leave the requirement in place then. I think the form error experience is slightly better than the "why didn't the toggle save" experience. But if you have a better idea, I am all ears.
