### ISSUE TITLE
Co-creator level missing

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#754]
In https://pu-acceptance.lifely.nl/tribes/development/settings/partups the cog opens a modal, but this modal misses the co-creators level

In https://pu-acceptance.lifely.nl/tribes/development/settings/uppers the cog misses the co-creators level

ON https://pu-acceptance.lifely.nl/partups/first-native-apps-for-part-up-XrjGFF8Q8eTngTqCT/settings the access rights dropdown misses the co-creators level

**Comment by andreleon** [comment]
This is fixed in commit 4a656388b8245ee9c6af626e66a0b2579ca5d3f7 

In some cases it may be nessesary to re-save the tribe access settings page
