### ISSUE TITLE
Co-creators can't select co-creator level for a part-up

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#756]
To reproduce:
- Go to a tribe in which the logged in user is an admin and which has the co-creators access level enabled
- Go to /settings/uppers and set the access level of a user to co-creator
- Log in with this user and go to this tribe
- Start a part-up in this tribe
- Try to set the access level to co-creator and see that it is not an item in the dropdown

**Comment by andreleon** [comment]
fixed in commit 4a656388b8245ee9c6af626e66a0b2579ca5d3f7
