### ISSUE TITLE
HIGH PRIO: After saving tribe access settings, old settings are gone

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#761]
To reproduce:
- Go to tribe settings, e.g. https://pu-acceptance.lifely.nl/tribes/development/settings/
- Add some access levels with labels, 
- Click save
- Go to tribes/<tribename>/settings/partups and assign these new levels to some part-ups and do the same on tribes/<tribename>/settings/uppers to assign theses new levels to tribe members

- Go back to tribe access settings, e.g. https://pu-acceptance.lifely.nl/tribes/development/settings/access
- Add some settings, e.g. change label or enable a new access level
- Click save
- Check /trbe/uppers to see previously assigned access levels are gone, dito for part-ups
- Go to https://pu-acceptance.lifely.nl/tribes/development/settings/access and see that the previously set acces level is not clickable and disabled
- See that it is gone from the dropdown in the /settings/partups popup that opens on click on the cog option

**Comment by peterpeerdeman** [comment]
was fixed in pr #762

**Comment by peterpeerdeman** [comment]
was fixed in pr #762
