### ISSUE TITLE
Tribe page responsiveness

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#777]
incl placeholder for chat directing people to the app

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon 
Here you can find the responsive screens (375px) for the **tribe** pages. If you would also like to see the tablet version, please let me know. For the menu and breaking points it works te same as the tablet versions of #745 

**1. Tribe page - part-ups**
![777 1 tribe page responsiveness - part-ups](https://cloud.githubusercontent.com/assets/22590642/20714072/1133879a-b64b-11e6-8877-244566753486.png)

**2. Tribe page - chat**
![777 2 tribe page responsiveness - chat](https://cloud.githubusercontent.com/assets/22590642/20714067/112a66d8-b64b-11e6-9951-128db60670ff.png)

**3. Tribe page - leden**
![777 3 tribe page responsiveness - leden](https://cloud.githubusercontent.com/assets/22590642/20714068/112a725e-b64b-11e6-911b-b82eba7bfaaa.png)

**4. Tribe page - over**
![777 4 tribe page responsiveness - over](https://cloud.githubusercontent.com/assets/22590642/20714069/112bc5fa-b64b-11e6-88e3-4c0496502d90.png)

**5. Tribe page - verlaat part-up dropdown**
![777 5 tribe page responsiveness - verlaat part-up](https://cloud.githubusercontent.com/assets/22590642/20714071/112ce5ac-b64b-11e6-8153-733ef1fcc43c.png)

**6. Tribe page - start je part-up**
![777 6 tribe page responsiveness - start je part-up](https://cloud.githubusercontent.com/assets/22590642/20714070/112c52fe-b64b-11e6-89b9-f6d925fe43f5.png)

**7. Tribe page - uitnodigen**
![777 7 tribe page responsiveness - nodig uit](https://cloud.githubusercontent.com/assets/22590642/20714073/11437e70-b64b-11e6-9884-4e5832e979c3.png)

**Comment by ralphboeije** [comment]
@AriellevdLinde only filter dropdown is missing from these designs I guess?

**Comment by AriellevdLinde** [comment]
@ralphboeije Here you can find the filter: 
![777 1 tribe page responsiveness - part-ups](https://cloud.githubusercontent.com/assets/22590642/20925352/bfacfa2a-bbb6-11e6-8898-62ef29fdfd7c.png)

**Comment by ralphboeije** [comment]
I do see a potential issue with the copy here: when selecting archived in filter, the copy now reads: <x> archived part-ups / <x> gearchiveerde part-ups.

**Comment by AriellevdLinde** [comment]
@ralphboeije Hm, I don't know why, but I've uploaded the wrong screen. In my previous post you can find the dropdown. Although there is only one item in it, I wanted to keep the style consistent with the other filters, but maybe we can find another solution for the active/archived part-ups.

**Comment by ralphboeije** [comment]
ah check, I like the consistency. My copy issue is with the header and is general for the responsiveness I guess. How do you think we should deal with longer copy like here?

**Comment by AriellevdLinde** [comment]
@ralphboeije Then I would show it like this (to keep the search/filter on a consistent place):
![777 1 3 tribe page responsiveness - part-ups gearchiveerd](https://cloud.githubusercontent.com/assets/22590642/20927748/390daf0c-bbc3-11e6-8365-7c1f5f59e81b.png)
