### ISSUE TITLE
Login responsiveness

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#778]

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon
Here you can find the responsive screen (375px) for the **login** page. The register and forgot password pages will look the same as the login page.

**Login responsiveness**
![778 1 login responsiveness - login](https://cloud.githubusercontent.com/assets/22590642/20716324/1989e644-b652-11e6-93fc-e9c18f69af51.png)

**Comment by ralphboeije** [comment]
There is an improvement request on the backlog to make the link to Create profile better visible. Depending on when resposiveness is to be fixed, I want to add that improvement to the DoD.

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon 
For https://ft-partup-responsive.staging.part-up.com/login I have little feedback:

- The x close isn't aligned right
- The login button should have the same width as the social login buttons.
- For the visibility of "create profile" I have a simple solution. Use the wording that is also used on the homepage. Also this is something users recognize easily: Meld je aan! or Sign up!

See the design here:
![778 1 login responsiveness - login](https://cloud.githubusercontent.com/assets/22590642/21136797/6ea8fb94-c127-11e6-9b30-d6a145dcf9ae.png)
