### ISSUE TITLE
Fix on-click handler for tags

### ISSUE THREAD

**Issue by eriksoon** [part-up/part-up#780]
All tags currently redirect to discover page. It is needed to make this handler more specific:
- In a tribe: a click on a part-up tag (expanding from part-up tile) should trigger a search on this tribe with this tag as search argument (see original explanation by Erik below).
- On the tribe homepage: a click on the tribe tag should trigger a search on this tribe with this tag as search argument 
- On an activity detail: a click on the lane tag on an activity detail should link to activity board view (NB: tag on activity detail is also broken at this moment, but will be fixed shortly by Noel)

Within the tribe Customer Cocreation of Part-up there are already 34 part-ups. I wanted to make an overview on which ones of them have to do with implementation, and therefore all tagged them 'Implementatie'. When clicking the label 'Implementatie' on the part-up tile, I'm redirected to the discover page. Clicking the label there, doesn't work either. I would expect to get an overview of all part-ups within the tribe with the same label.

**Comment by ralphboeije** [comment]
Second case: When you click the lane tag on an activity detail, you also land on discover instead of on activity board view

**Comment by ralphboeije** [comment]
Third case: when you click on the tags on the tribe homepage. Should be on tribe/part-ups with search on tag
