### ISSUE TITLE
Responsiveness rest

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#788]
- [x] profile
- [x] New message modal
- [x] @ mention dropdown
- [x] 404/closed part-up/closed tribe/not existing swarm page
- [x] modals profile/tribe settings
- [x] what else you can find
- [x] tribe onboarding page

**Comment by AriellevdLinde** [comment]
@ralphboeije here you can find the first draft of the responsive profile (mobile):

**1.1 Wie is...**
![788 1 1 profile page - wie is](https://cloud.githubusercontent.com/assets/22590642/20934238/c32ca3d4-bbda-11e6-89c1-1283220754b0.png)

**1.2 Partner part-ups**
![788 1 2 profile page - partner part-ups](https://cloud.githubusercontent.com/assets/22590642/20934239/c3535402-bbda-11e6-8b31-607ae622be6d.png)

**1.3 Supporter part-ups**
![788 1 3 profile page - supporter part-ups](https://cloud.githubusercontent.com/assets/22590642/20934241/c363c2f6-bbda-11e6-9a15-567b43b7ed5e.png)

**1.4 Partners**
![788 1 4 profile page - supporter part-ups](https://cloud.githubusercontent.com/assets/22590642/20934240/c3637814-bbda-11e6-9c96-eb555946242b.png)

**Comment by ralphboeije** [comment]
Looking good! Much easier now the patterns can be reused I see. Can't find any loopholes right now.

**Comment by ralphboeije** [comment]
Feedback after testing https://ft-partup-responsive.staging.part-up.com/
- Log in should be on the far right
- chevron More menu should be facing down
- After login, you now end up halfway discover page
- part-up updates not loading on first click
- x to close part-up information positioning is off
- Menu dropdown on a part-up has to little padding, menu item height is to small
- chat dropdown app row grey background color missing and erronous double grey line exists
- filter dropdown positioning next to new message button (if copy of filter items is too long, then cut them off)
- EN timestamp runs over title of part-up update (because of AM/PM)
- Pixel perfect: profile image is not 40x40, but smaller
- PP2: small Part-up logo spacing is off, should be a square around the logo
- i icon of part-up information is not right (check zepplin for right icon)

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon 
Here you can find the "new message" modal for mobile. I also made an improved design for desktop, as I think the buttons aren't in the right place at the moment.

# Mobile: 
**2.1 Part-up page - new message modal**
![788 2 1 part-up page - new message modal](https://cloud.githubusercontent.com/assets/22590642/21140690/c918e7c6-c139-11e6-8af1-1564cd38b556.png)

**2.2 Part-up page - add media**
![788 2 2 part-up page - new message modal - add media](https://cloud.githubusercontent.com/assets/22590642/21140698/d74da76e-c139-11e6-8e01-0a0481931e42.png)

**2.3 Part-up page - media added**
![788 2 3 part-up page - new message modal - media added](https://cloud.githubusercontent.com/assets/22590642/21140716/e40e0f20-c139-11e6-863e-4af3ea285422.png)

# Desktop:
 **Desktop 2.1 Part-up page - new message modal**
![788 desktop 2 1 part-up page - new message modal](https://cloud.githubusercontent.com/assets/22590642/21140744/f82095f0-c139-11e6-8b81-d70b734db4d8.png)

 **Desktop 2.3 Part-up page - media added**
![788 desktop 2 3 part-up page - new message modal - media added](https://cloud.githubusercontent.com/assets/22590642/21140750/00994d30-c13a-11e6-9958-922b1a8a3b30.png)

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon 

**4.1 404**
![788 4 1 404 page](https://cloud.githubusercontent.com/assets/22590642/21143876/b4daace0-c148-11e6-8194-119d20f299e5.png)

**4.2 closed tribe**
![788 4 2 closed tribe](https://cloud.githubusercontent.com/assets/22590642/21143885/bfffdb72-c148-11e6-9aec-bfa2c46b0309.png)

**4.3 Closed part-up** 
![788 4 3 closed part-up](https://cloud.githubusercontent.com/assets/22590642/21143902/d45fb984-c148-11e6-83ca-8513865507f8.png)

**4.4 Not existing swarm page**
![788 4 4 not existing swarm page](https://cloud.githubusercontent.com/assets/22590642/21143923/e68a24aa-c148-11e6-88ed-0301bfd8ed85.png)

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon 

**The profile modal with the different menu items:**
![788 5 1 profile modal](https://cloud.githubusercontent.com/assets/22590642/21144483/2827a0b6-c14b-11e6-8e5a-0ad5602a6050.png)

@ralphboeije For the tribe settings: do you have an example of how it looks like? I can't seem to find the settings anywhere :).

**Comment by andreleon** [comment]
![screen shot 2016-12-13 at 17 04 52](https://cloud.githubusercontent.com/assets/1391492/21147814/88934454-c156-11e6-825c-2bac5fc0c379.png)
![screen shot 2016-12-13 at 17 06 39](https://cloud.githubusercontent.com/assets/1391492/21147821/8ab5d3d2-c156-11e6-884e-0db8e79dde9c.png)

>  - filter dropdown positioning next to new message button (if copy of filter items is too long, then cut them off)

There is just way to little room for this

**Comment by ralphboeije** [comment]
Mmm, you definitely have a point here. @AriellevdLinde would it be an idea to make the new message button smaller for mobile, or do we throw away the key C2A too much then? Another (kinda wild) idea is to add this filter to the sub-navigation of the part-up (beneath the updates, activities, documents & Links menu items), as they are all filters anyway?

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon 
Here you can find the responsive tribe page. All designs can also be found in Zeplin. 

**6.1 Tribe page**
![788 6 1 tribe page](https://cloud.githubusercontent.com/assets/22590642/21171738/2b332d7e-c1ce-11e6-8b6a-7690bd73febe.png)

**6.2 Tribe page - scroll**
![788 6 2 tribe page - scroll](https://cloud.githubusercontent.com/assets/22590642/21171739/2b3414dc-c1ce-11e6-9d48-d19cbfbe2a97.png)

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon 
For the filter dropdown: I would suggest to place the sort dropdown also under the filter button. So, when there is both a filter and a sort you can place it all under the filter button. This way the user can find everything in one place and we don't have the dropdown problem next to the "new message" button.

**7.1 Part-up page - sort**
![788 7 1 part-up page - sort](https://cloud.githubusercontent.com/assets/22590642/21172059/0bfff944-c1d0-11e6-80d0-f7cf0e2260ec.png)

**7.2 Part-up page - sort dropdown**
![788 7 2 part-up page - sort dropdown](https://cloud.githubusercontent.com/assets/22590642/21172058/0bfefe90-c1d0-11e6-95b4-0d9826ec7de1.png)

**Comment by andreleon** [comment]
@AriellevdLinde 

![screen shot 2016-12-19 at 16 04 03](https://cloud.githubusercontent.com/assets/1391492/21317292/cc8d3860-c604-11e6-8003-9503dbed3196.png)

Should I put the same navigation here as Profile?

**Comment by andreleon** [comment]
@AriellevdLinde I don't get why the Profile filtering needs to be in a dropdown (active/archived), when the filter itself is already a dropdown. Aren't you making it way too hard on the user by hiding it behind 3 clicks/taps each time the user wants to change it? (1 open "filter", 2 open selector dropdown, 3 selecting the filter)

**Comment by andreleon** [comment]
@AriellevdLinde Here is an example of the "hide behind a dropdown" solution:
![screen shot 2016-12-20 at 10 03 41](https://cloud.githubusercontent.com/assets/1391492/21344416/f614cbac-c69b-11e6-9453-7e3e0c7327d4.png)

As you can see, it makes very little difference:

**Comment by AriellevdLinde** [comment]
@andreleon Yes, sounds like a good idea to also change the tribe menu to a dropdown. I have changed this dropdown menu a little bit, to not give users the idea the button is disabled (with the white text). You can find it here:

![788 1 4 profile page - partners](https://cloud.githubusercontent.com/assets/22590642/21347805/7eb2fd2c-c6aa-11e6-8f90-0db59abc1c56.png)

**Comment by AriellevdLinde** [comment]
@andreleon The profile filtering (active/archived) is in the filter dropdown menu to keep everything consistent. I would suggest to have every sort/filter option in the filter button. For this the user has indeed 3 steps to change the filter, but how many times will the user use this filter?

**Comment by andreleon** [comment]
@AriellevdLinde On a partup-detail I recon the filter is used alot, but that is an assumption on my part.

And what about these? 
![screen shot 2016-12-20 at 12 14 34](https://cloud.githubusercontent.com/assets/1391492/21348542/e77ee1ec-c6ad-11e6-8e87-9d4502ecc67f.png)

**Comment by andreleon** [comment]
@AriellevdLinde I am also having some difficulty with the search functionality on the tribe page because of it's behaviour.

**Comment by AriellevdLinde** [comment]
@andreleon Here you can find the solution for the photo/video button:
![788 1 1 2 profile page - wie is](https://cloud.githubusercontent.com/assets/22590642/21349985/3cf330fe-c6b5-11e6-8888-da2e254c7206.png)

**Comment by AriellevdLinde** [comment]
@andreleon for search on the tribe page I've made this design: 
![777 1 tribe page responsiveness - part-ups](https://cloud.githubusercontent.com/assets/22590642/21350028/7efbad0a-c6b5-11e6-867d-a6727db00a57.png)

Could you explain your issue?

**Comment by andreleon** [comment]
@AriellevdLinde nvm, I had not seen your designs yet

**Comment by AriellevdLinde** [comment]
@andreleon You can find the tribe responsive designs here: #777
