### ISSUE TITLE
Textsearch on discover tribes stores value but doesn't show them

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#791]
@andreleon To reproduce:
1. Go to part-up.com/discover
2. enter text in the search box (e.g. "development")
3. click one of the results
4. Navigate back to the discover page (using back or using my tribes dropdown
5. See that only the search results are shown of step 2 and see that the text of step 2 is not in the search box

<img width="1440" alt="screen shot 2016-12-15 at 00 13 24" src="https://cloud.githubusercontent.com/assets/14044235/21205278/a426ff7a-c25b-11e6-9ce2-e01a1caea12f.png">

**Comment by andreleon** [comment]
fixed in develop
