### ISSUE TITLE
Popular sort on discover tribes does not work correctly

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#793]
see part-up.com/discover. It seems that the least popular are on top instead of the most popular.

**Comment by andreleon** [comment]
I have found the root of this problem, but I, myself, don't know how to fix this.

![screen shot 2016-12-22 at 16 59 18](https://cloud.githubusercontent.com/assets/1391492/21431591/22d23454-c868-11e6-892b-c98f538a1c01.png)

The `Networks.findForDiscover()` method tries to sort the tribes by the non-existing `popularity` field. The cron that is supposed to calculate the `popularity` score of a tribe does not exist.

**Comment by andreleon** [comment]
I am creating a cron that uses the stats of a tribe to determine it's popularity. I ran this cron locally with good results. I think this would be a good fix for the time being until @prik comes back from his vacation.

**Comment by andreleon** [comment]
With @peterpeerdeman 's help I have added chatmessages count of the past 3 months.
