### ISSUE TITLE
"Pending approval" button on two lines

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#797]
related to #710 @AriellevdLinde maybe lose the icon here. In EN it just fits on one line, but I don't know how the relative width of the left column will impact this?

<img width="1440" alt="screen shot 2016-12-19 at 10 47 44" src="https://cloud.githubusercontent.com/assets/14044235/21308173/055de85a-c5d9-11e6-9415-518d2d6e78d4.png">

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon I would suggest to have the buttons always underneath each other, because I think it will not fit on one line in most cases. 

I suggest to have 10px space between the buttons. 

The icon of the "wacht op goedkeuring" isn't correct. It should be the user icon without te +.
