### ISSUE TITLE
Google Drive upload broken

### ISSUE THREAD

**Issue by josjevdk** [part-up/part-up#799]
![schermopname 14](https://cloud.githubusercontent.com/assets/20724922/21346704/d3b9df34-c6a5-11e6-9d7e-c90c927154ff.png)

**Comment by jplattel** [comment]
I could successfully replicate this bug on my mac on the live app.. Calling the Upload API seems broken (also, really weird URL structure for the request?)

**Comment by ralphboeije** [comment]
linked to #789 ??

**Comment by ralphboeije** [comment]
Just tried to reproduce it, but I get the drive pop-up and can select and upload a file. So I can triage it correctly.

<img width="1440" alt="screen shot 2016-12-20 at 11 55 33" src="https://cloud.githubusercontent.com/assets/14044235/21348036/958574de-c6ab-11e6-90bc-e765f3d07185.png">

**Comment by ralphboeije** [comment]
Error message 

GET https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.c_iA8CIT0kk.O/m…sv=1/d=1/ed=1/am=AQ/rs=AGLTcCN6ekOcg8FdubsbNtuPlkWrYLR6Mg/cb=gapi.loaded_0 
V @ rpc:shindig_random.js?onload=init:7
Y @ rpc:shindig_random.js?onload=init:11
Z @ rpc:shindig_random.js?onload=init:9
(anonymous) @ rpc:shindig_random.js?onload=init:11
X @ rpc:shindig_random.js?onload=init:11
x.load @ rpc:shindig_random.js?onload=init:11
(anonymous) @ rpc:shindig_random.js?onload=init:12

**Comment by ralphboeije** [comment]
Now I get this error code
<img width="1440" alt="screen shot 2017-01-17 at 13 32 30" src="https://cloud.githubusercontent.com/assets/14044235/22020607/6ef18e24-dcb9-11e6-8890-6120ab5dc50e.png">
