### ISSUE TITLE
Add manual language toggle to homepage

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#817]
Users from eg Spain now report Part-up to be in dutch when they visit the website (not logged in state)

**Comment by ralphboeije** [comment]
decided to do a manual language toggle

**Comment by ralphboeije** [comment]
@AriellevdLinde can you think of a nice way to add it to the home page not-logged in and the user menu dropdown?

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon Here (and on Zeplin) you can find the language switcher:

![817 1 homepage - language dutch](https://cloud.githubusercontent.com/assets/22590642/22296725/65e9755e-e31b-11e6-9107-6c188fae2424.png)
![817 1 2 homepage - language dutch - dropdown](https://cloud.githubusercontent.com/assets/22590642/22296721/65e2808c-e31b-11e6-9e28-da66fd76b4c6.png)
![817 ipad 768px - 1 homepage - language dutch](https://cloud.githubusercontent.com/assets/22590642/22296723/65e335ae-e31b-11e6-8c3e-c050ed92ee1b.png)
![817 iphone 375px - 1 homepage - language dutch](https://cloud.githubusercontent.com/assets/22590642/22296722/65e31aec-e31b-11e6-9f58-ae1d7d6c68fe.png)

**Comment by andreleon** [comment]
language switch is now part of ft-homepage-redesign
