### ISSUE TITLE
Disable link fetcher on one-on-one chat

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#818]
![img_5289](https://cloud.githubusercontent.com/assets/14044235/21718923/ee1a1600-d41a-11e6-9406-2c5492f77b8a.PNG)

**Comment by ralphboeije** [comment]
@prik will disable the url fetcher on one-on-one for now. I will prioritize this bug again.

**Comment by andreleon** [comment]
This is already disabled
