### ISSUE TITLE
Cookie accept button is behind Intercom button

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#823]
<img width="1440" alt="screen shot 2017-01-09 at 16 05 55" src="https://cloud.githubusercontent.com/assets/14044235/21770882/867e6e34-d685-11e6-83ec-255062e5674d.png">

**Comment by nicolasmarabel** [comment]
@ralphboeije I think this is already done with #912 and #933

**Comment by ralphboeije** [comment]
yes, indeed
