### ISSUE TITLE
Loader needed on discover tribes

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#825]
Currently, the loadtime of the discover tribes is really long. And there is no loader to indicate that it is loading at all.

We need to have a look at the performance and add a loader like we have on the discover part-ups page.

**Comment by andreleon** [comment]
added in commit 89eba3c2a2db93e92aadfe2df6bb8c6d396bbcea

**Comment by prik** [comment]
Morning @ralphboeije, this issue has been fixed (loader and performance improvements). It's in develop, so you can deploy it to acceptance to test the changes.

**Comment by ralphboeije** [comment]
@prik We just released it. @wouterd unfortunately released it immediately to production and therewith I didn't see the things that were not working before release:
- Not all images of uppers are showing (grey placeholder image shows)
- Profile pop-ups do not work correctly

**Comment by wouterd** [comment]
Also, the payload that comes in from the GET is waay more bloated than needed. It should return a JSON with only the data that the frontend needs to render the page. F.ex the Upper gets returned with all his/her partups, supporterOfs, ratings from meurs, etcetc.

**Comment by prik** [comment]
Just pushed 1b55f962ba93eb6e0defe3d7b332d32ca59b38e9 that fixed this issue.
@ralphboeije pop-ups not only always working is a frontend issue that hasn't been investigated yet. If you hover off and then back on it works.
