### ISSUE TITLE
Upgrade to meteor 1.4

### ISSUE THREAD

**Issue by wouterd** [part-up/part-up#826]
Meteor 1.4 has finally moved on from node 0.10 and is supporting node 4.

@peterpeerdeman Any experience yet? Especially with upgrades? :)

**Comment by peterpeerdeman** [comment]
hi @wouterd. we've got some experience upgrading from 1.3 to 1.4. Codewise there is not a lof of scary stuff, I'm not expecting a lot of rework from the upgrade. The hardest change we experienced is the switch from Mongo 2.4 to 3.2, which required us to do a sort of manual dump-upgrade-restore on another project.

In addition to the meteor changes we'd need to update the meteor-build docker image, but we've done that before as well havent we :)

I think this would be an interesting change to pick up during the next development cycle, where we might be able to support the transition a bit while you guys test out the differences, does that sound like an idea @ralphboeije ?

**Comment by ralphboeije** [comment]
@Krijger and @wouterd discussed with @peterpeerdeman that having Shadow running now is a great opportunity to test this. The steps would be:
- Create new db deployment
- Change mongo version to 3.2
- Connect new db to shadow to test backwards compatibility
- Branch off from develop and update to meteor 1.4
- Update meteor build to Node 4 and Meteor 1.4 to create new image
- Deploy new image to shadow
- Connect new db to shadow and test it

Let's discuss friday if we can put it on the sprint backlog?

**Comment by wouterd** [comment]
Yes, let's discuss. Not sure if shadow is the solution here, but some alternate environment definitely is.

**Comment by ralphboeije** [comment]
@wouterd when do you have the time to steps 1-3?

**Comment by wouterd** [comment]
Should be pretty quick to do. Already have the deployment on compose, did the upgrade to the latest 1.3 that should support the new mongodb version. By end of week should be feasible.

**Comment by andreleon** [comment]
In order to fix the Facebook login I need to update Meteor, so I think this would be a good time to try the update. @wouterd can you notify me when you are done with steps 1-3 so?

**Comment by andreleon** [comment]
First issue: fourseven:scss is broken for meteor 1.4, also the SASS synthax is depicated. This means when we upgrade to meteor 1.4 we need to get rid of fourseven:scss and replace it with something else. Also we need to convert every SASS to SCSS

**Comment by ralphboeije** [comment]
are there any converters available, or is it a manual job?

**Comment by andreleon** [comment]
I got partup running again in meteor 1.4, I converted all SASS to SCSS and had to do some work on partup-server (e.g install npm dependencies etc...)

**Comment by andreleon** [comment]
I am going to revert my changes in feat-meteor-upgrade and create a refactor-sass-scss branch. The sass refactoring needs to be done before we upgrade to meteor 1.4 or else every branch will be unable to merge their css changes. After the refactor-sass-scss branch is merged in master, the feat-meteor-upgrade can be done easily by installing the missing npm dependencies.

**Comment by andreleon** [comment]
The feat-meteor-upgrade branch is pushed without SASS conversion, this means it's broken until we can rebase it on master after refactor-sass-scss is merged in master

**Comment by ralphboeije** [comment]
If you create a PR and ask @peterpeerdeman to review it we can merge it to master after he did. I think four eyes on this big one is not a bad thing.

**Comment by andreleon** [comment]
feat-meteor-upgrade has been rebased ontop of master with the new .scss styles. I still had to fix some minor issues, but the styling seems to be fine now. Now onto the nest issue: partups in tribes

**Comment by wouterd** [comment]
I fixed the Dockerfile in the branch to use node 4.8 so that should make it deploy again. Logs showed there was some ES6 that it didn't understand. According to meteor's changelog, the newest meteor 1.4 uses node 4.8.

**Comment by wouterd** [comment]
@andreleon @ralphboeije Staging envs are already on mongo 3, so we can test this upgrade on staging. When we have to go to acc, we need to prep that new DB.

**Comment by andreleon** [comment]
There is an issue with `Meteor.publishComposite` it puts some weird `[__proto__]: {}` property in the parameters object witch causes the powercheck to fail (because it doesn't expect the `[__proto__]: {}` property`.

**Comment by andreleon** [comment]
The publishComposite issue is fixed in commit aad26d3dccd1f04bc96a81bdf29736547e3b9ba7

**Comment by andreleon** [comment]
@ralphboeije The facebook login is also fixed in this branch

**Comment by andreleon** [comment]
@wouterd I think the frontend is ready.

**Comment by andreleon** [comment]
https://github.com/part-up/part-up/pull/1006
