### ISSUE TITLE
Allow media upload to pick files from phone/tablet

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#827]
Scenario: Add a picture from phone (e.g. to set profile picture)

Given I am a logged in user
When I click the Add media button anywhere on Part-up (e.g. user profile)
Then I can choose a picture from my tablet/phone
And I can upload it to part-up

**Comment by jplattel** [comment]
For now I've hidden the upload from computer button on mobile & tablet views to upload a file until this is fixed. [As this is also relevant to the document upload function](https://github.com/part-up/part-up/pull/1029/commits/408768f39ccda24511ef7dd5e01fa822f5b3a0cf).
