### ISSUE TITLE
Profile pop-up not working on part-up tiles

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#829]
On hoover on profile picture of a partner on a part-up tile (discover/part-ups tab, tribe page/part-up tab), the profile pop-up is not showing anymore. Probably caused by responsiveness improvements to part-up tile.

<img width="1440" alt="x not loading on new part-up tile" src="https://cloud.githubusercontent.com/assets/14044235/21825361/bbf0bb54-d783-11e6-87f4-357aba8bc82f.png">

**Comment by andreleon** [comment]
If I remember correctly, this feature was removed in a performance improvement sprint in the past. I will re-enable this so you can test it on staging.

**Comment by ralphboeije** [comment]
Can't remember that, but I will test it for sure.

**Comment by andreleon** [comment]
Deploying to: https://fix-re-enable-uppercard-discover.staging.part-up.com

**Comment by ralphboeije** [comment]
@andreleon just tested and saw that it only works for logged in users and not for not-logged in users.

**Comment by ralphboeije** [comment]
And there is no PR yet, I believe?

**Comment by andreleon** [comment]
That's weird, there is no built in limitation for non loggedin users...

**Comment by andreleon** [comment]
And i PRed it
