### ISSUE TITLE
Meteor health check for infrastructure deployment

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#830]
Request by @Krijger As an infrastructure I would like to know when a specific Meteor instance is up and running. 

DoD: a URL exists that can be pinged on which your get request can be performed, indicating the above state.

**Comment by ralphboeije** [comment]
@peterpeerdeman do you know if we already have such a health check implemented or have you done so for other projects already?

**Comment by peterpeerdeman** [comment]
Hi @ralph, we use the https://part-up.com/VERSION URL as a health check, but that is currently just an indication if the server is up and does not say anything further about the application status yet. Should not be that big of a story to create a decent /api/health route.

**Comment by Krijger** [comment]
Using /VERSION will probably suffice for now. Once we are in production on Amazon cloud we will monitor 500 return codes to see whether clients experience downtime. If that occurs, this will need to be implemented, but untill then I thank you for the /VERSION url, @peterpeerdeman
