### ISSUE TITLE
Notification bulb and counter shouldn't show when you are on that chat

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#843]
Currently the notification counter and bulb also show when you are in a one-on-one chat and receive a new chat message from that person. This is unwanted, mainly because you can't get rid of it unless you leave /chats and return.

**Comment by ralphboeije** [comment]
related to #712

**Comment by andreleon** [comment]
@ralphboeije I cannot reproduce this, i see this is an old issue and I think we fixed this in the past. Can you confirm/retest this?
