### ISSUE TITLE
Firefox - tribe page content behind header

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#848]
<img width="1440" alt="screen shot 2017-02-02 at 13 28 56" src="https://cloud.githubusercontent.com/assets/14044235/22570434/89c1f70e-e99b-11e6-8ae9-b9dbba7fe977.png">

**Comment by AnnotatedJS** [comment]
I have the same issue on Firefox on win 8 and on Firefox on Ubuntu of dual boot Windows machine win10.

**Comment by ralphboeije** [comment]
Cause: show tribe homepage is on different line than tribe logo+name
