### ISSUE TITLE
Turn sectors into translatable keys

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#849]
In the admin panel, we can set sectors for the tribes. They cannot be changed there and there is no way to translate them. 

My idea is:
- Create key in phraseapp with the new sectors as copy (in multiple languages)
- Add that key to the sectors in the admin tab
- The key should then be translated in the frontend

Complexity: 55

NB: change in front and backend needed to change the model for the sector. Migrations also need to be changed.

**Comment by ralphboeije** [comment]
I think that the bug that currently makes the sector filters "Overheid" and "Finance" not working is related. I changed those sector ID's in the database, but I think that killed the feature. 

I see this error in the console: Exception in template helper: [sprintf] expecting number but found undefined

**Comment by ralphboeije** [comment]
@noelheesen can you also make the sectors appear in alphabetical order in the dropdown?

**Comment by noelheesen** [comment]
I'm improving the 'sector' entity itself to work with auto-generated id's instead of names for #849 I will change the filtering so it compare's auto generated id's which I hope will make filtering easier and more robust.

**Comment by noelheesen** [comment]
@ralphboeije It's now ready on 'feat-sectors' (new branch). When you delete a sector you will get a notification about the amount of tribe it affects. This is not operational yet but let me know if you think it's worth it to add.

**Comment by ralphboeije** [comment]
Yes, that is worth to add, and would also require a list of those tribes. Is that a small thing to add to the query, or would that increase the complexity of this issue too much?
