### ISSUE TITLE
High prio issues from acceptance test

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#855]
Found some issues after acceptance tests on all browsers today. These are the ones that we hope to be able to fix today.

- [x] Safari on Mac: activity detail rendering of lane tag (see att)
- [ ] Edge on win10: can't add lanes (lane not created after adding title)

<img width="1440" alt="screen shot 2017-02-08 at 11 41 16" src="https://cloud.githubusercontent.com/assets/14044235/22738173/9574cb66-ee06-11e6-9df5-c2fe19a049d3.png">

**Comment by peterpeerdeman** [comment]
safari bug should be fixed now. I was not able to reproduce the lane creation error on ie10: https://dl.dropboxusercontent.com/u/4418952/ie10-lane-add.mov

**Comment by ralphboeije** [comment]
edge bug was probably caused by my vm then.
