### ISSUE TITLE
Can't create a part-up

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#862]
To reproduce:
- Go to any tribe
- Click start a part-up
- Fill out form
- Click create part-up
- See that nothing happens and no errors are showing in the console

Have retested on acceptance also.

**Comment by ralphboeije** [comment]
@peterpeerdeman the strange thing is that Eva just created a new part-up, but I still can't and other users also can't. I've also seen some part-up being created over the past days.

**Comment by andreleon** [comment]
@ralphboeije Which users can't create a part-up? I have tried with several now, and all of them were able to create a partup, no problem

**Comment by andreleon** [comment]
@ralphboeije Are there specific tribes where this issue occurs?

**Comment by andreleon** [comment]
@ralphboeije Does absolutely nothing happen, or does the button go into the loading state? 
![screen shot 2017-02-13 at 17 30 45](https://cloud.githubusercontent.com/assets/1391492/22892257/33156a9c-f212-11e6-97f9-96f20f778291.png)

**Comment by ralphboeije** [comment]
Hi @andreleon I currently still have no loading state whatsoever. You can reproduce using my account. Both on acceptance and production. Maybe has to do with me being a tribe admin (but I can also reproduce it in tribes where I am not an admin)? The other user that reported this issue is https://part-up.com/profile/BDr9RGGNESkevhxv7. Eva first also reported the issue, but later created a part-up.

**Comment by ralphboeije** [comment]
Hi @andreleon this is the only thing I see in the console when I click the "Create you part-up" button on acceptance. On production it has the same issue.

<img width="1440" alt="screen shot 2017-02-14 at 09 33 23" src="https://cloud.githubusercontent.com/assets/14044235/22921115/aa44fb60-f298-11e6-957b-2d288f3f5e8c.png">

**Comment by andreleon** [comment]
@ralphboeije I managed to reproduce it, the issue was the new board switch. Since it is essentially a 'fake' custom input, no default value was set to the partup creation actual form. So if you don't click the board_view switch, it won't be set. I fixed it so it sets a default value on form initialisation. I tested and re-tested, and it works fine now.
