### ISSUE TITLE
Add ? explainer tooltip in create part-up form activity view radio button field

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#873]
See screenshot for current state
Desired state is that this radio button field also has a ? with explainer tooltip, like several of the other form fields have (e.g. date and tags)

<img width="1440" alt="screen shot 2017-02-16 at 11 47 54" src="https://cloud.githubusercontent.com/assets/14044235/23018289/c460f16a-f43d-11e6-8683-81a0753759a5.png">

**Comment by nicolasmarabel** [comment]
@ralphboeije This is for each radio, right?

Which is the text that you wants to see here?

**Comment by ralphboeije** [comment]
I think one question mark on the question level (bold text) is just enough. Text will be something like this (I can edit and translate it after the merge using Phraseapp): "For new ideas and projects without a team we advise you to use the list view. This view helps interested users to identify quickly how they can contribute to the part-up. Once you have a team in place, the board view helps you and your team to adopt an agile work process. For more information on an agile way of working, read our blogpost (add url with target=blank: https://blog.part-up.com/blogs/nieuw-op-part-up-agile-samenwerken).
