### ISSUE TITLE
Remove on-click action on activity comments in list view

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#878]
When you click the "comments" link on an activity in the new activity list view with expandable comments, you still land on the activity detail, which is not needed anymore for the new list view.

You can use designs of the personal homepage list view

![000 1 2 personal dashboard - mijn activiteiten](https://user-images.githubusercontent.com/14044235/31798223-cdae5288-b532-11e7-9c55-03eb973ed22e.png)
![000 1 2 2 personal dashboard - mijn activiteiten - wijzig activiteit](https://user-images.githubusercontent.com/14044235/31798224-cdc5c3c8-b532-11e7-9bd2-544731d88909.png)
![000 1 2 3 personal dashboard - mijn activiteiten - uitklap reacties](https://user-images.githubusercontent.com/14044235/31798225-cdddcdba-b532-11e7-87cd-23e336043d94.png)

**Comment by svasquez** [comment]
Hi, how can I contribute?

**Comment by ralphboeije** [comment]
Hi @svasquez if you now MeteorJS you are welcome to contribute to this OS project. You can find the live version on part-up.com. In the [contributing file](https://github.com/part-up/part-up/blob/develop/CONTRIBUTING.md) you can read the technical details on how to start contributing. You can always connect to us on the [development tribe chat]( https://part-up.com/tribes/development/chat).

**Comment by svasquez** [comment]
Hi @ralphboeije,  I don't know MeteorJS but I'd like to learn it.

**Comment by ralphboeije** [comment]
Hi @svasquez what level are you on with NodeJS and JS in general? @noelheesen can share a link with you to a youtube presentation on Meteor. Let's move the conversation to: https://part-up.com/tribes/development/chat please, as this is not really on topic for this issue.
