### ISSUE TITLE
Auto-scroll to bottom after inserting an activity on a lane

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#879]
Current state: When you create a new activity it is placed at the bottom of the lane. If there are more activities in this lane than can fit the vertical space, you don't see the activity being added (and miss out on the great animation).

**Comment by nicolasmarabel** [comment]
<img width="1363" alt="screen shot 2017-02-24 at 10 29 07 pm" src="https://cloud.githubusercontent.com/assets/1412808/23326942/ef98a4d0-fae2-11e6-87a4-e56f48841ae6.png">

**Comment by noelheesen** [comment]
Hello @nicolasmarabel , I've looked into the issue regarding the board view not positioning new items on top. The sorted collection passed in gets re-sorted by the https://github.com/SortableJS/meteor-sortablejs library.

In the file: /partup-client-boardview/BoardView.js
- line 200: Each board has lanes which in turn have an array of activities,
- line 173: each lane gets a handle to sort it's items.

This is as much as I have found out about the inner works of the lib, maybe you can take a look? 

Expected time to solve is: 6hrs+ depending the need for changes to the model.

**Comment by jplattel** [comment]
Looked into this bit as well, it also might have to do with the $addToSet operator of the Lane.prototype.addActivity in `partup-lib/schemas/lane.js`. That might be of help?

**Comment by nicolasmarabel** [comment]
@noelheesen @jplattel Thank you guys! I'm going to look at this between today and tomorrow and I let you know

**Comment by nicolasmarabel** [comment]
@jplattel  I looked into $addToSet operator, $addToSet only ensures that there are no duplicate items added to the set and does not affect existing duplicate elements. $addToSet does not guarantee a particular ordering of elements in the modified set.

@noelheesen 

In the file: /partup-client-boardview/BoardView.js line 208-210
```
lane.activities = (lane && lane.activities || []).map(function(activityId, activityIndex) {
   return Activities.findOne(activityId);
}).filter(function(activity) { return !!activity; });
```

and the line 239-241
```
lane.activities = (lane && lane.activities || []).map(function(activityId, activityIndex) {
   return Activities.findOne(activityId);
}).filter(function(activity) { return !!(activity && !activity.isRemoved()); });
```

I've tried adding this ```.sort(Partup.client.sort.dateDESC.bind(null, 'created_at')) ``` after  ```.filter()``` and it works fine ... **BUT** the drag order is lost.

**Comment by ralphboeije** [comment]
Just discussed with Peter and Nick and the latter suggested to not make it a backend fix, but to change the story to "Auto-scroll to bottom after inserting an activity on a lane". This is also the behavior on Trello. I think that is a good idea and will change the issue accordingly. Sorry for the research work that went into this one. I hope you learned a lot from it.

**Comment by nicolasmarabel** [comment]
@ralphboeije I agree with you, it's a good idea. This worked at some point? Look at this issue #152  and this changes [commit](https://github.com/part-up/part-up/commit/a18f88bc065d0ef29f8b7d6b4e785a315c0935b3) .

Should be working in this way, right?

**Comment by ralphboeije** [comment]
Thanks for refreshing my memory! ;-) Yes, indeed, it should be working, but it isn't. I have no clue why it isn't.

**Comment by nicolasmarabel** [comment]
@ralphboeije At first glance I do not see any changes in this issue #710 have affected the behavior of the Auto-scroll.  I'm going to research more in depth.

**Comment by ralphboeije** [comment]
in the commits related to that epic (was a bit more than one story actually), we changed the lay-out of the part-up page and the scrolling behavior on that page. I don't know if it could have affected auto-scroll, so it might not be the right place to look for why it isn't working. But in terms of knowledge of the history it is good to know and might lead you to the right place to fix. If not, feel free to drop this one and focus on more rewarding fixes that also help you learn the things you want to learn from this full-scale meteor implementation. Don't feel obliged to finish it, if it doesn't bring you the energy.

**Comment by nicolasmarabel** [comment]
I don't feel obliged, in fact, I like research and learn along the way =)
Maybe it doesn't make sense this pull request #909 until we have it resolved.
I'm going to look at some files, if someone remember any changes that has to do with this, it would be great ! =)

**Comment by ralphboeije** [comment]
@jplattel said that it is probably because in that commit the scroll is on the window and not in the div of the lane. That might help you nail this one @nicolasmarabel ?

**Comment by nicolasmarabel** [comment]
@ralphboeije Yes! I'll look into this today. Thanks

**Comment by noelheesen** [comment]
This was fixed a while ago
