### ISSUE TITLE
Untranslated buttons on new activity detail

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#884]
The new activity detail (collapse, unfold) probably has hardcoded copy on the Join/Invite buttons as there is no English version (see screenshot).
<img width="1440" alt="screen shot 2017-02-16 at 20 45 57" src="https://cloud.githubusercontent.com/assets/14044235/23038126/2ad43dda-f489-11e6-9d90-20b6493b3dab.png">

**Comment by ralphboeije** [comment]
I think it is found here: /Projects/part-up/app/packages/partup-client-pages/app/partup/activities/activity/view/view.html

**Comment by nicolasmarabel** [comment]
Hi @ralphboeije ! I would like to contribute on this one.
I follow all the steps in order to contribute but I get this error:
remote: Permission to part-up/part-up.git denied to nicolasmarabel.
fatal: unable to access 'https://github.com/part-up/part-up.git/': The requested URL returned error: 403

**Comment by partupadmin** [comment]
Hi @nicolasmarabel very welcome! I think I have to add you as contributor for you to get access to the repo and push a PR to develop. I'll do that now for you.
