### ISSUE TITLE
Links in footer are not all correct

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#887]
- Terms and Privacy policy link is not build right: Link tooltip has right URL - terms.part-up.com, but on click you land on part-up.com/terms.part-up.com (nb check these have target=blank)
- FAQ link misses target=blank
- Add developer entry (like in more menu)
- link to open intercom should also work on smaller screen size
- socials (right lower corner) do not have target=blank

**Comment by vanessa-bell** [comment]
Hi! I'm a first-time open source contributor, and I'd like to help out with this

**Comment by partupadmin** [comment]
HI Vanessa, that would be great! Do you know about MeteorJS? @ralphboeije can give you push access to the repo, and you can read on the contributing file about our conventions and such.
