### ISSUE TITLE
Set default language to tribe language for not-logged in users

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#889]
As a visitor (e.g. invited person), I want the Part-up language to be set to English, when the tribe page is also in English. 

Example: visit https://part-up.com/tribes/kampusklubi using VPN from abroad and see that the content the tribe admin put in there is in English, but the buttons and header are in Dutch.

**Comment by andreleon** [comment]
@ralphboeije fixed in commit 88396c461598f5c148a306c387d5b6e38a60f499

**Comment by ralphboeije** [comment]
@andreleon @peterpeerdeman Although it seems to work nicely on local env, it doesn't work on staging and acceptance.part-up.com. @wouterd thought it has to do with Ik denk dat het een conflict between bootstrap.js on the client and this fix. It looks like the first wins. When you run this code on the client, it does work, he says. The result is that the header and buttons are still in Dutch for not logged in users on tribes with language=en.

Tested on several tribes of which language=en, e.g. https://acceptance.part-up.com/tribes/development with In Private window and with and without VPN (Finland).

As this is quite urgent, I hope we can find a fix for this this morning.

<img width="1440" alt="screen shot 2017-02-21 at 07 52 49" src="https://cloud.githubusercontent.com/assets/14044235/23153799/c3802204-f80a-11e6-9710-4998a2d48cd5.png">
