### ISSUE TITLE
High prio: activities not visible in lane

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#907]
Issue:
- after deleting one activity, all activities are not visible in the backlog lane anymore
- when you change the view of the activities (in partup/settings) you see that the activities still exist

https://part-up.com/partups/community-management-Pj2dLoWtamQq58atR/activities

**Comment by andreleon** [comment]
Fixed in develop

**Comment by ralphboeije** [comment]
@prik did you see that this migration creates an error and breaks the build process? see #916
