### ISSUE TITLE
Notifications dropdown content runs over bottom of dropdown

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#913]
<img width="1440" alt="screen shot 2017-02-27 at 13 59 45" src="https://cloud.githubusercontent.com/assets/14044235/23362884/1e1653e0-fcf8-11e6-80e8-cb764039943e.png">

**Comment by JamieDawson** [comment]
I'll take a look at this and see what I can do!

**Comment by ralphboeije** [comment]
Hi @JamieDawson, you are more then welcome. Feel free to join the part-up dev tribe: https://part-up.com/tribes/development. What brought you to this OS project?

**Comment by JamieDawson** [comment]
Thanks for the link to the tribe @ralphboeije! I jumped on this project because I'm trying to improve my skills as a programmer who can work with others. This project is a really neat idea for meeting like-minded people, so I figured it would be nice to be apart of this in some way.

**Comment by ralphboeije** [comment]
Great to have you in the tribe. If you have any questions regarding contributing, you can use the tribe chat. The core team of this project is more than happy to assist you in your contributions! The Contributing.md should be self-explanatory, but don't hesitate to ask any questions you might have.

**Comment by JamieDawson** [comment]
I used Dev-Tools to find the bit of code I need to edit, but I'm unable to find the code I need to edit on Github.  How would I search up the code necessary to edit the personal chat dropdown page?  (See attached) 

![page 1ex](https://cloud.githubusercontent.com/assets/16840579/25970592/2e31842c-3667-11e7-85d0-124008cd56b4.png)

**Comment by JamieDawson** [comment]
I believe figured out the issue. Just have to take  **{.pu-dropdown-notifications-chats ul{max-height:490px}**  and change the max-height to **470px.**  Found the code through Dev-Tools but unable to find by searching Github.
Here are all the stops I found the code through Dev-Tools.
![partup code issue](https://cloud.githubusercontent.com/assets/16840579/26016953/329e49ae-3735-11e7-9020-c97df73beb44.png)

**Comment by noelheesen** [comment]
@JamieDawson Hi, because of .SCSS the class 'pu-dropdowns-notifications' is defined as followed:

`.pu-dropdown {
  &-notifications {
  }
}`

If you have any more questions please let me know :)
Yours,

**Comment by JamieDawson** [comment]
https://github.com/part-up/part-up/pull/1075

I've created a pull request that requires a review.

**Comment by noelheesen** [comment]
Hello @JamieDawson , thanks for the help! I have looked into the pull requests #1074 & #1075 and noticed the file you have changed. The file changed in the commit is generated based on our `.scss` files. 
When searching for `.pu-dropdown { &-notifications { } } ` it will still come up in the search results of your editor. We should just ignore this file and look for files with the `.scss` extension. Often I use GIT itself when I want to search something as it's more than useful.  

Could you apply the fix **[here](https://github.com/part-up/part-up/search?utf8=%E2%9C%93&q=%26-notifications&type=)** and commit a new PR? We also have a page about how to **[contribute](https://github.com/part-up/part-up/blob/master/CONTRIBUTING.md)** to help you out.

If you have any questions please let me know.
Yours,
