### ISSUE TITLE
Add conversations tab to part-ups

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#921]
DoD:
- Extra tab called "Conversations" added to part-up navigation
- On this tab show all:
 - Messages
 - All updates that have one or more comments

**Comment by noelheesen** [comment]
@ralphboeije Do you have a specific 'picon' in mind to use with the new tab?

**Comment by noelheesen** [comment]
@ralphboeije  I have found the picons partup uses, they are in app/public/fonts/icons. I have selected 'message' from the 1st ttf file. We can always change this on a later stage.
![conversations-picon](https://cloud.githubusercontent.com/assets/18031130/25579393/e982c620-2e77-11e7-80fa-e311f5780c2c.png)

**Comment by noelheesen** [comment]
@ralphboeije @jplattel I'm unsure whether to make the new conversations tab the new main tab when entering a partup.

**Comment by jplattel** [comment]
@noelheesen lets discuss this today, curious on your opinion why you are unsure about it :)
