### ISSUE TITLE
Upgrade FB api version

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#930]
https://developers.facebook.com/apps/361616407358764/alerts/?ref=email&alert_id=1291959350883326
 
v2.2 Upgrade Reminder

Part-up currently has access to Graph API v2.2 which will reach the end of its 2-year lifetime on 27 March, 2017. To ensure a smooth transition, please migrate all calls to Graph API v2.3 or higher.

To check if your app will be affected by this upgrade you can use the Version Upgrade Tool. This will show you which calls, if any, are affected by this change as well as any replacement calls in newer versions. If you do not see any calls, your app may not be affected by this change.

You can also use our changelog to see the full list of changes in all Graph API versions.
 
You can view this and other Developer Notifications related to your app, in the App Dashboard.

**Comment by andreleon** [comment]
I tried to update the accounts-facebook and accounts-base packages, but I'm afraid we need to update Meteor first. I keep getting the same message `The specified packages are at their latest compatible versions`.

**Comment by ralphboeije** [comment]
Bummer, have to move fast on the other one then.

**Comment by ralphboeije** [comment]
@andreleon The FB login seems to work, but I now get an error message that the email already exists, when I log in with a FB account user (see screenshot). Can you have a look at it?

<img width="1440" alt="screen shot 2017-04-13 at 08 13 16" src="https://cloud.githubusercontent.com/assets/14044235/24992356/545047d0-2021-11e7-8891-4f5f47ed486f.png">
