### ISSUE TITLE
Improve spacing on activity detail on mobile

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#934]
![img_5486](https://cloud.githubusercontent.com/assets/14044235/23466678/1984fb7e-fe9c-11e6-80e7-1b98b2203179.PNG)

**Comment by ralphboeije** [comment]
NB: also check the render of single activity in updates view on both mobile and desktop

**Comment by noelheesen** [comment]
@ralphboeije I'm really sorry but I forgot where to find the intended design for the activity detail. The one I can find on google drive is outdated.

**Comment by ralphboeije** [comment]
In Zeplin under de #411 tag. https://app.zeplin.io/project/5829d23dbecd687e3fcd1cb0/screen/58331b62bf7ead6e6ab894af and next few designs

**Comment by noelheesen** [comment]
@ralphboeije I have pushed 'fix-activity-spacing-mobile' to staging. It shows the reason why I hate CSS :face_with_head_bandage: Let's discuss this tomorrow.

**Comment by ralphboeije** [comment]
I see, let's see if we can come up with an easy solution tomorrow.
