### ISSUE TITLE
Bulk upload csv too sensitive 

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#959]
Issue: csv upload doesn't work when:
- there are spaces in the first column cells (name)
- there is upper case content in the second column cells (email address)

**Comment by ralphboeije** [comment]
@jplattel it is not completely fixed. I still get an error when I upload a doc. This is what papertrail logs: 

Jun 20 14:08:25 52.213.43.0 meteor_beta-ba39d3e764e2: Exception in callback of async function: TypeError: Cannot read property 'toLowerCase' of undefined
Jun 20 14:08:25 52.213.43.0 meteor_beta-ba39d3e764e2:     at packages/partup-server/routes/csv/csv_routes.js:58:41
Jun 20 14:08:25 52.213.43.0 meteor_beta-ba39d3e764e2:     at arrayMap (/app/programs/server/npm/node_modules/meteor/stevezhu_lodash/node_modules/lodash/index.js:1406:25)
Jun 20 14:08:25 52.213.43.0 meteor_beta-ba39d3e764e2:     at map (/app/programs/server/npm/node_modules/meteor/stevezhu_lodash/node_modules/lodash/index.js:6710:14)
Jun 20 14:08:25 52.213.43.0 meteor_beta-ba39d3e764e2:     at interceptor (/app/programs/server/npm/node_modules/meteor/stevezhu_lodash/node_modules/lodash/index.js:12240:26)
Jun 20 14:08:25 52.213.43.0 meteor_beta-ba39d3e764e2:     at thru (/app/programs/server/npm/node_modules/meteor/stevezhu_lodash/node_modules/lodash/index.js:5927:26)
Jun 20 14:08:25 52.213.43.0 meteor_beta-ba39d3e764e2:     at baseWrapperValue (/app/programs/server/npm/node_modules/meteor/stevezhu_lodash/node_modules/lodash/index.js:2768:30)
Jun 20 14:08:25 52.213.43.0 meteor_beta-ba39d3e764e2:     at LazyWrapper.lazyValue [as value] (/app/programs/server/npm/node_modules/meteor/stevezhu_lodash/node_modules/lodash/index.js:1077:16)
Jun 20 14:08:25 52.213.43.0 meteor_beta-ba39d3e764e2:     at baseWrapperValue (/app/programs/server/npm/node_modules/meteor/stevezhu_lodash/node_modules/lodash/index.js:2761:25)
Jun 20 14:08:25 52.213.43.0 meteor_beta-ba39d3e764e2:     at LodashWrapper.wrapperValue (/app/programs/server/npm/node_modules/meteor/stevezhu_lodash/node_modules/lodash/index.js:6124:14)
Jun 20 14:08:25 52.213.43.0 meteor_beta-ba39d3e764e2:     at packages/partup-server/routes/csv/csv_routes.js:71:26

**Comment by jplattel** [comment]
Thanks for the traceback, will fix this! Looks like an empty field to me? That's undefined so it throws...
