### ISSUE TITLE
Discover should call API for recommended part-ups

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#96]
API needs userID

**Comment by wouterd** [comment]
# Recommended Partups - Discover Page

Name of feature branch: feat-discover-recommendations

## Frontend Meteor
- Extra filter: recommended
- Request to Meteor API with different sort param (relevance)
- New default “discover mode”
- Add CTA to “newest” Part-ups

## Backend Meteor
 - Implement sorting by relevance:
	- Call the Partup API (api.part-up.com) for X recommended part-ups (IDs)
	- Create the objects that the fronted expects (same as other sorting)

## Part-up API (api.part-up.com)
- Implement endpoint that gives recommended partups for a user
	- Input: userId, via url, encrypted with shared secret (api key) => AES, Base64UrlEncoded
	- Output: Partup IDs, sorted by relevance (List)
```
{
	partUpIds: [“18u2ejdlfas”, “9283urfdsalfjasl”]
}
```
	- Calling Principal: “Trusted System” 
	- URL: https://api.part-up.com/partups/recommended/for/user/{userId}

- Create Neo4J Query that grabs X recommended part-up IDs from Neo4J.

## Road to Production
- Package Neo with Recommendation Engine
	- Based Neo docker image
	- include graph aware runtime + reach
	- include recommendation JAR (UBCF)
	- update neo4j.properties
- Deploy Neo on AWS
- Neo + Api + Meteor runnable @local 
- Event processing test
	- Archived partups
	- Fix some properties
- Load test
- Latency test
- Resilience test
- Run an import
