### ISSUE TITLE
Prevent hot reload after release

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#966]
We need to find a way where the user can stick to the old version after a release, until manual refresh (like e.g. Google Inbox does). Because I just found out that one user lost all the content of a message due to an auto refresh after the release.

@wouterd pointed to this discussion meteor forum:

https://forums.meteor.com/t/is-it-possible-to-disable-auto-refresh-and-display-there-is-a-new-version-click-here-to-refresh-message-instead-when-a-new-version-of-my-app-is-deployed/26440

**Comment by wouterd** [comment]
PR #967 stops the auto reload, would be nice if we add the inbox-style "reload message / button" to it before we merge.

**Comment by ralphboeije** [comment]
@noelheesen could you do the fronten part of this issue?

**Comment by wouterd** [comment]
To test on dev, go into the console and type: `Session.set('puWantsToReload', true)`
