### ISSUE TITLE
Document upload on message

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#969]
As a logged in user
When I add a message to a part-up
And I click the Add media dropdown
Then I want to be able to upload a document from my computer
And I want this document to be added as an attachment to the message

Acceptance criteria:
- Upload document (same file formats, same max number of files, same file icons as in Google Drive/Dropbox upload)
- Download document (not yet existent, also needed for current image upload)
- Link is shareable (no auth, just like current Google Drive/Dropbox upload)
- Remove "images only" and "all file types" subtitles from the Add media dropdown
- s3 delete needed
- Metadata needed for clean up function in S3

**Comment by andreleon** [comment]
https://feat-document-upload.staging.part-up.com/

**Comment by ralphboeije** [comment]
@andreleon looking good! Just did a quick test and found one issue:
- after editing a message, and clicking save, the message is not refreshed when the edit includes adding a new file. So you won't see the changes you just made/the new doc you uploaded until you manually refresh.

**Comment by andreleon** [comment]
@ralphboeije i cannot reproducethis
> after editing a message, and clicking save, the message is not refreshed when the edit includes adding a new file. So you won't see the changes you just made/the new doc you uploaded until you manually refresh.

**Comment by andreleon** [comment]
@ralphboeije it seems the IE issue ("on IE11 on Win7 the Computer dropdown item can't be clicked") is an old one and not caused by this new feature. It's a tough one to fix, so you can decide if it's blocking

**Comment by prik** [comment]
I fixed the illegal characters issue @ d362656896845c4c361a167ae832c10abee21c16

**Comment by noelheesen** [comment]
@andreleon , @prik . @jplattel and me have found that on IE&EDGE only images can be uploaded. This is specified in file: app/packages/partup-client-base/client/uploader.js line 299 I'm in doubt why this is and if I can just remove the whole IE file type entry. Any ideas?
