### ISSUE TITLE
Dropbox upload not working

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#974]
These PR's are now live, but now the dropbox links are not created anymore:
- #972 changed linkType to preview (as is specified in https://www.dropbox.com/developers/chooser#js) to fix auto expiration of dropbox links (is default for linkType: direct)
- #965 removed expiration link, because on free accounts this is not allowed
- #961 changed expiration date to very long to fix expiring links

**Comment by noelheesen** [comment]
@ralphboeije Is this fixed now after the changes made by @jplattel ?

**Comment by ralphboeije** [comment]
Yes, this is fixed now
