### ISSUE TITLE
Improve accesibility (tab navigation)

### ISSUE THREAD

**Issue by GiuliaM** [part-up/part-up#981]

**Comment by Murderlon** [comment]
I would say this is a bit too broad for a single issue. It is preferable if an issue can be a single feat or fix branch as well. Beside the fact that accessibility and page speed are two different things, they are also arbitrary on their own. For instance, page speed can be blocking scripts, server response, unoptimized images, etc. Each one of them could be an issue of it's own.

Try to be more specific :)
