### ISSUE TITLE
Improve keyboard navigation by settings focus states on tab able elements. 

### ISSUE THREAD

**Issue by Djaygo** [part-up/part-up#983]
Will do this by styling the ': focus' states and implementing JS for showing submenus.

**Comment by Murderlon** [comment]
This doesn't really describe a problem. What do mean by "obvious tab navigation"?

**Comment by ralphboeije** [comment]
Hi @Djaygo  great that you'll be working on Part-up. As product owner, I am here to answer any question you might have. Can you explain to me why this issue is most important to work on right now?

**Comment by Djaygo** [comment]
Hi @ralphboeije, I created a small video which indicates the problem [Loom Video](https://www.useloom.com/embed/27100bf5699b47738bfebc02af2d4b58). I think this will make the website more accessible for people who can't make use of the mouse or trackpad.

**Comment by ralphboeije** [comment]
I understand the issue, the question for a product owner is always: what is the most important value to be delivered to the users. And not so much: what is the first issue that I come across. You can check this project with issues that is prioritized by users.
