### ISSUE TITLE
Implement service worker to cache assets

### ISSUE THREAD

**Issue by SadisticSun** [part-up/part-up#992]
To improve the loading times and effects on the users bandwidth I will implement a service worker that caches static assets. This will improve speed and Lighthouse scores.

**Comment by ralphboeije** [comment]
Hi @SadisticSun thanks for working on Part-up this week. As a product owner of Part-up, I am always happy to help. This specific issue is already covered in #980 so I think it is best to pick something else to work on that actually can be released to production.

**Comment by ralphboeije** [comment]
check https://github.com/part-up/part-up/issues for all the issues and https://github.com/part-up/part-up/projects/8 for inspiration
